const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,require=()=>({}),extra={}){const ctx={exports:{},require,TextEncoder,TextDecoder,Uint8Array,Response,Request,fetch,btoa,atob,Date,...extra};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);return ctx.exports}
const {GitHubAudioStore,AudioError}=load('supabase/functions/audio-recall-github/core.ts');
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
function github(privateRepo=true){const files=new Map();let serial=0,conflict=false;const requests=[];const transport=async(url,opts)=>{requests.push({url,opts});const path=decodeURIComponent(url.split('/contents/')[1]??'');if(!path)return Response.json({private:privateRepo});const file=files.get(path);if(opts.method==='GET'){if(!file)return new Response(null,{status:404});if(opts.headers.Accept.includes('raw'))return new Response(Buffer.from(file.content,'base64'));return Response.json(file)}const body=JSON.parse(opts.body);if(opts.method==='DELETE'){files.delete(path);return Response.json({})}if(conflict&&path.endsWith('index.json')){conflict=false;return new Response(null,{status:409})}if(file&&body.sha!==file.sha)return new Response(null,{status:409});files.set(path,{content:body.content,sha:String(++serial)});return Response.json({})};return {files,requests,transport,conflict:()=>conflict=true}}
const note=(id='note-1')=>({id,subjectName:'Physics',topicName:'ආලෝකය',createdAt:'2026-10-01T00:00:00Z',durationSeconds:15,mimeType:'audio/webm',content:btoa('test audio bytes')});
test('private GitHub upload, list and playback work across separate store instances',async()=>{const g=github();let store=new GitHubAudioStore('owner/private-audio','server-token',g.transport);await store.assertPrivate();await store.upload(owner,note());store=new GitHubAudioStore('owner/private-audio','server-token',g.transport);const list=await store.list(owner);assert.equal(list.notes[0].topicName,'ආලෝකය');assert.equal('path' in list.notes[0],false);const audio=await store.audio(owner,'note-1');assert.equal(atob(audio.content),'test audio bytes');assert.equal(audio.mimeType,'audio/webm')});
test('account paths isolate libraries and prevent traversal',async()=>{const g=github(),s=new GitHubAudioStore('owner/private-audio','token',g.transport);await s.upload(owner,note());assert.equal((await s.list(other)).notes.length,0);await assert.rejects(s.audio(other,'note-1'),/not found/);await assert.rejects(s.audio(other,'../../'+owner),/Invalid recording/);await assert.rejects(s.list('../other'),/Invalid account/)});
test('public repositories and missing server secrets fail closed',async()=>{const g=github(false),s=new GitHubAudioStore('owner/public','token',g.transport);await assert.rejects(s.assertPrivate(),/private GitHub/);assert.equal(g.files.size,0);assert.throws(()=>new GitHubAudioStore('','',g.transport),/administrator setup/)});
test('retries are idempotent and concurrent index conflicts are retried',async()=>{const g=github(),s=new GitHubAudioStore('owner/private','token',g.transport);g.conflict();await s.upload(owner,note());await s.upload(owner,note());assert.equal((await s.list(owner)).notes.length,1);assert.equal([...g.files.keys()].filter(k=>k.includes('/audio/')).length,1)});
test('deletion propagates as a tombstone and an offline retry cannot resurrect it',async()=>{const g=github(),s=new GitHubAudioStore('owner/private','token',g.transport);await s.upload(owner,note());await s.remove(owner,'note-1');const list=await s.list(owner);assert.equal(list.notes.length,0);assert.equal(list.deletedIds[0],'note-1');await assert.rejects(s.upload(owner,note()),/deleted on another device/);assert.equal([...g.files.keys()].filter(k=>k.includes('/audio/')).length,0)});
test('invalid audio, oversized uploads and invalid details are rejected before writing',async()=>{const g=github(),s=new GitHubAudioStore('owner/private','token',g.transport);await assert.rejects(s.upload(owner,{...note(),content:'***'}),/Invalid audio/);await assert.rejects(s.upload(owner,{...note(),content:'A'.repeat(14*1024*1024)}),/10 MB/);await assert.rejects(s.upload(owner,{...note(),durationSeconds:-1}),/Invalid recording details/);assert.equal(g.files.size,0)});
test('server authorizes the verified account and ignores caller-supplied user IDs',async()=>{let handler,scoped;const stub={AudioError,GitHubAudioStore:class{async assertPrivate(){}async list(uid){scoped=uid;return {notes:[]}}}};load('supabase/functions/audio-recall-github/index.ts',name=>name.includes('supabase-js')?{createClient:()=>({auth:{getUser:async()=>({data:{user:{id:owner}},error:null})}})}:stub,{Deno:{env:{get:()=> 'test'},serve:fn=>handler=fn}});let response=await handler(new Request('https://example.test',{method:'POST',body:JSON.stringify({action:'list',userId:other})}));assert.equal(response.status,401);response=await handler(new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer verified-token'},body:JSON.stringify({action:'list',userId:other})}));assert.equal(response.status,200);assert.equal(scoped,owner)});
const client=load('lib/audioRecallStorage.ts',name=>name==='react-native'?{Platform:{OS:'web'}}:name.includes('supabase')?{supabase:{}}:{});
test('refresh merges recordings without discarding local drafts or reviving deleted notes',()=>{const local=[{id:'draft',createdAt:'2026-10-02',uri:'local',synced:false},{id:'old',createdAt:'2026-10-01',uri:'local-old',synced:true}],remote=[{id:'new',createdAt:'2026-10-03',synced:true}];const rows=client.mergeRecalls(local,remote,['old']);assert.equal(rows.length,2);assert.equal(rows[0].id,'new');assert.equal(rows[1].id,'draft');assert.equal(rows[1].uri,'local')});
