const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,require=()=>({})){const ctx={exports:{},require};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);return ctx.exports}
const {nextPaperName}=load('lib/paperNaming.ts');
const row=(id,subjectName,title,testDate='2026-01-01')=>({id,subjectName,title,testDate});
test('each subject starts and advances its own paper series',()=>{const rows=[row('1','Physics','Paper 5'),row('2','Chemistry','Paper 2')];assert.equal(nextPaperName(rows,'Physics'),'Paper 6');assert.equal(nextPaperName(rows,'Chemistry'),'Paper 3');for(const s of ['Pure Mathematics','Applied Mathematics'])assert.equal(nextPaperName(rows,s),'Paper 1')});
test('backdated and unnumbered results do not repeat paper names',()=>{const rows=[row('1','Physics','Paper 8','2025-01-01'),row('2','Physics','Paper 2','2026-01-01'),row('3','Physics','Term exam','2026-03-01')];assert.equal(nextPaperName(rows,'Physics'),'Paper 9');assert.equal(nextPaperName(rows,'Physics','1'),'Paper 3')});
test('custom series continue independently within a subject',()=>{const rows=[row('1','Physics','Paper 8'),row('2','Physics','Revision 3','2026-02-01'),row('3','Chemistry','Revision 10','2026-03-01')];assert.equal(nextPaperName(rows,'Physics'),'Revision 4');assert.equal(nextPaperName(rows,'Chemistry'),'Revision 11')});
const theme=load('lib/appTheme.ts');
test('all themes recolour brand colours but preserve status colours and alpha',()=>{for(const option of theme.APP_THEMES){theme.setCurrentAppTheme(option.id);for(const colour of ['#7BD3A2','#E7BC78','#EFA7B3','#FFFFFF'])assert.equal(theme.appColor(colour),colour);assert.match(theme.appColor('#B784FF80'),/^#[a-f\d]{6}80$/i);if(option.id!=='purple')assert.notEqual(theme.appColor('#B784FF'),'#B784FF');}theme.setCurrentAppTheme('purple');assert.equal(theme.appColor('#B784FF'),'#B784FF');assert.equal(theme.isAppThemeId('invalid'),false)});
test('styles react to palette switches without losing dimensions',()=>{const styles=load('lib/themeStyles.ts',name=>name==='react-native'?{StyleSheet:{create:s=>s}}:theme).createThemeStyles({card:{backgroundColor:'#080D14',borderColor:'#B784FF',padding:16,shadowOffset:{width:0,height:2}}});const original=styles.card.backgroundColor;theme.setCurrentAppTheme('blue');assert.notEqual(styles.card.backgroundColor,original);assert.equal(styles.card.padding,16);assert.equal(styles.card.shadowOffset.height,2);theme.setCurrentAppTheme('purple');assert.equal(styles.card.backgroundColor,original)});
