const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,require){const ctx={exports:{},require};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,ctx);return ctx.exports}
function receipt(result){const calls=[];const helper=load('lib/paymentReceipt.ts',()=>({supabase:{storage:{from(bucket){return {async createSignedUrl(path,seconds){calls.push({bucket,path,seconds});return result}}}}}}));return {helper,calls}}
test('a receipt uses the private bucket and a fresh ten-minute signed URL',async()=>{const {helper,calls}=receipt({data:{signedUrl:'https://example.test/private'},error:null});assert.equal(await helper.paymentReceiptUrl('owner/slip.jpg'),'https://example.test/private');assert.deepEqual(calls,[{bucket:'payment-receipts',path:'owner/slip.jpg',seconds:600}])});
test('storage failures and missing links cannot silently open an empty preview',async()=>{let r=receipt({error:{message:'Object not found'}});await assert.rejects(r.helper.paymentReceiptUrl('owner/slip.jpg'),e=>e.message==='Object not found');r=receipt({data:{},error:null});await assert.rejects(r.helper.paymentReceiptUrl('owner/slip.jpg'),/Could not load/);await assert.rejects(r.helper.paymentReceiptUrl('  '),/No payment slip/);assert.equal(r.calls.length,1);assert.match(r.helper.paymentReceiptError({message:'Access denied'}),/Access denied/)});
function viewerHarness(){let states=[],cursor=0,dependencies,cleanup,effect,resolve,reject;const opens=[];const react={useState(initial){const i=cursor++;if(!(i in states))states[i]=initial;return [states[i],v=>states[i]=typeof v==='function'?v(states[i]):v]},useEffect(fn,deps){if(!dependencies||deps.some((v,i)=>v!==dependencies[i])){cleanup?.();dependencies=deps;effect=fn}}};const jsx={jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};const helper=receipt({}).helper;const Component=load('components/PaymentReceiptViewer.tsx',name=>name==='react'?react:name==='react/jsx-runtime'?jsx:name==='react-native'?{Image:'Image',Modal:'Modal',ScrollView:'ScrollView',View:'View',Text:'Text',Pressable:'Pressable',SafeAreaView:'SafeAreaView',ActivityIndicator:'ActivityIndicator',useWindowDimensions:()=>({width:390,height:844}),Linking:{openURL:url=>{opens.push(url);return Promise.resolve()}}}:name.includes('paymentReceipt')?{paymentReceiptUrl:()=>new Promise((a,b)=>{resolve=a;reject=b}),paymentReceiptError:helper.paymentReceiptError}:name.includes('themeStyles')?{createThemeStyles:s=>s}:name.includes('AppThemeContext')?{useThemeRefresh(){}}:name.includes('appTheme')?{appColor:s=>s}:{Ionicons:'Icon'}).default;return {render(){cursor=0;const tree=Component({path:'owner/slip.jpg',reference:'ARC-TEST',onClose(){}});if(effect){const f=effect;effect=null;cleanup=f()}return tree},resolve:v=>resolve(v),reject:e=>reject(e),close:()=>cleanup?.(),opens}}
function nodes(tree){if(!tree||typeof tree!=='object')return [];return [tree,...[tree.props?.children].flat(Infinity).flatMap(nodes)]}
test('preview loads inside the app, supports zoom, and opens the original only on demand',async()=>{const h=viewerHarness();h.render();h.resolve('https://example.test/private');await Promise.resolve();let tree=h.render();let image=nodes(tree).find(n=>n.type==='Image');assert.equal(image.props.source.uri,'https://example.test/private');assert.equal(h.opens.length,0);image.props.onLoad();tree=h.render();const zoom=nodes(tree).find(n=>n.type==='Pressable'&&nodes(n).some(t=>t.type==='Text'&&t.props.children==='Zoom in'));zoom.props.onPress();image=nodes(h.render()).find(n=>n.type==='Image');assert.equal(image.props.style.width,716);const open=nodes(tree).find(n=>n.type==='Pressable'&&nodes(n).some(t=>t.type==='Text'&&t.props.children==='Open original'));open.props.onPress();assert.deepEqual(h.opens,['https://example.test/private'])});
test('closing a preview ignores a late signed URL response',async()=>{const h=viewerHarness();h.render();h.close();h.resolve('https://example.test/private');await Promise.resolve();assert.equal(nodes(h.render()).some(n=>n.type==='Image'),false);assert.equal(h.opens.length,0)});
test('a signing error is displayed in the preview with a retry action',async()=>{const h=viewerHarness();h.render();h.reject({message:'Access denied'});await Promise.resolve();await Promise.resolve();const tree=h.render();assert.ok(nodes(tree).some(n=>n.props.accessibilityRole==='alert'&&n.props.children.includes('Access denied')));assert.ok(nodes(tree).some(n=>n.type==='Text'&&n.props.children==='Try again'));assert.equal(h.opens.length,0)});
