import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React from "react";
import { Image, Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useAppConfig } from "../context/AppConfigContext";

export default function AboutScreen(){
 const router=useRouter();const{settings}=useAppConfig();
 return <View style={s.root}><LinearGradient colors={["#171020","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><Text style={s.title}>About</Text></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <LinearGradient colors={["#392452","#151A25"]} style={s.hero}><Image source={require("../assets/images/study-arc-icon.png")} style={s.logo}/><Text style={s.name}>Study Arc</Text><Text style={s.tag}>A study planning, focus, paper-practice and exam-readiness companion for G.C.E. A/L students.</Text></LinearGradient>
  <Text style={s.section}>HOW STUDY ARC PLANS</Text><View style={s.info}><Text style={s.infoTitle}>Adaptive planning algorithm</Text><Text style={s.infoText}>Study Arc builds daily study recommendations from your available time, sleep, classes, protected time, selected subjects, syllabus progress, weak areas, recent study, paper activity, assignments and examination timing. Classes remain fixed constraints; the planner fills usable time with balanced study or revision work and can prioritize recently covered class topics, weak areas and under-served subjects.</Text><Text style={s.infoText}>Combined Mathematics is selected once by the student, while Pure Mathematics and Applied Mathematics are balanced separately inside planning controls. Missed work can be recovered by rescheduling, splitting, reducing or dropping low-priority work rather than simply pushing the whole timetable forward.</Text></View>
  <Text style={s.section}>READINESS, NOT GRADE PREDICTION</Text><View style={s.info}><Text style={s.infoTitle}>What the readiness percentage means</Text><Text style={s.infoText}>Exam readiness combines recorded syllabus coverage, paper practice, topic mastery, revision consistency and recent revision. It is a study-readiness estimate based on your Study Arc activity. It is not a prediction or guarantee of an examination grade.</Text></View>
  <Text style={s.section}>SUPPORT & LEGAL</Text><Row icon="mail-outline" title="Contact Study Arc" sub={settings.contactEmail} onPress={()=>router.push("/contact")}/><Row icon="cafe-outline" title="Support the Developer" sub="Buy Me a Coffee" onPress={()=>Linking.openURL(settings.buyMeACoffeeUrl)}/><Row icon="globe-outline" title="Official website" sub={settings.websiteUrl} onPress={()=>Linking.openURL(settings.websiteUrl)}/><Row icon="shield-checkmark-outline" title="Privacy Policy" sub="Read Study Arc's data-handling policy" onPress={()=>router.push("/privacy")}/><Row icon="document-text-outline" title="Terms" sub="Terms for using Study Arc" onPress={()=>router.push("/terms")}/>
  <View style={s.privacy}><Text style={s.infoTitle}>Privacy by design</Text><Text style={s.infoText}>Private study sessions, marks, receipts and account data are protected by authenticated Supabase access controls. Administrative analytics should use aggregate operational information unless user-level access is required for account support or access management.</Text></View>
 </ScrollView></View>
}
function Row({icon,title,sub,onPress}:{icon:keyof typeof Ionicons.glyphMap;title:string;sub:string;onPress:()=>void}){return <Pressable style={s.row} onPress={onPress}><View style={s.icon}><Ionicons name={icon} size={22} color="#C6A1F2"/></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{sub}</Text></View><Ionicons name="chevron-forward" size={18} color="#647184"/></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},header:{padding:18,paddingTop:20,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#282033"},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F5F6F8",fontSize:24,fontWeight:"900"},content:{padding:20,paddingBottom:45,maxWidth:720,width:"100%",alignSelf:"center"},hero:{borderRadius:25,borderWidth:1,borderColor:"#5A4273",padding:26,alignItems:"center"},logo:{width:82,height:82,borderRadius:24},name:{color:"#FFF",fontSize:26,fontWeight:"900",letterSpacing:.5,marginTop:14},tag:{color:"#9386A1",fontSize:11,lineHeight:18,textAlign:"center",marginTop:8,maxWidth:500},section:{color:"#7D8999",fontSize:9,fontWeight:"900",letterSpacing:1.25,marginTop:24,marginBottom:9},row:{minHeight:72,borderRadius:18,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:12,flexDirection:"row",alignItems:"center",gap:11,marginBottom:7},icon:{width:44,height:44,borderRadius:14,backgroundColor:"#B784FF15",alignItems:"center",justifyContent:"center"},rowTitle:{color:"#EDF0F4",fontSize:13,fontWeight:"900"},rowSub:{color:"#718092",fontSize:10,marginTop:4},info:{borderRadius:19,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#263241",padding:16,marginBottom:9},privacy:{borderRadius:19,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#263241",padding:16,marginTop:5},infoTitle:{color:"#DDE2E8",fontSize:12,fontWeight:"900"},infoText:{color:"#718092",fontSize:10.5,lineHeight:17,marginTop:7}})
