import{Ionicons}from"@expo/vector-icons";
import{LinearGradient}from"expo-linear-gradient";
import{Redirect,useRouter}from"expo-router";
import React,{useCallback,useEffect,useMemo,useState}from"react";
import{Alert,Linking,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{useAcademicCatalog}from"../context/AcademicCatalogContext";
import{useAppConfig}from"../context/AppConfigContext";
import{useAuth}from"../context/AuthContext";
import{supabase}from"../lib/supabase";

const DOE="https://www.doenets.lk/news";type Row={id:string;exam_year:number;subject_name:string;component_name:string;exam_at:string;duration_minutes:number|null;source_url:string;source_document_version:string|null;amended:boolean;verified_at:string};
export default function AdminExamSync(){const router=useRouter();const{session}=useAuth();const{isAdmin}=useAppConfig();const{subjects,paperComponentsFor}=useAcademicCatalog();const[year,setYear]=useState(String(new Date().getFullYear())),[subject,setSubject]=useState(subjects[0]?.subjectName??"Physics"),[component,setComponent]=useState(""),[dateTime,setDateTime]=useState(""),[duration,setDuration]=useState("180"),[sourceUrl,setSourceUrl]=useState(DOE),[version,setVersion]=useState("Amended timetable"),[amended,setAmended]=useState(true),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);const components=paperComponentsFor(subject);const y=Math.max(2020,Math.min(2100,Number(year)||new Date().getFullYear()));
 const load=useCallback(async()=>{if(!isAdmin)return;const{data,error}=await supabase.from("official_exam_schedule").select("*").eq("exam_year",y).order("exam_at");if(error){setMessage(error.message);return}setRows((data??[])as Row[])},[isAdmin,y]);useEffect(()=>{load()},[load]);useEffect(()=>{if(!component||!components.includes(component))setComponent(components[0]??"Paper I")},[component,components]);
 if(!session)return <Redirect href="/login"/>;if(!isAdmin)return <Redirect href="/(tabs)"/>;
 const save=async()=>{if(!subject||!component||!dateTime.trim()){Alert.alert("Missing exam details","Choose a subject/component and enter the official date and time.");return}const parsed=new Date(dateTime);if(Number.isNaN(parsed.getTime())){Alert.alert("Invalid date/time","Use an ISO-like value such as 2026-08-14T08:30:00+05:30.");return}setBusy(true);setMessage(null);try{const{error}=await supabase.from("official_exam_schedule").upsert({exam_year:y,subject_name:subject,component_name:component,exam_at:parsed.toISOString(),duration_minutes:Math.max(15,Math.min(600,Number(duration)||180)),source_url:sourceUrl.trim()||DOE,source_document_version:version.trim()||null,amended,verified_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"exam_year,subject_name,component_name"});if(error)throw error;setDateTime("");await load();setMessage("Official timetable row saved. Student devices will synchronize matching A/L components automatically.")}catch(e){setMessage(e instanceof Error?e.message:"Could not save timetable row.")}finally{setBusy(false)}};
 const remove=async(id:string)=>{setBusy(true);try{const{error}=await supabase.from("official_exam_schedule").delete().eq("id",id);if(error)throw error;await load()}finally{setBusy(false)}};
 const subjectRows=useMemo(()=>rows.filter(r=>r.subject_name===subject),[rows,subject]);
 return <View style={s.root}><LinearGradient colors={["#11192A","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.title}>Official exam sync</Text><Text style={s.sub}>Department of Examinations timetable mirror</Text></View><Pressable onPress={()=>Linking.openURL(DOE)} style={s.official}><Ionicons name="open-outline" size={17} color="#B9D9FF"/><Text style={s.officialText}>DOE</Text></Pressable></View><ScrollView contentContainerStyle={s.content}>{message?<View style={s.message}><Text style={s.messageText}>{message}</Text></View>:null}<View style={s.notice}><Ionicons name="shield-checkmark-outline" size={21} color="#8BD3A8"/><Text style={s.noticeText}>Enter dates only from the current official Department of Examinations timetable. Study Arc then automatically copies matching subject components into each student's main A/L exam.</Text></View>
 <Text style={s.section}>TIMETABLE YEAR</Text><TextInput value={year} onChangeText={setYear} keyboardType="numeric" style={s.input}/><Text style={s.section}>SUBJECT</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{subjects.map(x=><Pressable key={x.subjectName} onPress={()=>setSubject(x.subjectName)} style={[s.chip,subject===x.subjectName&&s.chipOn]}><Text style={[s.chipText,subject===x.subjectName&&s.chipTextOn]}>{x.subjectName}</Text></Pressable>)}</ScrollView><Text style={s.section}>PAPER COMPONENT</Text><View style={s.chips}>{components.map(x=><Pressable key={x} onPress={()=>setComponent(x)} style={[s.chip,component===x&&s.chipOn]}><Text style={[s.chipText,component===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</View>
 <View style={s.card}><Field label="OFFICIAL DATE/TIME" value={dateTime} onChange={setDateTime} placeholder="2026-08-14T08:30:00+05:30"/><Field label="DURATION MINUTES" value={duration} onChange={setDuration} keyboard/><Field label="SOURCE URL" value={sourceUrl} onChange={setSourceUrl}/><Field label="DOCUMENT VERSION" value={version} onChange={setVersion}/><Pressable onPress={()=>setAmended(v=>!v)} style={s.toggle}><View style={[s.check,amended&&s.checkOn]}>{amended?<Ionicons name="checkmark" size={14} color="#140B1D"/>:null}</View><Text style={s.toggleText}>This is the amended/current timetable</Text></Pressable><Pressable disabled={busy} onPress={save} style={s.primary}><Ionicons name="sync-outline" size={18} color="#130B1C"/><Text style={s.primaryText}>{busy?"Saving…":"Save official component"}</Text></Pressable></View>
 <Text style={s.section}>{subject.toUpperCase()} · {y}</Text>{subjectRows.length?subjectRows.map(r=><View key={r.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{r.component_name}</Text><Text style={s.rowMeta}>{new Date(r.exam_at).toLocaleString()} · {r.duration_minutes??"—"} min</Text><Text style={s.rowMeta}>{r.source_document_version??"Official timetable"}{r.amended?" · amended":""}</Text></View><Pressable disabled={busy} onPress={()=>remove(r.id)} style={s.delete}><Ionicons name="trash-outline" size={17} color="#F0A9B3"/></Pressable></View>):<View style={s.empty}><Text style={s.emptyText}>No official rows for this subject/year yet.</Text></View>}
 </ScrollView></View>}
function Field({label,value,onChange,placeholder,keyboard}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;keyboard?:boolean}){return <View style={{marginTop:9}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#526071" keyboardType={keyboard?"numeric":"default"} autoCapitalize="none" style={s.input}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:"#253247"},back:{width:42,height:42,borderRadius:13,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F4F5F8",fontSize:21,fontWeight:"900"},sub:{color:"#748194",fontSize:9.5,marginTop:3},official:{height:39,borderRadius:12,backgroundColor:"#142033",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:5},officialText:{color:"#B9D9FF",fontSize:9,fontWeight:"900"},content:{padding:20,paddingBottom:50,maxWidth:900,width:"100%",alignSelf:"center"},message:{borderRadius:14,backgroundColor:"#102019",borderWidth:1,borderColor:"#315843",padding:11,marginBottom:9},messageText:{color:"#95D8AE",fontSize:10},notice:{borderRadius:17,backgroundColor:"#102019",borderWidth:1,borderColor:"#315843",padding:13,flexDirection:"row",gap:9},noticeText:{flex:1,color:"#86AA94",fontSize:9.5,lineHeight:15},section:{color:"#8190A3",fontSize:9,fontWeight:"900",letterSpacing:1.2,marginTop:20,marginBottom:8},input:{minHeight:44,borderRadius:12,backgroundColor:"#0B1119",borderWidth:1,borderColor:"#26313F",color:"#EDF0F4",paddingHorizontal:11,fontSize:11},chips:{flexDirection:"row",gap:7,paddingRight:15,flexWrap:"wrap"},chip:{minHeight:36,borderRadius:11,backgroundColor:"#111923",borderWidth:1,borderColor:"#293646",paddingHorizontal:10,justifyContent:"center"},chipOn:{backgroundColor:"#1D3048",borderColor:"#4D789F"},chipText:{color:"#8390A0",fontSize:9,fontWeight:"800"},chipTextOn:{color:"#DCEEFF"},card:{borderRadius:18,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:14},label:{color:"#748194",fontSize:8,fontWeight:"900",letterSpacing:.8,marginBottom:5},toggle:{minHeight:50,flexDirection:"row",alignItems:"center",gap:9,marginTop:10},check:{width:26,height:26,borderRadius:8,borderWidth:1,borderColor:"#4A5768",alignItems:"center",justifyContent:"center"},checkOn:{backgroundColor:"#7EBBF4",borderColor:"#7EBBF4"},toggleText:{color:"#C9D2DC",fontSize:10,fontWeight:"800"},primary:{height:48,borderRadius:14,backgroundColor:"#7EBBF4",alignItems:"center",justifyContent:"center",flexDirection:"row",gap:7,marginTop:8},primaryText:{color:"#130B1C",fontSize:10,fontWeight:"900"},row:{minHeight:73,borderRadius:16,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:12,flexDirection:"row",alignItems:"center",gap:10,marginBottom:7},rowTitle:{color:"#E9EDF2",fontSize:11,fontWeight:"900"},rowMeta:{color:"#748194",fontSize:8.5,marginTop:3},delete:{width:39,height:39,borderRadius:12,backgroundColor:"#29171D",alignItems:"center",justifyContent:"center"},empty:{minHeight:70,borderRadius:16,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#273443",alignItems:"center",justifyContent:"center"},emptyText:{color:"#718092",fontSize:9.5}})
