import{Ionicons}from"@expo/vector-icons";
import{LinearGradient}from"expo-linear-gradient";
import{Redirect,useRouter}from"expo-router";
import React,{useCallback,useEffect,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{useAppConfig}from"../context/AppConfigContext";
import{useAuth}from"../context/AuthContext";
import{supabase}from"../lib/supabase";

type Health={onboardedUsers:number;profilesWithoutSubjects:number;profilesWithoutExamYear:number;usersWithoutManualCoverage:number;usersWithoutRecentStudy:number;overlappingWeeklyClasses:number;catalogSubjects:number;catalogTopics:number;catalogNeedsReview:number;subjectsWithoutTopics:number;officialScheduleRows:number;officialScheduleYears:number[]};
const zero:Health={onboardedUsers:0,profilesWithoutSubjects:0,profilesWithoutExamYear:0,usersWithoutManualCoverage:0,usersWithoutRecentStudy:0,overlappingWeeklyClasses:0,catalogSubjects:0,catalogTopics:0,catalogNeedsReview:0,subjectsWithoutTopics:0,officialScheduleRows:0,officialScheduleYears:[]};
export default function AdminPlannerHealth(){const router=useRouter();const{session}=useAuth();const{isAdmin}=useAppConfig();const[data,setData]=useState<Health>(zero),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{const{data,error}=await supabase.rpc("admin_planner_health");if(error)throw error;setData({...zero,...(data??{})})}catch(e){setError(e instanceof Error?e.message:"Could not load planner diagnostics.")}finally{setLoading(false)}},[]);useEffect(()=>{if(isAdmin)load()},[isAdmin,load]);if(!session)return <Redirect href="/login"/>;if(!isAdmin)return <Redirect href="/(tabs)"/>;
 const issues=data.profilesWithoutSubjects+data.profilesWithoutExamYear+data.usersWithoutManualCoverage+data.overlappingWeeklyClasses+data.subjectsWithoutTopics;
 return <View style={s.root}><LinearGradient colors={["#181025","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.title}>Planner health</Text><Text style={s.sub}>Aggregate checks for scheduling inputs, catalog coverage and exam sync</Text></View><Pressable onPress={load} style={s.refresh}><Ionicons name="refresh" size={18} color="#D5BCEF"/></Pressable></View><ScrollView contentContainerStyle={s.content}>{error?<View style={s.error}><Ionicons name="warning-outline" size={18} color="#F2A7B3"/><Text style={s.errorText}>{error}</Text></View>:null}<View style={[s.hero,issues===0&&s.heroGood]}><Ionicons name={issues===0?"checkmark-circle-outline":"pulse-outline"} size={28} color={issues===0?"#87D9A6":"#DAB9FA"}/><View style={{flex:1}}><Text style={s.heroTitle}>{loading?"Checking planner…":issues===0?"No blocking planner-data issues detected":`${issues} planner-data issues need attention`}</Text><Text style={s.heroSub}>This dashboard uses aggregate counts only; it does not expose private student notes or paper answers.</Text></View></View>
 <Text style={s.section}>STUDENT INPUT HEALTH</Text><View style={s.grid}><Metric label="ONBOARDED" value={data.onboardedUsers}/><Metric label="NO SUBJECTS" value={data.profilesWithoutSubjects} warn/><Metric label="NO EXAM YEAR" value={data.profilesWithoutExamYear} warn/><Metric label="NO MANUAL COVERAGE" value={data.usersWithoutManualCoverage} warn/><Metric label="NO STUDY · 14 DAYS" value={data.usersWithoutRecentStudy}/><Metric label="CLASS OVERLAPS" value={data.overlappingWeeklyClasses} warn/></View>
 <Text style={s.section}>ACADEMIC CATALOG</Text><View style={s.grid}><Metric label="SUBJECTS" value={data.catalogSubjects}/><Metric label="TOPICS" value={data.catalogTopics}/><Metric label="NEEDS VERIFICATION" value={data.catalogNeedsReview} warn/><Metric label="SUBJECTS WITHOUT TOPICS" value={data.subjectsWithoutTopics} warn/></View><Pressable onPress={()=>router.push("/admin-catalog")} style={s.action}><Ionicons name="library-outline" size={20} color="#D8C1F5"/><View style={{flex:1}}><Text style={s.actionTitle}>Open Academic Catalog</Text><Text style={s.actionSub}>Fill missing non-science syllabi and mark topics verified only after checking NIE material.</Text></View><Ionicons name="chevron-forward" size={18} color="#667487"/></Pressable>
 <Text style={s.section}>OFFICIAL EXAM SYNC</Text><View style={s.grid}><Metric label="SCHEDULE ROWS" value={data.officialScheduleRows}/><Metric label="YEARS AVAILABLE" value={data.officialScheduleYears?.length??0}/></View><Pressable onPress={()=>router.push("/admin-exam-sync")} style={s.action}><Ionicons name="calendar-number-outline" size={20} color="#B8D9FF"/><View style={{flex:1}}><Text style={s.actionTitle}>Manage official exam timetable</Text><Text style={s.actionSub}>{data.officialScheduleYears?.length?`Current mirror: ${data.officialScheduleYears.join(", ")}`:"No official timetable rows have been entered yet."}</Text></View><Ionicons name="chevron-forward" size={18} color="#667487"/></Pressable>
 <View style={s.note}><Ionicons name="information-circle-outline" size={20} color="#91AECF"/><Text style={s.noteText}>Planner health identifies missing inputs and structural conflicts. It intentionally does not promise grades or infer exam results.</Text></View></ScrollView></View>}
function Metric({label,value,warn=false}:{label:string;value:number;warn?:boolean}){const bad=warn&&value>0;return <View style={[s.metric,bad&&s.metricBad]}><Text style={s.metricLabel}>{label}</Text><Text style={[s.metricValue,bad&&s.metricValueBad]}>{Number(value??0).toLocaleString()}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:"#2B2337"},back:{width:42,height:42,borderRadius:13,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F4F5F8",fontSize:21,fontWeight:"900"},sub:{color:"#748194",fontSize:9.5,marginTop:3},refresh:{width:42,height:42,borderRadius:13,backgroundColor:"#201829",alignItems:"center",justifyContent:"center"},content:{padding:20,paddingBottom:50,maxWidth:900,width:"100%",alignSelf:"center"},error:{borderRadius:14,backgroundColor:"#28161C",borderWidth:1,borderColor:"#63323E",padding:11,flexDirection:"row",gap:8},errorText:{flex:1,color:"#F2A7B3",fontSize:10},hero:{minHeight:100,borderRadius:20,backgroundColor:"#181421",borderWidth:1,borderColor:"#47365A",padding:15,flexDirection:"row",gap:11,alignItems:"center"},heroGood:{backgroundColor:"#102019",borderColor:"#315843"},heroTitle:{color:"#ECE8F2",fontSize:13,fontWeight:"900"},heroSub:{color:"#7D7388",fontSize:9.5,lineHeight:15,marginTop:4},section:{color:"#8190A3",fontSize:9,fontWeight:"900",letterSpacing:1.2,marginTop:21,marginBottom:8},grid:{flexDirection:"row",flexWrap:"wrap",gap:8},metric:{minWidth:130,flexGrow:1,flexBasis:"30%",minHeight:82,borderRadius:16,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:12,justifyContent:"center"},metricBad:{backgroundColor:"#24171B",borderColor:"#5B343E"},metricLabel:{color:"#718092",fontSize:7.5,fontWeight:"900",letterSpacing:.7},metricValue:{color:"#EDF0F4",fontSize:20,fontWeight:"900",marginTop:6},metricValueBad:{color:"#F2A7B3"},action:{minHeight:70,borderRadius:16,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:12,flexDirection:"row",alignItems:"center",gap:10,marginTop:8},actionTitle:{color:"#E7EAF0",fontSize:11,fontWeight:"900"},actionSub:{color:"#748194",fontSize:8.5,lineHeight:13,marginTop:3},note:{marginTop:19,borderRadius:16,backgroundColor:"#101B26",borderWidth:1,borderColor:"#2A425A",padding:12,flexDirection:"row",gap:9},noteText:{flex:1,color:"#8297AE",fontSize:9.5,lineHeight:15}})
