import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { Redirect, useRouter } from "expo-router";
import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useAppConfig } from "../context/AppConfigContext";
import { useAuth } from "../context/AuthContext";
import { supabase } from "../lib/supabase";

export default function AdminUpdatesScreen() {
  const router=useRouter(); const { session }=useAuth(); const { isAdmin, role }=useAppConfig();
  const [version,setVersion]=useState("1.1.3"),[title,setTitle]=useState("Study Arc v1.1.3 is ready"),[message,setMessage]=useState("Syllabus coverage now measures completed subtopics against your complete selected syllabus."),[url,setUrl]=useState("https://github.com/mathilad/StudyArc/releases/download/v1.1.3/StudyArc-v1.1.3.apk"),[status,setStatus]=useState<string|null>(null),[sending,setSending]=useState(false);
  if(!session)return <Redirect href="/login"/>; if(!isAdmin)return <Redirect href="/(tabs)"/>;
  const send=async()=>{setSending(true);setStatus(null);try{const{error}=await supabase.rpc("admin_publish_app_update",{p_version:version,p_title:title,p_message:message,p_download_url:url});if(error)throw error;setStatus("Update notification sent to all signed-in users.");}catch(e:any){setStatus(e?.message??"Could not send the update notification.");}finally{setSending(false);}};
  const canSend=role==="super_admin";
  return <View style={s.root}><LinearGradient colors={["#1D122C","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View><Text style={s.kicker}>ADMIN</Text><Text style={s.title}>App updates</Text></View></View><ScrollView contentContainerStyle={s.content}><Text style={s.sub}>Send an in-app notification with a customizable download link. Users see it when they open Study Arc.</Text>{status?<View style={s.status}><Text style={s.statusText}>{status}</Text></View>:null}<Field label="VERSION" value={version} onChange={setVersion} placeholder="1.0.6"/><Field label="TITLE" value={title} onChange={setTitle} placeholder="New version available"/><Field label="MESSAGE" value={message} onChange={setMessage} placeholder="What changed?" multiline/><Field label="DOWNLOAD LINK" value={url} onChange={setUrl} placeholder="https://..." autoCapitalize="none"/><View style={s.note}><Ionicons name="information-circle-outline" size={19} color="#C7A8EE"/><Text style={s.noteText}>Use a direct APK link or your Study Arc website download page. The user chooses when to open it.</Text></View><Pressable disabled={!canSend||sending} onPress={send} style={[s.send,(!canSend||sending)&&{opacity:.5}]}><Ionicons name="send-outline" size={18} color="#160B20"/><Text style={s.sendText}>{sending?"SENDING…":canSend?"Send update notification":"Super Admin only"}</Text></Pressable></ScrollView></View>;
}
function Field({label,value,onChange,placeholder,multiline,autoCapitalize}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;multiline?:boolean;autoCapitalize?:"none"}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#5A6677" autoCapitalize={autoCapitalize} multiline={multiline} style={[s.input,multiline&&s.area]}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",gap:11,alignItems:"center",borderBottomWidth:1,borderBottomColor:"#2B2338"},back:{width:42,height:42,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},kicker:{color:"#A985D2",fontSize:8,fontWeight:"900",letterSpacing:1.3},title:{color:"#F5F6F8",fontSize:22,fontWeight:"900"},content:{width:"100%",maxWidth:650,alignSelf:"center",padding:20,paddingBottom:50},sub:{color:"#8290A2",fontSize:11,lineHeight:17},field:{marginTop:15},label:{color:"#929FB1",fontSize:9,fontWeight:"900",letterSpacing:1,marginBottom:7},input:{minHeight:47,borderRadius:13,backgroundColor:"#101720",borderWidth:1,borderColor:"#2B3949",color:"#EFF1F5",paddingHorizontal:12,fontSize:12},area:{minHeight:90,paddingTop:12,textAlignVertical:"top"},note:{marginTop:16,padding:13,borderRadius:15,backgroundColor:"#181525",flexDirection:"row",gap:9},noteText:{flex:1,color:"#A696B1",fontSize:10,lineHeight:15},send:{minHeight:52,borderRadius:16,backgroundColor:"#B784FF",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,marginTop:18},sendText:{color:"#160B20",fontSize:11,fontWeight:"900"},status:{marginTop:15,padding:11,borderRadius:13,backgroundColor:"#122019",borderWidth:1,borderColor:"#315843"},statusText:{color:"#A7DABB",fontSize:10.5,fontWeight:"800"}});
