import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React,{useMemo,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{useAcademic}from"../context/AcademicContext";
import{useStudent}from"../context/StudentContext";
import{SUBJECTS,expandSubjectChoices,topicDisplayName}from"../data/subjects";

export default function AssignmentScreen(){
 const router=useRouter();const{profile}=useStudent();const{assignments,addAssignment,setAssignmentCompleted}=useAcademic();
 const subjects=useMemo(()=>expandSubjectChoices(profile.subjectChoices),[profile.subjectChoices]);const[subject,setSubject]=useState(subjects[0]??"Physics"),[topic,setTopic]=useState(""),[title,setTitle]=useState(""),[dueDate,setDueDate]=useState(""),[minutes,setMinutes]=useState("60"),[message,setMessage]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const topics=(SUBJECTS as Record<string,any>)[subject]?.topics??[];
 const save=async()=>{if(!title.trim()){setMessage("Enter an assignment or homework title.");return}setSaving(true);try{await addAssignment({sourceClassId:null,title:title.trim(),subjectName:subject,topicName:topic||null,dueAt:/^\d{4}-\d{2}-\d{2}$/.test(dueDate)?new Date(`${dueDate}T18:00:00`).toISOString():null,estimatedMinutes:Math.max(5,Math.min(1440,Number(minutes)||60)),completed:false});setTitle("");setDueDate("");setTopic("");setMessage("Assignment added to planner priorities.")}catch(e){setMessage(e instanceof Error?e.message:"Could not save assignment.")}finally{setSaving(false)}};
 const open=assignments.filter(a=>!a.completed).sort((a,b)=>(a.dueAt??"9999").localeCompare(b.dueAt??"9999"));
 return <View style={s.root}><LinearGradient colors={["#171022","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.title}>Assignments</Text><Text style={s.sub}>Add homework and deadlines that should influence the planner.</Text></View></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">{message?<View style={s.message}><Text style={s.messageText}>{message}</Text></View>:null}<Text style={s.section}>QUICK ADD</Text><View style={s.card}><Text style={s.label}>TITLE</Text><TextInput value={title} onChangeText={setTitle} placeholder="e.g. Complete Tutorial 07" placeholderTextColor="#586678" style={s.input}/><Text style={s.label}>SUBJECT</Text><View style={s.wrap}>{subjects.map(x=><Pressable key={x} onPress={()=>{setSubject(x);setTopic("")}} style={[s.chip,subject===x&&s.chipOn]}><Text style={[s.chipText,subject===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</View><Text style={s.label}>RELATED TOPIC</Text><View style={s.wrap}>{topics.map((t:any)=><Pressable key={t.id} onPress={()=>setTopic(t.title)} style={[s.chip,topic===t.title&&s.chipOn]}><Text style={[s.chipText,topic===t.title&&s.chipTextOn]}>{topicDisplayName(subject,t.title,profile.medium)}</Text></Pressable>)}</View><View style={s.row}><View style={{flex:1}}><Text style={s.label}>DUE DATE</Text><TextInput value={dueDate} onChangeText={setDueDate} placeholder="YYYY-MM-DD" placeholderTextColor="#586678" style={s.input}/></View><View style={{width:120}}><Text style={s.label}>MINUTES</Text><TextInput value={minutes} onChangeText={setMinutes} keyboardType="number-pad" style={s.input}/></View></View><Pressable disabled={saving} onPress={save} style={s.primary}><Ionicons name="add" size={18} color="#160B20"/><Text style={s.primaryText}>{saving?"Saving…":"Add assignment"}</Text></Pressable></View><Text style={s.section}>OPEN DEADLINES</Text>{open.length?open.map(a=><View key={a.id} style={s.item}><Pressable onPress={()=>setAssignmentCompleted(a.id,true)} style={s.check}><Ionicons name="ellipse-outline" size={22} color="#8B98AA"/></Pressable><View style={{flex:1}}><Text style={s.itemTitle}>{a.title}</Text><Text style={s.itemSub}>{a.subjectName}{a.topicName?` · ${a.topicName}`:""} · {a.estimatedMinutes} min{a.dueAt?` · due ${new Date(a.dueAt).toLocaleString()}`:""}</Text></View></View>):<View style={s.empty}><Text style={s.emptyText}>No open assignments.</Text></View>}</ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:11},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F5F6F8",fontSize:22,fontWeight:"900"},sub:{color:"#748194",fontSize:10,marginTop:3},content:{padding:20,paddingBottom:50,maxWidth:760,width:"100%",alignSelf:"center"},message:{borderRadius:14,backgroundColor:"#122019",borderWidth:1,borderColor:"#315843",padding:11,marginBottom:10},messageText:{color:"#8BD4A7",fontSize:10.5,fontWeight:"700"},section:{color:"#8190A3",fontSize:9,fontWeight:"900",letterSpacing:1.3,marginTop:18,marginBottom:9},card:{borderRadius:19,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:14},label:{color:"#718094",fontSize:8,fontWeight:"900",letterSpacing:1,marginTop:10,marginBottom:6},input:{height:45,borderRadius:12,backgroundColor:"#0B1119",borderWidth:1,borderColor:"#293646",color:"#EDF0F4",paddingHorizontal:10,fontSize:10.5},wrap:{flexDirection:"row",flexWrap:"wrap",gap:6},chip:{minHeight:34,borderRadius:10,backgroundColor:"#17202B",borderWidth:1,borderColor:"#2C3948",paddingHorizontal:9,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:"#392653",borderColor:"#7755A2"},chipText:{color:"#8190A2",fontSize:8.5,fontWeight:"800"},chipTextOn:{color:"#F0E5FD"},row:{flexDirection:"row",gap:8},primary:{height:47,borderRadius:14,backgroundColor:"#B784FF",flexDirection:"row",gap:6,alignItems:"center",justifyContent:"center",marginTop:13},primaryText:{color:"#160B20",fontSize:10.5,fontWeight:"900"},item:{minHeight:67,borderRadius:16,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:11,flexDirection:"row",alignItems:"center",gap:9,marginBottom:7},check:{width:34,height:34,alignItems:"center",justifyContent:"center"},itemTitle:{color:"#E8EBEF",fontSize:11,fontWeight:"900"},itemSub:{color:"#748194",fontSize:8.5,lineHeight:13,marginTop:3},empty:{minHeight:70,borderRadius:16,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#273443",alignItems:"center",justifyContent:"center"},emptyText:{color:"#718092",fontSize:9.5}})
