import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React, { useMemo } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useStudent } from "../context/StudentContext";
import { useStudy } from "../context/StudyContext";
import { generateBonusWork } from "../lib/planner";

const UNLOCK_SECONDS=12*3600;
export default function BonusWorkScreen(){const router=useRouter();const{profile,topicProgress,testMarks}=useStudent();const{todaySeconds}=useStudy();const work=useMemo(()=>generateBonusWork(profile,topicProgress,testMarks,6),[profile,testMarks,topicProgress]);const unlocked=todaySeconds>=UNLOCK_SECONDS;return <View style={s.root}><LinearGradient colors={["#1B1023","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View><Text style={s.kicker}>EXTRA ARC</Text><Text style={s.title}>Generate new work</Text></View></View><ScrollView contentContainerStyle={s.content}>{!unlocked?<View style={s.lock}><Ionicons name="lock-closed-outline" size={38} color="#8B789E"/><Text style={s.lockTitle}>Unlocks after 12 hours today</Text><Text style={s.lockText}>This is intentionally a bonus-work feature. It appears only after 12 recorded study hours.</Text></View>:<><LinearGradient colors={["#4A2D65","#1A1A2B"]} style={s.hero}><Ionicons name="sparkles" size={26} color="#F0D7FF"/><Text style={s.heroTitle}>Daily plan complete. Bonus work unlocked.</Text><Text style={s.heroText}>These tasks come from overdue recall, weak test topics and your lowest-mastery syllabus areas.</Text></LinearGradient>{work.map((x,i)=><View key={x.id} style={s.card}><View style={s.num}><Text style={s.numText}>{i+1}</Text></View><View style={{flex:1}}><Text style={s.workTitle}>{x.title}</Text><Text style={s.workSub}>{x.subtitle}</Text></View><Pressable onPress={()=>router.push({pathname:"/stopwatch",params:{subjectName:x.subjectName,topicName:x.topicName,studyType:x.studyType}})} style={s.play}><Ionicons name="play" size={15} color="#130A1C"/></Pressable></View>)}</>}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},header:{padding:18,paddingTop:20,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#282033"},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},kicker:{color:"#9B7DC0",fontSize:8,fontWeight:"900",letterSpacing:1.3},title:{color:"#F5F6F8",fontSize:24,fontWeight:"900",marginTop:2},content:{padding:20,paddingBottom:45,maxWidth:720,width:"100%",alignSelf:"center"},lock:{marginTop:40,padding:35,borderRadius:23,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",alignItems:"center"},lockTitle:{color:"#EDF0F4",fontSize:18,fontWeight:"900",marginTop:12},lockText:{color:"#748194",fontSize:11,lineHeight:17,textAlign:"center",marginTop:7,maxWidth:420},hero:{borderRadius:23,borderWidth:1,borderColor:"#654985",padding:20,alignItems:"center",marginBottom:14},heroTitle:{color:"#F6F0FB",fontSize:17,fontWeight:"900",textAlign:"center",marginTop:10},heroText:{color:"#A494B3",fontSize:10.5,lineHeight:17,textAlign:"center",marginTop:6},card:{minHeight:74,borderRadius:18,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:11,flexDirection:"row",alignItems:"center",gap:10,marginBottom:8},num:{width:40,height:40,borderRadius:13,backgroundColor:"#B784FF16",alignItems:"center",justifyContent:"center"},numText:{color:"#C9A8F3",fontWeight:"900"},workTitle:{color:"#EDF0F4",fontSize:12.5,fontWeight:"900"},workSub:{color:"#718092",fontSize:9.5,marginTop:4},play:{width:38,height:38,borderRadius:13,backgroundColor:"#B784FF",alignItems:"center",justifyContent:"center"}});
