import {Ionicons} from "@expo/vector-icons";
import {LinearGradient} from "expo-linear-gradient";
import {useRouter} from "expo-router";
import React,{useMemo,useState} from "react";
import {Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import {useStudent} from "../context/StudentContext";
import {expandSubjectChoices} from "../data/subjects";
const pct=(a:number|null,b:number|null)=>a==null||b==null||b<=0?null:Math.round(a/b*100);
export default function ClassTestAnalysis(){const router=useRouter();const{profile,testMarks}=useStudent();const subjects=useMemo(()=>expandSubjectChoices(profile.subjectChoices),[profile.subjectChoices]);const[selected,setSelected]=useState("All subjects");const rows=useMemo(()=>testMarks.filter(x=>selected==="All subjects"||x.subjectName===selected).slice().sort((a,b)=>b.testDate.localeCompare(a.testDate)),[selected,testMarks]);return <View style={s.root}><LinearGradient colors={["#171020","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.title}>Class test analysis</Text><Text style={s.sub}>Class tests and test-paper marks stay separate from past-paper analysis.</Text></View><Pressable onPress={()=>router.push("/test-mark")} style={s.add}><Ionicons name="add" size={16} color="#160B20"/><Text style={s.addText}>Input marks</Text></Pressable></View><ScrollView contentContainerStyle={s.content}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{["All subjects",...subjects].map(x=><Pressable key={x} onPress={()=>setSelected(x)} style={[s.chip,selected===x&&s.chipOn]}><Text style={[s.chipText,selected===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</ScrollView><View style={s.summary}><Text style={s.summaryValue}>{rows.length}</Text><Text style={s.summaryText}>recorded class/test papers</Text></View>{rows.map(x=>{const mcq=pct(x.mcqScore,x.mcqTotal),essay=pct(x.essayScore,x.essayTotal);const vals=[mcq,essay].filter((v):v is number=>v!=null),overall=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):null;return <Pressable key={x.id} onPress={()=>router.push({pathname:"/test-mark",params:{editId:x.id}})} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{x.subjectName} · {x.title}</Text><Text style={s.rowSub}>{x.testDate} · MCQ/Part A {mcq==null?"—":mcq+"%"} · Essay/Part B {essay==null?"—":essay+"%"}</Text></View><Text style={s.score}>{overall==null?"—":overall+"%"}</Text><Ionicons name="chevron-forward" size={16} color="#657386"/></Pressable>})}{!rows.length?<View style={s.empty}><Text style={s.emptyText}>No class/test marks recorded yet.</Text></View>:null}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:9},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F5F6F8",fontSize:21,fontWeight:"900"},sub:{color:"#748194",fontSize:8.8,marginTop:3},add:{minHeight:40,borderRadius:12,backgroundColor:"#B784FF",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:4},addText:{color:"#160B20",fontSize:8.5,fontWeight:"900"},content:{padding:18,paddingBottom:55,maxWidth:860,width:"100%",alignSelf:"center",gap:9},chips:{gap:6,paddingRight:8},chip:{height:35,borderRadius:10,backgroundColor:"#121B24",borderWidth:1,borderColor:"#2D3B4A",paddingHorizontal:9,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:"#3B2852",borderColor:"#805AA9"},chipText:{color:"#8391A2",fontSize:8,fontWeight:"800"},chipTextOn:{color:"#F2E9FB"},summary:{minHeight:65,borderRadius:16,backgroundColor:"#171321",borderWidth:1,borderColor:"#49375C",padding:12,flexDirection:"row",alignItems:"baseline",gap:7},summaryValue:{color:"#E9D8F8",fontSize:22,fontWeight:"900"},summaryText:{color:"#8B7F94",fontSize:8.5},row:{minHeight:68,borderRadius:16,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:10,flexDirection:"row",alignItems:"center",gap:8},rowTitle:{color:"#E7EBEF",fontSize:10,fontWeight:"900"},rowSub:{color:"#718092",fontSize:8.2,marginTop:4},score:{color:"#C7A8EB",fontSize:16,fontWeight:"900"},empty:{minHeight:110,borderRadius:16,backgroundColor:"#0F161F",alignItems:"center",justifyContent:"center"},emptyText:{color:"#718092",fontSize:9}});
