import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useLocalSearchParams, useRouter } from "expo-router";
import React from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useStudent } from "../context/StudentContext";
import { subjectDisplayName } from "../lib/subjectDisplay";
import { format12Hour } from "../lib/time";

const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export default function ClassReminderScreen(){
 const router=useRouter();const p=useLocalSearchParams<{classId?:string|string[]}>();const classId=Array.isArray(p.classId)?p.classId[0]:p.classId;const{classes}=useStudent();const item=classes.find(x=>x.id===classId);
 return <View style={s.root}><LinearGradient colors={["#1B1129","#080D14","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><Text style={s.headTitle}>Class reminder</Text></View><View style={s.content}>{item?<><View style={s.icon}><Ionicons name="school-outline" size={30} color="#DCC7F6"/></View><Text style={s.subject}>{subjectDisplayName(item.subjectName)}</Text><Text style={s.type}>{item.classType} class</Text><View style={s.card}><Row icon="calendar-outline" label="Day" value={DAYS[item.dayOfWeek]}/><Row icon="time-outline" label="Time" value={`${format12Hour(item.startTime)} – ${format12Hour(item.endTime)}`}/><Row icon={item.deliveryMode==="Physical"?"location-outline":"videocam-outline"} label="Mode" value={item.deliveryMode}/><Row icon="refresh-outline" label="Pre-class review" value={`${item.preReviewMinutes} min`}/></View><Pressable onPress={()=>router.push("/classes")} style={s.primary}><Ionicons name="calendar-number-outline" size={18} color="#160B20"/><Text style={s.primaryText}>Open class schedule</Text></Pressable></>:<View style={s.missing}><Ionicons name="alert-circle-outline" size={32} color="#D79AA7"/><Text style={s.missingTitle}>Class not found</Text><Text style={s.missingText}>This class may have been edited or deleted. Open the class schedule to check your current classes.</Text><Pressable onPress={()=>router.replace("/classes")} style={s.primary}><Text style={s.primaryText}>Open classes</Text></Pressable></View>}</View></View>
}
function Row({icon,label,value}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string}){return <View style={s.row}><View style={s.rowIcon}><Ionicons name={icon} size={18} color="#AFA0C2"/></View><View style={{flex:1}}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{height:76,paddingHorizontal:18,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#2A2235"},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},headTitle:{color:"#F4F5F8",fontSize:20,fontWeight:"900"},content:{flex:1,padding:24,maxWidth:620,width:"100%",alignSelf:"center"},icon:{width:62,height:62,borderRadius:20,backgroundColor:"#241A31",alignItems:"center",justifyContent:"center",marginTop:18},subject:{color:"#F5F6F8",fontSize:28,fontWeight:"900",marginTop:17},type:{color:"#A990C8",fontSize:13,fontWeight:"800",marginTop:4},card:{borderRadius:20,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:14,marginTop:20},row:{minHeight:64,flexDirection:"row",alignItems:"center",gap:11,borderBottomWidth:1,borderBottomColor:"#222E3B"},rowIcon:{width:39,height:39,borderRadius:12,backgroundColor:"#181F2A",alignItems:"center",justifyContent:"center"},label:{color:"#718092",fontSize:8.5,fontWeight:"900",letterSpacing:.8},value:{color:"#E9EDF2",fontSize:12,fontWeight:"900",marginTop:4},primary:{height:52,borderRadius:15,backgroundColor:"#B784FF",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,marginTop:14},primaryText:{color:"#160B20",fontSize:11,fontWeight:"900"},missing:{alignItems:"center",paddingTop:80},missingTitle:{color:"#F1F3F6",fontSize:18,fontWeight:"900",marginTop:12},missingText:{color:"#748194",fontSize:10.5,lineHeight:17,textAlign:"center",marginTop:6,maxWidth:360}});
