import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React,{useState} from "react";
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {useAppConfig} from "../context/AppConfigContext";
import {useAuth} from "../context/AuthContext";
import {useStudent} from "../context/StudentContext";
import {supabase} from "../lib/supabase";

export default function ContactScreen(){
  const router=useRouter();const{settings}=useAppConfig();const{user}=useAuth();const{profile}=useStudent();
  const[subject,setSubject]=useState("Study Arc support"),[message,setMessage]=useState(""),[sending,setSending]=useState(false),[sent,setSent]=useState(false);
  const send=async()=>{if(!message.trim()){Alert.alert("Add a message","Tell us what you need help with.");return}if(!user){Alert.alert("Sign in required","Sign in to send a support request.");return}setSending(true);setSent(false);try{const{error}=await supabase.from("contact_messages").insert({user_id:user.id,email:user.email??null,subject:subject.trim()||"Study Arc support",message:`Profile name: ${profile.fullName||"Not provided"}\n\n${message.trim()}`});if(error)throw error;setSent(true);setMessage("")}catch(e){Alert.alert("Could not send message",e instanceof Error?e.message:"Please try again.")}finally{setSending(false)}};
  return <View style={s.root}><LinearGradient colors={["#161020","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View><Text style={s.kicker}>STUDY ARC SUPPORT</Text><Text style={s.title}>Contact us</Text></View></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.emailCard}><Ionicons name="mail" size={22} color="#C8A3F4"/><View style={{flex:1}}><Text style={s.emailLabel}>SUPPORT</Text><Text style={s.email}>{settings.contactEmail}</Text><Text style={s.emailHint}>Admins can update this address without releasing a new app version.</Text></View></View>{sent&&<View style={s.success}><Ionicons name="checkmark-circle" size={22} color="#65D79A"/><View style={{flex:1}}><Text style={s.successTitle}>Message sent</Text><Text style={s.successText}>Your support request was saved successfully.</Text></View></View>}<Text style={s.label}>SUBJECT</Text><TextInput value={subject} onChangeText={setSubject} placeholder="What is this about?" placeholderTextColor="#596677" style={s.input}/><Text style={s.label}>MESSAGE</Text><TextInput value={message} onChangeText={setMessage} placeholder="Tell us what happened or what you would like to improve…" placeholderTextColor="#596677" style={[s.input,s.message]} multiline textAlignVertical="top"/><Pressable disabled={sending} onPress={send} style={[s.send,sending&&{opacity:.6}]}><Ionicons name={sending?"hourglass-outline":"send"} size={18} color="#150B1D"/><Text style={s.sendText}>{sending?"Sending…":"Send to Study Arc"}</Text></Pressable><Text style={s.note}>Your account email is attached automatically so support can identify your request.</Text></ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},header:{padding:18,paddingTop:20,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#282033"},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},kicker:{color:"#9B7DC0",fontSize:8,fontWeight:"900",letterSpacing:1.3},title:{color:"#F5F6F8",fontSize:24,fontWeight:"900",marginTop:2},content:{padding:20,paddingBottom:45,maxWidth:680,width:"100%",alignSelf:"center"},emailCard:{minHeight:82,borderRadius:18,backgroundColor:"#171321",borderWidth:1,borderColor:"#4F3B63",padding:14,flexDirection:"row",alignItems:"center",gap:11},emailLabel:{color:"#7F708E",fontSize:8,fontWeight:"900",letterSpacing:1},email:{color:"#DEC9F8",fontSize:12,fontWeight:"900",marginTop:4},emailHint:{color:"#82728F",fontSize:9,marginTop:4},success:{marginTop:14,borderRadius:16,backgroundColor:"#102019",borderWidth:1,borderColor:"#315843",padding:13,flexDirection:"row",alignItems:"center",gap:9},successTitle:{color:"#DDF3E6",fontSize:12,fontWeight:"900"},successText:{color:"#779889",fontSize:9.5,lineHeight:15,marginTop:3},label:{color:"#7D8999",fontSize:9,fontWeight:"900",letterSpacing:1.2,marginTop:20,marginBottom:8},input:{minHeight:52,borderRadius:15,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",paddingHorizontal:14,color:"#EEF1F5",fontSize:13},message:{minHeight:150,paddingTop:13},send:{height:55,borderRadius:17,backgroundColor:"#B784FF",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,marginTop:18},sendText:{color:"#150B1D",fontSize:13,fontWeight:"900"},note:{color:"#687588",fontSize:9.5,lineHeight:15,textAlign:"center",marginTop:10}})
