import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React, { useState } from "react";
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSocial } from "../context/SocialContext";

export default function FriendsScreen(){
 const router=useRouter(); const{friendCode,friends,pendingRequests,sendFriendRequest,acceptFriendRequest,declineFriendRequest,removeFriend}=useSocial(); const[code,setCode]=useState(""); const[busy,setBusy]=useState(false);
 const add=async()=>{try{setBusy(true);const msg=await sendFriendRequest(code);setCode("");Alert.alert("Friends",msg);}catch(e){Alert.alert("Could not add friend",e instanceof Error?e.message:"Try again.");}finally{setBusy(false)}};
 return <View style={s.root}><LinearGradient colors={["#151020","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.kicker}>STUDY TOGETHER</Text><Text style={s.title}>Friends</Text></View><Ionicons name="people-outline" size={27} color="#C5A2F2"/></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 <LinearGradient colors={["#2B1D3C","#121A25"]} style={s.codeCard}><Text style={s.codeLabel}>YOUR FRIEND CODE</Text><Text style={s.code}>{friendCode}</Text><Text style={s.codeSub}>Share this code with another Study Arc student.</Text></LinearGradient>
 <Text style={s.section}>ADD A FRIEND</Text><View style={s.addRow}><TextInput value={code} onChangeText={setCode} autoCapitalize="characters" placeholder="ARC-XXXXXXXX" placeholderTextColor="#596677" style={s.input}/><Pressable disabled={busy} onPress={add} style={s.add}><Ionicons name="person-add-outline" size={18} color="#150B1D"/></Pressable></View>
 {pendingRequests.length>0&&<><Text style={s.section}>REQUESTS</Text>{pendingRequests.map(x=><View key={x.friendshipId} style={s.row}>{x.avatarUrl?<Image source={{uri:x.avatarUrl}} style={s.avatar}/>:<View style={s.avatar}><Ionicons name="person" size={18} color="#8B98A8"/></View>}<View style={{flex:1}}><Text style={s.name}>{x.displayName}</Text><Text style={s.meta}>{x.friendCode}</Text></View><Pressable onPress={()=>acceptFriendRequest(x.friendshipId)} style={s.accept}><Ionicons name="checkmark" size={18} color="#102017"/></Pressable><Pressable onPress={()=>declineFriendRequest(x.friendshipId)} style={s.decline}><Ionicons name="close" size={18} color="#C98E9A"/></Pressable></View>)}</>}
 <View style={s.sectionRow}><Text style={s.section}>FRIENDS</Text><Text style={s.live}>{friends.filter(x=>x.isStudying).length} STUDYING NOW</Text></View>
 {friends.length===0?<View style={s.empty}><Ionicons name="people-outline" size={34} color="#5D6A7B"/><Text style={s.emptyTitle}>No friends yet</Text><Text style={s.emptyText}>Add someone with their Study Arc friend code to see when they are actively studying.</Text></View>:friends.map(x=><Pressable key={x.userId} onLongPress={()=>Alert.alert("Remove friend?",x.displayName,[{text:"Cancel",style:"cancel"},{text:"Remove",style:"destructive",onPress:()=>removeFriend(x.userId)}])} style={[s.row,x.isStudying&&s.rowLive]}>{x.avatarUrl?<Image source={{uri:x.avatarUrl}} style={s.avatar}/>:<View style={s.avatar}><Ionicons name="person" size={18} color="#8B98A8"/></View>}<View style={{flex:1,minWidth:0}}><View style={s.nameRow}><Text style={s.name}>{x.displayName}</Text>{x.isStudying&&<View style={s.liveDot}/>}</View><Text style={[s.meta,x.isStudying&&s.metaLive]} numberOfLines={1}>{x.isStudying?`Studying now${x.subjectName?` · ${x.subjectName}`:""}${x.topicName?` · ${x.topicName}`:""}`:"Not studying right now"}</Text></View>{x.isStudying&&<Ionicons name="radio-outline" size={19} color="#65D79A"/>}</Pressable>)}
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},header:{padding:18,paddingTop:20,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#282033"},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},kicker:{color:"#9B7DC0",fontSize:8,fontWeight:"900",letterSpacing:1.3},title:{color:"#F5F6F8",fontSize:24,fontWeight:"900",marginTop:2},content:{padding:20,paddingBottom:45,maxWidth:720,width:"100%",alignSelf:"center"},codeCard:{borderRadius:22,borderWidth:1,borderColor:"#4E3A62",padding:18},codeLabel:{color:"#8E7AA6",fontSize:8,fontWeight:"900",letterSpacing:1.2},code:{color:"#E9D7FF",fontSize:24,fontWeight:"900",letterSpacing:1.4,marginTop:7},codeSub:{color:"#7B8797",fontSize:10,marginTop:6},section:{color:"#7D8999",fontSize:9,fontWeight:"900",letterSpacing:1.25,marginTop:23,marginBottom:9},sectionRow:{flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between"},live:{color:"#65D79A",fontSize:8,fontWeight:"900",marginBottom:9},addRow:{flexDirection:"row",gap:8},input:{flex:1,height:50,borderRadius:15,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",paddingHorizontal:14,color:"#EEF1F5",fontSize:13,fontWeight:"800"},add:{width:50,height:50,borderRadius:15,backgroundColor:"#B784FF",alignItems:"center",justifyContent:"center"},row:{minHeight:68,borderRadius:17,backgroundColor:"#101720",borderWidth:1,borderColor:"#263241",padding:10,flexDirection:"row",alignItems:"center",gap:10,marginBottom:8},rowLive:{borderColor:"#315746",backgroundColor:"#0F1C1A"},avatar:{width:43,height:43,borderRadius:14,backgroundColor:"#18212C",alignItems:"center",justifyContent:"center"},nameRow:{flexDirection:"row",alignItems:"center",gap:6},name:{color:"#EDF0F4",fontSize:12.5,fontWeight:"900"},meta:{color:"#6F7C8D",fontSize:9.5,marginTop:4},metaLive:{color:"#78B993"},liveDot:{width:7,height:7,borderRadius:4,backgroundColor:"#65D79A"},accept:{width:36,height:36,borderRadius:12,backgroundColor:"#65D79A",alignItems:"center",justifyContent:"center"},decline:{width:36,height:36,borderRadius:12,backgroundColor:"#25161C",alignItems:"center",justifyContent:"center"},empty:{padding:32,borderRadius:20,backgroundColor:"#101720",borderWidth:1,borderColor:"#263241",alignItems:"center"},emptyTitle:{color:"#E9EDF2",fontSize:16,fontWeight:"900",marginTop:10},emptyText:{color:"#718092",fontSize:10.5,lineHeight:16,textAlign:"center",marginTop:5}});
