import{Ionicons}from"@expo/vector-icons";
import{Stack,useRouter}from"expo-router";
import React,{useEffect,useState}from"react";
import{Pressable,StyleSheet,Switch,Text,View}from"react-native";
import{useAuth}from"../context/AuthContext";
import{supabase}from"../lib/supabase";
import StudyArcDialog from"../components/StudyArcDialog";
export default function LeaderboardSettingsScreen(){const router=useRouter(),{user}=useAuth();const[visible,setVisible]=useState(true),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);useEffect(()=>{if(!user)return;supabase.from("social_profiles").select("show_on_leaderboard").eq("user_id",user.id).maybeSingle().then(({data})=>{setVisible(data?.show_on_leaderboard!==false);setLoading(false)})},[user]);const change=async(value:boolean)=>{if(!user||saving)return;setVisible(value);setSaving(true);const{error:e}=await supabase.from("social_profiles").update({show_on_leaderboard:value,updated_at:new Date().toISOString()}).eq("user_id",user.id);setSaving(false);if(e){setVisible(!value);setError(e.message)}};return <><Stack.Screen options={{presentation:"transparentModal",animation:"fade",contentStyle:{backgroundColor:"transparent"}}}/><View style={s.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>router.back()}/><View style={s.modal}><View style={s.head}><View style={s.icon}><Ionicons name="trophy-outline" size={25} color="#E6C56E"/></View><View style={{flex:1}}><Text style={s.kicker}>PRIVACY</Text><Text style={s.title}>Leaderboard visibility</Text><Text style={s.sub}>Choose whether your study time appears in rankings.</Text></View><Pressable onPress={()=>router.back()} style={s.close}><Ionicons name="close" size={20} color="#FFF"/></Pressable></View><View style={s.card}><View style={{flex:1}}><Text style={s.cardTitle}>Appear on daily leaderboard</Text><Text style={s.cardText}>When off, your ranking rows are hidden. Your sessions, analytics and friends still work normally.</Text></View><Switch disabled={loading||saving} value={visible} onValueChange={change}/></View><View style={s.note}><Ionicons name="shield-checkmark-outline" size={20} color="#87CDA4"/><Text style={s.noteText}>{loading?"Loading your preference…":visible?"You appear in the leaderboard when you record study time.":"You are hidden from the leaderboard. Turn this back on anytime."}</Text></View></View></View><StudyArcDialog visible={Boolean(error)} title="Could not update setting" message={error??""} tone="danger" onClose={()=>setError(null)}/></>}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(3,6,10,.78)",alignItems:"center",justifyContent:"center",padding:18},modal:{width:"100%",maxWidth:550,borderRadius:26,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#41334F",padding:16},head:{flexDirection:"row",alignItems:"center",gap:11},icon:{width:50,height:50,borderRadius:16,backgroundColor:"#F0C96C14",alignItems:"center",justifyContent:"center"},kicker:{color:"#B8995C",fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:"#F3F5F7",fontSize:20,fontWeight:"900",marginTop:2},sub:{color:"#7B8797",fontSize:11,marginTop:3},close:{width:40,height:40,borderRadius:13,backgroundColor:"#18212B",alignItems:"center",justifyContent:"center"},card:{borderRadius:18,backgroundColor:"#141D27",borderWidth:1,borderColor:"#2B3848",padding:14,flexDirection:"row",alignItems:"center",gap:12,marginTop:15},cardTitle:{color:"#EBEEF2",fontSize:14,fontWeight:"900"},cardText:{color:"#7D8999",fontSize:11,lineHeight:17,marginTop:4},note:{marginTop:10,borderRadius:16,backgroundColor:"#102019",borderWidth:1,borderColor:"#315843",padding:12,flexDirection:"row",alignItems:"flex-start",gap:9},noteText:{flex:1,color:"#8DBB9D",fontSize:11,lineHeight:17}});
