import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect } from "@react-navigation/native";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React,{useCallback}from"react";
import{Image,Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{useSocial}from"../context/SocialContext";

const fmt=(sec:number)=>{const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);return h?`${h}h ${m}m`:`${m}m`};
export default function LeaderboardScreen(){
 const router=useRouter();const{leaderboard,myRank,refreshSocial}=useSocial();
 useFocusEffect(useCallback(()=>{refreshSocial().catch(()=>undefined)},[refreshSocial]));
 return <View style={s.root}><LinearGradient colors={["#181021","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.kicker}>DAILY STUDY TIME</Text><Text style={s.title}>Leaderboard</Text></View><Pressable onPress={()=>refreshSocial().catch(()=>undefined)} style={s.refresh}><Ionicons name="refresh-outline" size={19} color="#C6A5EC"/></Pressable></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><LinearGradient colors={["#392352","#171929"]} style={s.hero}><Text style={s.heroLabel}>YOUR RANK TODAY</Text><Text style={s.heroRank}>{myRank?`#${myRank.rank}`:"—"}</Text><Text style={s.heroTime}>{myRank?fmt(myRank.studySeconds):"No study time yet"}</Text><Text style={s.heroSub}>Optional social comparison. Rankings do not affect your planner or readiness score.</Text></LinearGradient><Text style={s.section}>TODAY</Text>{leaderboard.length===0?<Text style={s.empty}>No ranking data yet. Complete a study session to enter today’s board.</Text>:leaderboard.map(entry=><View key={entry.userId} style={[s.row,entry.isMe&&s.rowMe]}><View style={s.rank}><Text style={[s.rankText,entry.rank<=3&&s.topRank]}>#{entry.rank}</Text></View>{entry.avatarUrl?<Image source={{uri:entry.avatarUrl}} style={s.avatar}/>:<View style={s.avatar}><Ionicons name="person" size={18} color="#8D99A8"/></View>}<View style={{flex:1}}><Text style={s.name}>{entry.displayName}{entry.isMe?" · You":""}</Text><Text style={s.meta}>Studied today</Text></View><Text style={s.time}>{fmt(entry.studySeconds)}</Text></View>)}</ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},header:{padding:18,paddingTop:20,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#282033"},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},refresh:{width:43,height:43,borderRadius:14,backgroundColor:"#21182D",alignItems:"center",justifyContent:"center"},kicker:{color:"#9B7DC0",fontSize:8,fontWeight:"900",letterSpacing:1.3},title:{color:"#F5F6F8",fontSize:24,fontWeight:"900",marginTop:2},content:{padding:20,paddingBottom:45,maxWidth:720,width:"100%",alignSelf:"center"},hero:{borderRadius:25,borderWidth:1,borderColor:"#5C4375",padding:22,alignItems:"center"},heroLabel:{color:"#AD95C7",fontSize:9,fontWeight:"900",letterSpacing:1.3},heroRank:{color:"#FFF",fontSize:48,fontWeight:"900",marginTop:8},heroTime:{color:"#D9C0F6",fontSize:16,fontWeight:"900"},heroSub:{color:"#8C8198",fontSize:10,textAlign:"center",marginTop:8},section:{color:"#7D8999",fontSize:9,fontWeight:"900",letterSpacing:1.3,marginTop:24,marginBottom:10},row:{minHeight:70,borderRadius:17,backgroundColor:"#101720",borderWidth:1,borderColor:"#263241",padding:11,flexDirection:"row",alignItems:"center",gap:10,marginBottom:8},rowMe:{backgroundColor:"#171321",borderColor:"#5A4273"},rank:{width:36,alignItems:"center"},rankText:{color:"#7D8999",fontSize:12,fontWeight:"900"},topRank:{color:"#F0CB73"},avatar:{width:43,height:43,borderRadius:14,backgroundColor:"#18212C",alignItems:"center",justifyContent:"center"},name:{color:"#EDF0F4",fontSize:12.5,fontWeight:"900"},meta:{color:"#6F7C8D",fontSize:9,marginTop:3},time:{color:"#C9A6F1",fontSize:12,fontWeight:"900"},empty:{color:"#718092",fontSize:11,lineHeight:18,padding:20,textAlign:"center"}})
