import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React,{useEffect,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{supabase}from"../lib/supabase";

type Prefs={next_session:boolean;class_reminders:boolean;revision_reminders:boolean;paper_reminders:boolean;missed_plan_reminders:boolean};
const defaults:Prefs={next_session:true,class_reminders:true,revision_reminders:true,paper_reminders:true,missed_plan_reminders:true};
export default function NotificationSettingsScreen(){
 const router=useRouter();const[prefs,setPrefs]=useState<Prefs>(defaults),[loading,setLoading]=useState(true),[message,setMessage]=useState<string|null>(null);
 useEffect(()=>{supabase.rpc("get_my_notification_preferences").then(({data,error})=>{if(!error&&data)setPrefs({...defaults,...data});setLoading(false)})},[]);
 const toggle=async(key:keyof Prefs)=>{const next={...prefs,[key]:!prefs[key]};setPrefs(next);setMessage(null);const{data,error}=await supabase.rpc("set_my_notification_preferences",{prefs:next});if(error){setPrefs(prefs);setMessage(error.message)}else if(data)setPrefs({...defaults,...data})};
 return <View style={s.root}><LinearGradient colors={["#171022","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.title}>Notification controls</Text><Text style={s.sub}>Choose which study reminders Study Arc may send.</Text></View></View><ScrollView contentContainerStyle={s.content}>{message?<View style={s.message}><Text style={s.messageText}>{message}</Text></View>:null}{loading?<Text style={s.loading}>Loading preferences…</Text>:<><Toggle label="Next study session" sub="Reminder before your next planned study block." value={prefs.next_session} onPress={()=>toggle("next_session")}/><Toggle label="Class reminders" sub="Reminder for upcoming classes and class-related preparation." value={prefs.class_reminders} onPress={()=>toggle("class_reminders")}/><Toggle label="Revision reminders" sub="Recall and class-to-revision reminders." value={prefs.revision_reminders} onPress={()=>toggle("revision_reminders")}/><Toggle label="Paper reminders" sub="Past-paper, paper-review and paper-class reminders." value={prefs.paper_reminders} onPress={()=>toggle("paper_reminders")}/><Toggle label="Missed-plan reminders" sub="Remind you when a planned task was missed and can be recovered." value={prefs.missed_plan_reminders} onPress={()=>toggle("missed_plan_reminders")}/></>}<View style={s.note}><Ionicons name="information-circle-outline" size={19} color="#BFA0E5"/><Text style={s.noteText}>Device notification permission is still controlled by your phone or browser. Turning a category off here stops Study Arc from scheduling that category.</Text></View></ScrollView></View>
}
function Toggle({label,sub,value,onPress}:{label:string;sub:string;value:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{label}</Text><Text style={s.rowSub}>{sub}</Text></View><View style={[s.switch,value&&s.switchOn]}><View style={[s.knob,value&&s.knobOn]}/></View></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:11},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F5F6F8",fontSize:22,fontWeight:"900"},sub:{color:"#748194",fontSize:10,marginTop:3},content:{padding:20,paddingBottom:50,maxWidth:700,width:"100%",alignSelf:"center"},message:{borderRadius:14,backgroundColor:"#27171D",borderWidth:1,borderColor:"#62333D",padding:11,marginBottom:10},messageText:{color:"#F0A8B3",fontSize:10},loading:{color:"#778496",textAlign:"center",marginTop:30},row:{minHeight:78,borderRadius:18,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:13,flexDirection:"row",alignItems:"center",gap:12,marginBottom:8},rowTitle:{color:"#E9EDF1",fontSize:11.5,fontWeight:"900"},rowSub:{color:"#748194",fontSize:9,lineHeight:14,marginTop:4},switch:{width:47,height:27,borderRadius:14,backgroundColor:"#283342",padding:3},switchOn:{backgroundColor:"#704AA1"},knob:{width:21,height:21,borderRadius:11,backgroundColor:"#9AA5B3"},knobOn:{marginLeft:20,backgroundColor:"#FFF"},note:{marginTop:8,borderRadius:16,backgroundColor:"#171522",borderWidth:1,borderColor:"#40344F",padding:12,flexDirection:"row",gap:9},noteText:{flex:1,color:"#8D8099",fontSize:9.5,lineHeight:15}})
