import{Ionicons}from"@expo/vector-icons";
import{Stack,useRouter}from"expo-router";
import React,{useEffect,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{supabase}from"../lib/supabase";
type Prefs={next_session:boolean;class_reminders:boolean;revision_reminders:boolean;paper_reminders:boolean;missed_plan_reminders:boolean};
const defaults:Prefs={next_session:true,class_reminders:true,revision_reminders:true,paper_reminders:true,missed_plan_reminders:true};
export default function NotificationSettingsScreen(){const router=useRouter();const[prefs,setPrefs]=useState<Prefs>(defaults),[loading,setLoading]=useState(true),[message,setMessage]=useState<string|null>(null);useEffect(()=>{supabase.rpc("get_my_notification_preferences").then(({data,error})=>{if(!error&&data)setPrefs({...defaults,...data});setLoading(false)})},[]);const toggle=async(key:keyof Prefs)=>{const next={...prefs,[key]:!prefs[key]};setPrefs(next);setMessage(null);const{data,error}=await supabase.rpc("set_my_notification_preferences",{prefs:next});if(error){setPrefs(prefs);setMessage(error.message)}else if(data)setPrefs({...defaults,...data})};return <><Stack.Screen options={{presentation:"transparentModal",animation:"fade",contentStyle:{backgroundColor:"transparent"}}}/><View style={s.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>router.back()}/><View style={s.modal}><View style={s.head}><View style={s.icon}><Ionicons name="notifications-outline" size={24} color="#D5B9F4"/></View><View style={{flex:1}}><Text style={s.kicker}>REMINDERS</Text><Text style={s.title}>Notification controls</Text><Text style={s.sub}>Choose which StudyArc reminders may be scheduled.</Text></View><Pressable onPress={()=>router.back()} style={s.close}><Ionicons name="close" size={20} color="#FFF"/></Pressable></View><ScrollView style={s.scroll} contentContainerStyle={s.content}>{message?<View style={s.message}><Text style={s.messageText}>{message}</Text></View>:null}{loading?<Text style={s.loading}>Loading preferences…</Text>:<><Toggle label="Next study session" sub="Reminder before your next planned study block." value={prefs.next_session} onPress={()=>toggle("next_session")}/><Toggle label="Class reminders" sub="Upcoming classes and class preparation." value={prefs.class_reminders} onPress={()=>toggle("class_reminders")}/><Toggle label="Revise reminders" sub="Recall and class-to-Revise reminders." value={prefs.revision_reminders} onPress={()=>toggle("revision_reminders")}/><Toggle label="Paper reminders" sub="Past paper, Paper Review and paper-class reminders." value={prefs.paper_reminders} onPress={()=>toggle("paper_reminders")}/><Toggle label="Missed-plan reminders" sub="Recover work that was missed without silently stacking it." value={prefs.missed_plan_reminders} onPress={()=>toggle("missed_plan_reminders")}/></>}<View style={s.note}><Ionicons name="information-circle-outline" size={19} color="#BFA0E5"/><Text style={s.noteText}>Your phone or browser still controls notification permission. Turning a category off here stops StudyArc from scheduling that category.</Text></View></ScrollView></View></View></>}
function Toggle({label,sub,value,onPress}:{label:string;sub:string;value:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{label}</Text><Text style={s.rowSub}>{sub}</Text></View><View style={[s.switch,value&&s.switchOn]}><View style={[s.knob,value&&s.knobOn]}/></View></Pressable>}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(3,6,10,.8)",alignItems:"center",justifyContent:"center",padding:16},modal:{width:"100%",maxWidth:600,maxHeight:"88%",borderRadius:26,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#41334F",overflow:"hidden"},head:{padding:16,flexDirection:"row",alignItems:"center",gap:11,borderBottomWidth:1,borderBottomColor:"#27313E"},icon:{width:48,height:48,borderRadius:15,backgroundColor:"#21182D",alignItems:"center",justifyContent:"center"},kicker:{color:"#A789C7",fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:"#F3F5F7",fontSize:20,fontWeight:"900",marginTop:2},sub:{color:"#7B8797",fontSize:11,marginTop:3},close:{width:40,height:40,borderRadius:13,backgroundColor:"#18212B",alignItems:"center",justifyContent:"center"},scroll:{maxHeight:600},content:{padding:14,paddingBottom:18},message:{borderRadius:14,backgroundColor:"#27171D",borderWidth:1,borderColor:"#62333D",padding:11,marginBottom:10},messageText:{color:"#F0A8B3",fontSize:11},loading:{color:"#778496",textAlign:"center",marginTop:30,fontSize:11},row:{minHeight:79,borderRadius:18,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:13,flexDirection:"row",alignItems:"center",gap:12,marginBottom:8},rowTitle:{color:"#E9EDF1",fontSize:13,fontWeight:"900"},rowSub:{color:"#748194",fontSize:10.5,lineHeight:16,marginTop:4},switch:{width:49,height:29,borderRadius:15,backgroundColor:"#283342",padding:3},switchOn:{backgroundColor:"#704AA1"},knob:{width:23,height:23,borderRadius:12,backgroundColor:"#9AA5B3"},knobOn:{marginLeft:20,backgroundColor:"#FFF"},note:{marginTop:8,borderRadius:16,backgroundColor:"#171522",borderWidth:1,borderColor:"#40344F",padding:12,flexDirection:"row",gap:9},noteText:{flex:1,color:"#9386A0",fontSize:10.5,lineHeight:16}});
