import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React,{useMemo}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{useStudent,type TestMark}from"../context/StudentContext";

const pct=(m:TestMark)=>{const a=m.mcqPercent,b=m.essayPercent;if(a!=null&&b!=null)return(a+b)/2;return a??b};
export default function PaperDetailsScreen(){
 const router=useRouter();const{testMarks}=useStudent();
 const marks=useMemo(()=>[...testMarks].sort((a,b)=>b.testDate.localeCompare(a.testDate)),[testMarks]);
 return <View style={s.root}><LinearGradient colors={["#171023","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.title}>Paper details</Text><Text style={s.sub}>Review and edit the paper information and marks you entered.</Text></View><Pressable onPress={()=>router.push("/test-mark")} style={s.add}><Ionicons name="add" size={19} color="#160B20"/></Pressable></View><ScrollView contentContainerStyle={s.content}>
 {marks.length===0?<View style={s.empty}><Ionicons name="document-text-outline" size={34} color="#776589"/><Text style={s.emptyTitle}>No paper results yet</Text><Text style={s.emptyText}>Your saved paper names, subjects, dates and marks will appear here.</Text></View>:marks.map(m=><View key={m.id} style={s.card}><View style={s.top}><View style={{flex:1}}><Text style={s.paper}>{m.title}</Text><Text style={s.meta}>{m.subjectName} · {new Date(m.testDate+"T12:00:00").toLocaleDateString()}</Text></View>{pct(m)!=null?<Text style={s.percent}>{pct(m)!.toFixed(1)}%</Text>:null}</View><View style={s.marks}>{m.mcqScore!=null?<View style={s.mark}><Text style={s.markLabel}>PART A / MCQ</Text><Text style={s.markValue}>{m.mcqScore} / {m.mcqTotal}</Text></View>:null}{m.essayScore!=null?<View style={s.mark}><Text style={s.markLabel}>PART B / LONG</Text><Text style={s.markValue}>{m.essayScore} / {m.essayTotal}</Text></View>:null}</View><Pressable onPress={()=>router.push({pathname:"/test-mark",params:{editId:m.id}} as never)} style={s.edit}><Ionicons name="create-outline" size={16} color="#D3B6F3"/><Text style={s.editText}>Edit paper details & marks</Text><Ionicons name="chevron-forward" size={16} color="#705E83"/></Pressable></View>)}
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{minHeight:82,padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:11},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151C27",alignItems:"center",justifyContent:"center"},title:{color:"#F5F3F8",fontSize:21,fontWeight:"900"},sub:{color:"#758194",fontSize:9,marginTop:3},add:{width:42,height:42,borderRadius:14,backgroundColor:"#B784FF",alignItems:"center",justifyContent:"center"},content:{padding:18,paddingBottom:45,maxWidth:760,width:"100%",alignSelf:"center",gap:10},card:{borderRadius:19,backgroundColor:"#111923",borderWidth:1,borderColor:"#2B3848",padding:13},top:{flexDirection:"row",alignItems:"center",gap:10},paper:{color:"#F0EDF4",fontSize:13,fontWeight:"900"},meta:{color:"#788596",fontSize:8.5,marginTop:4},percent:{color:"#D3B6F3",fontSize:18,fontWeight:"900"},marks:{flexDirection:"row",gap:8,marginTop:12},mark:{flex:1,borderRadius:12,backgroundColor:"#0B121A",padding:9},markLabel:{color:"#647285",fontSize:6.5,fontWeight:"900"},markValue:{color:"#DCE2E9",fontSize:11,fontWeight:"900",marginTop:4},edit:{height:42,borderRadius:13,backgroundColor:"#1A1422",borderWidth:1,borderColor:"#3C2F49",paddingHorizontal:11,flexDirection:"row",alignItems:"center",gap:7,marginTop:10},editText:{flex:1,color:"#D3B6F3",fontSize:9,fontWeight:"900"},empty:{alignItems:"center",padding:40,borderRadius:20,backgroundColor:"#101720",borderWidth:1,borderColor:"#293543"},emptyTitle:{color:"#E6E0EB",fontSize:14,fontWeight:"900",marginTop:10},emptyText:{color:"#748194",fontSize:9,textAlign:"center",marginTop:5}});
