import {Ionicons} from "@expo/vector-icons";
import {useLocalSearchParams,useRouter} from "expo-router";
import React,{useEffect,useMemo,useRef,useState} from "react";
import {Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from "react-native";
import {loadPreferredPastPaperRange} from "../components/PastPaperYearRange";
import PastPaperQuestionGrid,{questionKey} from "../components/PastPaperQuestionGrid";
import {usePastPaperEntry} from "../hooks/usePastPaperEntry";
import {defaultPastPaperRange,trackerQuestions,yearsForRange,type PastPaperRange} from "../lib/pastPaperTracker";
import {subjectAccent} from "../lib/pastPaperUi";
const first=(v?:string|string[])=>Array.isArray(v)?v[0]:v;
export default function PastPaperRecord(){
 const p=useLocalSearchParams<{subjectName?:string|string[];paperYear?:string|string[];paperSection?:string|string[]}>();const router=useRouter();
 const subject=first(p.subjectName)||"Physics",section=first(p.paperSection)||"Full Paper",accent=subjectAccent(subject);
 const entry=usePastPaperEntry(subject);const initial=Number(first(p.paperYear));
 const [range,setRange]=useState<PastPaperRange>(defaultPastPaperRange());const [year,setYear]=useState(Number.isInteger(initial)&&initial>=1950&&initial<=new Date().getFullYear()?initial:new Date().getFullYear());
 const [picker,setPicker]=useState(false);const [selected,setSelected]=useState<Set<string>>(new Set());const [complete,setComplete]=useState(false);
 const savedSelections=useRef(new Map<string,string>());const [savedCount,setSavedCount]=useState(0);
 useEffect(()=>{let live=true;loadPreferredPastPaperRange(subject).then(r=>{if(live){setRange(r);if(!initial)setYear(r.to)}});return()=>{live=false}},[subject,initial]);
 const questions=useMemo(()=>trackerQuestions(subject,year,section),[subject,year,section]);
 const years=useMemo(()=>{const list=yearsForRange(range).filter(y=>trackerQuestions(subject,y,section).length>0);return questions.length&&!list.includes(year)?[year,...list]:list},[range,subject,section,year,questions.length]);
 const availableQuestions=questions.filter(q=>![...savedSelections.current.values()].includes(questionKey(q)));
 const toggle=(key:string)=>setSelected(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next});
 const save=async()=>{const ok=await entry.save(year,availableQuestions.filter(q=>selected.has(questionKey(q))),(q,id)=>{const key=questionKey(q);savedSelections.current.set(id,key);setSavedCount(savedSelections.current.size);setSelected(current=>{const next=new Set(current);next.delete(key);return next})});if(ok)setComplete(true)};
 const undo=async()=>{await entry.undo(id=>{const key=savedSelections.current.get(id);savedSelections.current.delete(id);if(key)setSelected(current=>new Set([...current,key]));setSavedCount(savedSelections.current.size);setComplete(false)})};
 return <SafeAreaView style={s.root}>
  <View style={s.head}><Pressable disabled={entry.busy} accessibilityLabel="Back" onPress={()=>router.back()} style={s.icon}><Ionicons name="arrow-back" size={22} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={[s.subject,{color:accent}]}>{subject} · {section}</Text><Text style={s.title}>Record completed questions</Text></View></View>
  <ScrollView contentContainerStyle={s.content}>
   <Text style={s.help}>Choose the paper year and tick the questions you completed.</Text>
   <Pressable disabled={entry.busy||savedCount>0} onPress={()=>setPicker(true)} style={[s.yearPicker,{borderColor:accent+"70"}]}><Ionicons name="calendar-outline" size={22} color={accent}/><Text style={s.year}>{year}</Text><Text style={s.help}>Paper year</Text><Ionicons name="chevron-down" size={18} color={accent}/></Pressable>
   {complete?<View style={[s.saved,{borderColor:accent+"70"}]}><Ionicons name="checkmark-circle" size={48} color={accent}/><Text style={s.title}>{savedCount} questions saved</Text><Text style={s.help}>Your completion meter has been updated.</Text></View>:<>
    <View style={s.actions}><Text style={[s.help,{flex:1}]}>{selected.size} selected</Text><Pressable disabled={entry.busy||entry.loading} onPress={()=>setSelected(new Set(availableQuestions.map(questionKey)))} style={s.action}><Text style={[s.link,{color:accent}]}>Select all</Text></Pressable><Pressable disabled={entry.busy} onPress={()=>setSelected(new Set())} style={s.action}><Text style={s.link}>Clear</Text></Pressable></View>
    <View style={s.card}><PastPaperQuestionGrid questions={availableQuestions} accent={accent} selected={q=>selected.has(questionKey(q))} disabled={entry.busy||entry.loading} onPress={q=>toggle(questionKey(q))} groupActions={group=>setSelected(current=>new Set([...current,...group.map(questionKey)]))}/>{!availableQuestions.length&&<Text style={s.help}>This section is unavailable for this year. Choose another year.</Text>}</View>
   </>}
   {savedCount>0&&!complete&&<Text accessibilityLiveRegion="polite" style={s.help}>{savedCount} already saved. Retry saves only the remaining selected questions.</Text>}
  </ScrollView>
  <View style={s.dock}>{entry.error&&<Text accessibilityRole="alert" style={s.error}>{entry.error}</Text>}<View style={s.feedback}><Text style={[s.help,{flex:1}]}>{entry.busy?"Saving…":complete?`${year} · saved`:selected.size+" questions selected"}</Text>{entry.canUndo&&<Pressable disabled={entry.busy} onPress={undo} style={s.action}><Ionicons name="arrow-undo" size={18} color={accent}/><Text style={[s.link,{color:accent}]}>Undo</Text></Pressable>}</View><Pressable accessibilityRole="button" disabled={entry.busy||entry.loading||(!complete&&selected.size===0)} onPress={complete?()=>router.replace("/past-paper"):save} style={[s.save,{backgroundColor:accent},(entry.busy||entry.loading||(!complete&&!selected.size))&&{opacity:.5}]}><Text style={s.saveText}>{entry.busy?"Saving…":complete?"Done":`Save ${selected.size} question${selected.size===1?"":"s"}`}</Text></Pressable></View>
  <Modal visible={picker} transparent animationType="fade" onRequestClose={()=>setPicker(false)}><Pressable style={s.overlay} onPress={()=>setPicker(false)}><Pressable style={s.sheet} onPress={e=>e.stopPropagation()}><View style={s.actions}><Text style={[s.title,{flex:1}]}>Paper year</Text><Pressable accessibilityLabel="Close year picker" onPress={()=>setPicker(false)} style={s.icon}><Ionicons name="close" size={22} color="#FFF"/></Pressable></View><ScrollView contentContainerStyle={s.years}>{years.map(y=><Pressable key={y} onPress={()=>{setYear(y);setSelected(new Set());setPicker(false)}} style={[s.chip,year===y&&{borderColor:accent}]}><Text style={s.link}>{y}</Text></Pressable>)}</ScrollView></Pressable></Pressable></Modal>
 </SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#090E17"},head:{padding:14,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#29374A"},icon:{width:42,height:42,borderRadius:13,backgroundColor:"#182331",alignItems:"center",justifyContent:"center"},subject:{fontSize:12,fontWeight:"700"},title:{color:"#F4F7FB",fontSize:21,fontWeight:"800",marginTop:3},content:{padding:16,gap:16,maxWidth:950,width:"100%",alignSelf:"center"},help:{color:"#A2B2C6",fontSize:13,lineHeight:19},yearPicker:{minHeight:62,padding:14,borderWidth:1,borderRadius:15,flexDirection:"row",alignItems:"center",gap:12},year:{fontSize:24,fontWeight:"800",color:"#FFF",flex:1},actions:{flexDirection:"row",alignItems:"center",gap:8},action:{minHeight:44,paddingHorizontal:10,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},link:{color:"#C7D4E5",fontSize:13,fontWeight:"700"},card:{backgroundColor:"#101A26",borderRadius:20,padding:16,borderWidth:1,borderColor:"#2C3B50"},saved:{alignItems:"center",padding:30,gap:12,borderWidth:1,borderRadius:22,backgroundColor:"#121E2B"},dock:{paddingHorizontal:16,paddingBottom:12,backgroundColor:"#101925",borderTopWidth:1,borderTopColor:"#29374A"},feedback:{minHeight:44,flexDirection:"row",alignItems:"center"},save:{minHeight:53,borderRadius:15,alignItems:"center",justifyContent:"center"},saveText:{color:"#0A1320",fontSize:16,fontWeight:"800"},error:{color:"#FFAAB7",fontSize:12,paddingTop:8},overlay:{flex:1,backgroundColor:"#000000BB",justifyContent:"center",padding:16},sheet:{width:"100%",maxWidth:530,maxHeight:"80%",alignSelf:"center",backgroundColor:"#101A26",borderRadius:22,padding:18,gap:16},years:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{minWidth:68,minHeight:44,borderWidth:1,borderColor:"#34465A",borderRadius:12,alignItems:"center",justifyContent:"center"}});
