import {Ionicons} from "@expo/vector-icons";
import {LinearGradient} from "expo-linear-gradient";
import {useRouter} from "expo-router";
import React,{useMemo,useState} from "react";
import {Alert,Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import {usePastPaperTracker} from "../context/PastPaperTrackerContext";
import {trackerSubjects} from "../lib/pastPaperTracker";

export default function PastPaperHistory(){
 const router=useRouter();const{ticks,removeAttempt,loading}=usePastPaperTracker();const[subject,setSubject]=useState("All");const[removing,setRemoving]=useState<string|null>(null);
 const rows=useMemo(()=>ticks.filter(t=>subject==="All"||t.subjectName===subject).slice().sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()),[subject,ticks]);
 const remove=(id:string)=>Alert.alert("Remove this attempt?","Only this saved attempt will be removed. Other attempts for the same question stay in history.",[{text:"Cancel",style:"cancel"},{text:"Remove",style:"destructive",onPress:async()=>{setRemoving(id);try{await removeAttempt(id)}finally{setRemoving(null)}}}]);
 return <View style={s.root}><LinearGradient colors={["#211431","#090D14","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.kicker}>PAST PAPER HISTORY</Text><Text style={s.title}>Ticked attempts</Text><Text style={s.sub}>Every tap is saved as an attempt. Remove individual attempts here.</Text></View></View><ScrollView contentContainerStyle={s.content}>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{["All",...trackerSubjects].map(x=><Pressable key={x} onPress={()=>setSubject(x)} style={[s.chip,subject===x&&s.chipOn]}><Text style={[s.chipText,subject===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</ScrollView>
   <View style={s.summary}><View style={s.summaryIcon}><Ionicons name="time-outline" size={24} color="#D9C3F3"/></View><View><Text style={s.summaryValue}>{rows.length}</Text><Text style={s.summaryLabel}>{subject==="All"?"saved attempts":subject+" attempts"}</Text></View></View>
   {loading&&!rows.length?<Text style={s.empty}>Loading history…</Text>:null}
   {!loading&&!rows.length?<View style={s.emptyCard}><Ionicons name="checkmark-done-outline" size={28} color="#657486"/><Text style={s.emptyTitle}>No attempts yet</Text><Text style={s.empty}>Tick a past-paper question and it will appear here.</Text></View>:null}
   {rows.map(t=><View key={t.id} style={s.row}><View style={s.attempt}><Text style={s.attemptNo}>#{t.attemptNo}</Text></View><View style={{flex:1,minWidth:0}}><Text style={s.rowTitle}>{t.subjectName} · {t.paperYear}</Text><Text style={s.rowMeta}>{t.paperSection+" · "+(t.itemKey==="paper"?"Paper":"Question "+t.itemKey)+" · Attempt "+t.attemptNo+(t.topicName?" · "+t.topicName:"")}</Text><Text style={s.rowDate}>{new Date(t.createdAt).toLocaleString()}</Text></View><Pressable disabled={removing===t.id} onPress={()=>remove(t.id)} style={s.remove}><Ionicons name="trash-outline" size={17} color="#FF9B9B"/></Pressable></View>)}
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#2B2037"},back:{width:43,height:43,borderRadius:14,backgroundColor:"#121821",alignItems:"center",justifyContent:"center"},kicker:{color:"#AA84D4",fontSize:7.5,fontWeight:"900",letterSpacing:1.3},title:{color:"#F7F4FA",fontSize:21,fontWeight:"900",marginTop:2},sub:{color:"#7C899A",fontSize:8.5,marginTop:3},content:{padding:18,paddingBottom:60,maxWidth:900,width:"100%",alignSelf:"center",gap:9},chips:{gap:6,paddingBottom:3},chip:{height:37,borderRadius:11,backgroundColor:"#121B24",borderWidth:1,borderColor:"#2D3B4A",paddingHorizontal:11,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:"#3B2852",borderColor:"#845EB0"},chipText:{color:"#8593A4",fontSize:8.5,fontWeight:"900"},chipTextOn:{color:"#F2E9FB"},summary:{minHeight:72,borderRadius:17,backgroundColor:"#15131D",borderWidth:1,borderColor:"#49375C",padding:12,flexDirection:"row",alignItems:"center",gap:10},summaryIcon:{width:44,height:44,borderRadius:13,backgroundColor:"#281D35",alignItems:"center",justifyContent:"center"},summaryValue:{color:"#F1ECF6",fontSize:18,fontWeight:"900"},summaryLabel:{color:"#8A8193",fontSize:8.5,marginTop:2},row:{minHeight:74,borderRadius:16,backgroundColor:"#0F171F",borderWidth:1,borderColor:"#293746",padding:10,flexDirection:"row",alignItems:"center",gap:10},attempt:{width:43,height:43,borderRadius:13,backgroundColor:"#223B2B",alignItems:"center",justifyContent:"center"},attemptNo:{color:"#9BE1B2",fontSize:10,fontWeight:"900"},rowTitle:{color:"#E9EDF2",fontSize:11,fontWeight:"900"},rowMeta:{color:"#8A98A8",fontSize:8.5,marginTop:3},rowDate:{color:"#5F6D7D",fontSize:7.5,marginTop:3},remove:{width:39,height:39,borderRadius:12,backgroundColor:"#2A171A",alignItems:"center",justifyContent:"center"},emptyCard:{minHeight:170,borderRadius:18,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#293746",alignItems:"center",justifyContent:"center",padding:20},emptyTitle:{color:"#D9E0E7",fontSize:12,fontWeight:"900",marginTop:8},empty:{color:"#758395",fontSize:8.5,marginTop:4,textAlign:"center"}});
