import {Ionicons} from "@expo/vector-icons";
import {LinearGradient} from "expo-linear-gradient";
import {useRouter} from "expo-router";
import React,{useMemo,useState} from "react";
import {Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import {usePastPaperTracker} from "../context/PastPaperTrackerContext";
import {trackerSubjects} from "../lib/pastPaperTracker";
export default function PastPaperQuestionReport(){const router=useRouter();const{ticks}=usePastPaperTracker();const[subject,setSubject]=useState("All");const[year,setYear]=useState<number|null>(null);const[topic,setTopic]=useState("All");const[section,setSection]=useState("All");const years=useMemo(()=>[...new Set(ticks.map(x=>x.paperYear))].sort((a,b)=>b-a),[ticks]);const topics=useMemo(()=>[...new Set(ticks.map(x=>x.topicName).filter(Boolean) as string[])].sort(),[ticks]);const sections=useMemo(()=>[...new Set(ticks.map(x=>x.paperSection))].sort(),[ticks]);const rows=useMemo(()=>ticks.filter(x=>(subject==="All"||x.subjectName===subject)&&(!year||x.paperYear===year)&&(topic==="All"||(topic==="Unmapped"?!x.topicName:x.topicName===topic))&&(section==="All"||x.paperSection===section)),[section,subject,ticks,topic,year]);return <View style={s.root}><LinearGradient colors={["#171020","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.title}>Past paper question report</Text><Text style={s.sub}>Filter completed questions by subject, year, section and lesson.</Text></View></View><ScrollView contentContainerStyle={s.content}>
<Filter title="SUBJECT" values={["All",...trackerSubjects]} value={subject} set={setSubject}/><Filter title="YEAR" values={["All",...years.map(String)]} value={year?String(year):"All"} set={v=>setYear(v==="All"?null:Number(v))}/><Filter title="SECTION" values={["All",...sections]} value={section} set={setSection}/><Filter title="LESSON" values={["All","Unmapped",...topics]} value={topic} set={setTopic}/>
<View style={s.summary}><Text style={s.summaryValue}>{rows.length}</Text><Text style={s.summaryText}>saved attempts match these filters</Text></View>
{rows.map(x=><View key={x.id} style={s.row}><View style={s.q}><Text style={s.qText}>{x.itemKey}</Text></View><View style={{flex:1}}><Text style={s.rowTitle}>{x.subjectName} · {x.paperYear} · {x.paperSection}</Text><Text style={s.rowSub}>{x.topicName||"Lesson not mapped yet"} · Attempt {x.attemptNo}</Text></View><Text style={s.date}>{new Date(x.createdAt).toLocaleDateString()}</Text></View>)}
{!rows.length?<View style={s.empty}><Text style={s.emptyText}>No recorded questions match these filters.</Text></View>:null}</ScrollView></View>}
function Filter({title,values,value,set}:{title:string;values:readonly string[];value:string;set:(v:string)=>void}){return <View><Text style={s.label}>{title}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{values.map(v=><Pressable key={v} onPress={()=>set(v)} style={[s.chip,value===v&&s.chipOn]}><Text style={[s.chipText,value===v&&s.chipTextOn]}>{v}</Text></Pressable>)}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:11},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F5F6F8",fontSize:21,fontWeight:"900"},sub:{color:"#748194",fontSize:9,marginTop:3},content:{padding:18,paddingBottom:55,maxWidth:900,width:"100%",alignSelf:"center",gap:10},label:{color:"#758395",fontSize:7.5,fontWeight:"900",letterSpacing:1,marginTop:5,marginBottom:6},chips:{gap:6,paddingRight:8},chip:{minHeight:34,borderRadius:10,backgroundColor:"#121B24",borderWidth:1,borderColor:"#2C3948",paddingHorizontal:9,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:"#3A2852",borderColor:"#7B58A4"},chipText:{color:"#8290A1",fontSize:8,fontWeight:"800"},chipTextOn:{color:"#F2E9FC"},summary:{minHeight:62,borderRadius:16,backgroundColor:"#171321",borderWidth:1,borderColor:"#49375C",padding:11,flexDirection:"row",alignItems:"baseline",gap:7,marginTop:4},summaryValue:{color:"#E8D9F7",fontSize:22,fontWeight:"900"},summaryText:{color:"#8A7E94",fontSize:8.5},row:{minHeight:66,borderRadius:15,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:9,flexDirection:"row",alignItems:"center",gap:9},q:{width:39,height:39,borderRadius:12,backgroundColor:"#223B2B",alignItems:"center",justifyContent:"center"},qText:{color:"#9EE0B3",fontSize:10,fontWeight:"900"},rowTitle:{color:"#E4E8ED",fontSize:9.5,fontWeight:"900"},rowSub:{color:"#718092",fontSize:8,marginTop:3},date:{color:"#657386",fontSize:7.5},empty:{minHeight:100,borderRadius:16,backgroundColor:"#0F161F",alignItems:"center",justifyContent:"center"},emptyText:{color:"#718092",fontSize:9}});
