import {Ionicons} from "@expo/vector-icons";
import {LinearGradient} from "expo-linear-gradient";
import {useRouter} from "expo-router";
import React,{useEffect,useMemo,useState} from "react";
import {Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import PastPaperYearRange,{loadPreferredPastPaperRange} from "../components/PastPaperYearRange";
import {usePastPaperTracker} from "../context/PastPaperTrackerContext";
import {defaultPastPaperRange,mcqCountForYear,trackerSectionsForSubject,trackerSubjects,type PastPaperRange,yearsForRange} from "../lib/pastPaperTracker";

export default function PastPaperTracker(){
 const router=useRouter();const{ticks,loading}=usePastPaperTracker();const[range,setRange]=useState<PastPaperRange>(defaultPastPaperRange());
 useEffect(()=>{loadPreferredPastPaperRange().then(setRange)},[]);
 const years=useMemo(()=>yearsForRange(range),[range]);
 const inRange=ticks.filter(t=>t.paperYear>=range.from&&t.paperYear<=range.to);
 const open=(subjectName:string,section:string)=>router.push({pathname:"/past-paper-section-tracker",params:{subjectName,section}});
 const sectionStats=(subject:string,section:string)=>{
   if(section==="MCQ"){const done=inRange.filter(t=>t.subjectName===subject&&t.paperSection==="MCQ").length;const total=years.reduce((n,y)=>n+mcqCountForYear(y),0);return{done,total,label:`${done.toLocaleString()} / ${total.toLocaleString()} MCQs`}}
   if(section==="Structured + Essay"){const done=inRange.filter(t=>t.subjectName===subject&&(t.paperSection==="Structured"||t.paperSection==="Essay")).length;const total=years.length*2;return{done,total,label:`${done} / ${total} sections`}}
   const done=inRange.filter(t=>t.subjectName===subject&&t.paperSection===section).length;const total=years.length;return{done,total,label:`${done} / ${total} papers`}
 };
 const allStats=trackerSubjects.flatMap(subject=>trackerSectionsForSubject(subject).map(section=>sectionStats(subject,section)));const allDone=allStats.reduce((n,x)=>n+x.done,0);const allTotal=allStats.reduce((n,x)=>n+x.total,0);
 return <View style={s.root}><LinearGradient colors={["#211431","#090D14","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.kicker}>PAST PAPER HISTORY</Text><Text style={s.title}>Everything you've done</Text><Text style={s.sub}>One overview for Physics, Chemistry, Pure Mathematics and Applied Mathematics.</Text></View></View><ScrollView contentContainerStyle={s.content}>
   <View style={s.hero}><View style={s.heroIcon}><Ionicons name="grid-outline" size={27} color="#E3D0F8"/></View><View style={{flex:1}}><Text style={s.heroTitle}>{loading?"Loading progress…":`${allDone.toLocaleString()} completed items`}</Text><Text style={s.heroSub}>{range.from}–{range.to} · MCQs are tracked individually; other paper sections are tracked by year until their detailed question lists are added.</Text></View><View style={s.heroPct}><Text style={s.heroPctText}>{allTotal?Math.round(allDone/allTotal*100):0}%</Text></View></View>
   <PastPaperYearRange value={range} onChange={setRange}/>
   {trackerSubjects.map(subject=><View key={subject} style={s.subjectCard}><View style={s.subjectHead}><View style={s.subjectIcon}><Ionicons name={subject.includes("Mathematics")?"calculator-outline":"flask-outline"} size={20} color="#D9C2F2"/></View><View style={{flex:1}}><Text style={s.subjectTitle}>{subject}</Text><Text style={s.subjectSub}>{subject==="Physics"||subject==="Chemistry"?"MCQ + Structured/Essay tracking":"Part A + Part B tracking"}</Text></View></View><View style={s.sectionGrid}>{trackerSectionsForSubject(subject).map(section=>{const st=sectionStats(subject,section);const pct=st.total?Math.round(st.done/st.total*100):0;return <Pressable key={section} onPress={()=>open(subject,section)} style={s.section}><View style={s.sectionTop}><Text style={s.sectionTitle}>{section}</Text><Ionicons name="arrow-forward-circle-outline" size={20} color="#B994DE"/></View><Text style={s.sectionCount}>{st.label}</Text><View style={s.bar}><View style={[s.fill,{width:`${pct}%` as any}]}/></View><Text style={s.pct}>{pct}% complete</Text></Pressable>})}</View></View>)}
   <View style={s.note}><Ionicons name="information-circle-outline" size={19} color="#8EA0B5"/><Text style={s.noteText}>Year range can be anywhere from 1950 to the current year. When you send the exact Structured/Essay and Mathematics question lists, this tracker is already designed to store those individual question ticks too.</Text></View>
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#2B2037"},back:{width:43,height:43,borderRadius:14,backgroundColor:"#121821",alignItems:"center",justifyContent:"center"},kicker:{color:"#AA84D4",fontSize:7.5,fontWeight:"900",letterSpacing:1.3},title:{color:"#F7F4FA",fontSize:22,fontWeight:"900",marginTop:2},sub:{color:"#7C899A",fontSize:8.8,marginTop:3},content:{padding:18,paddingBottom:55,maxWidth:980,width:"100%",alignSelf:"center",gap:12},hero:{borderRadius:21,backgroundColor:"#15131D",borderWidth:1,borderColor:"#4B3860",padding:15,flexDirection:"row",alignItems:"center",gap:12},heroIcon:{width:52,height:52,borderRadius:16,backgroundColor:"#B784FF18",alignItems:"center",justifyContent:"center"},heroTitle:{color:"#F0EBF5",fontSize:14,fontWeight:"900"},heroSub:{color:"#8B8294",fontSize:8.8,lineHeight:14,marginTop:4},heroPct:{minWidth:60,height:45,borderRadius:14,backgroundColor:"#251B31",alignItems:"center",justifyContent:"center"},heroPctText:{color:"#DCC6F5",fontSize:14,fontWeight:"900"},subjectCard:{borderRadius:20,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#293746",padding:13},subjectHead:{flexDirection:"row",alignItems:"center",gap:10,marginBottom:10},subjectIcon:{width:42,height:42,borderRadius:13,backgroundColor:"#251B31",alignItems:"center",justifyContent:"center"},subjectTitle:{color:"#EDF0F4",fontSize:13,fontWeight:"900"},subjectSub:{color:"#748294",fontSize:8.5,marginTop:3},sectionGrid:{flexDirection:"row",gap:8,flexWrap:"wrap"},section:{flex:1,minWidth:220,borderRadius:15,backgroundColor:"#121B24",borderWidth:1,borderColor:"#2D3B4A",padding:12},sectionTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},sectionTitle:{color:"#E8EDF2",fontSize:11,fontWeight:"900"},sectionCount:{color:"#8795A6",fontSize:8.5,marginTop:6},bar:{height:5,borderRadius:3,backgroundColor:"#242F3B",overflow:"hidden",marginTop:10},fill:{height:"100%",backgroundColor:"#B784FF",borderRadius:3},pct:{color:"#6F7E90",fontSize:7.5,fontWeight:"800",marginTop:5},note:{borderRadius:15,backgroundColor:"#101821",borderWidth:1,borderColor:"#293746",padding:12,flexDirection:"row",alignItems:"flex-start",gap:8},noteText:{flex:1,color:"#8190A2",fontSize:8.8,lineHeight:14}});
