import {Ionicons} from "@expo/vector-icons";
import {useLocalSearchParams,useRouter} from "expo-router";
import React,{useEffect,useMemo,useState} from "react";
import {Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from "react-native";
import PastPaperYearRange,{loadPreferredPastPaperRange} from "../components/PastPaperYearRange";
import PastPaperQuestionGrid from "../components/PastPaperQuestionGrid";
import {usePastPaperTracker} from "../context/PastPaperTrackerContext";
import {usePastPaperEntry} from "../hooks/usePastPaperEntry";
import {defaultPastPaperRange,trackerQuestions,yearsForRange,type PastPaperRange,type TrackerQuestion} from "../lib/pastPaperTracker";
import {subjectAccent,timerSection} from "../lib/pastPaperUi";
const first=(v?:string|string[])=>Array.isArray(v)?v[0]:v;
export default function PastPaperSectionTracker(){
 const router=useRouter();const p=useLocalSearchParams<{subjectName?:string|string[];section?:string|string[]}>();const subject=first(p.subjectName)||"Physics",section=first(p.section)||"MCQ",accent=subjectAccent(subject);
 const {isDone,attemptCount}=usePastPaperTracker();const entry=usePastPaperEntry(subject);
 const [range,setRange]=useState<PastPaperRange>(defaultPastPaperRange());const [year,setYear]=useState<number|null>(null);const [picker,setPicker]=useState(false);const [repeat,setRepeat]=useState<{year:number;q:TrackerQuestion}|null>(null);const [message,setMessage]=useState("");
 useEffect(()=>{let live=true;loadPreferredPastPaperRange(subject).then(r=>{if(live)setRange(r)});return()=>{live=false}},[subject]);
 const years=useMemo(()=>yearsForRange(range).filter(y=>trackerQuestions(subject,y,section).length>0),[range,subject,section]);
 const visible=year!==null&&years.includes(year)?[year]:years;
 const add=async(y:number,qs:TrackerQuestion[])=>{if(await entry.save(y,qs))setMessage(`${y} · ${qs.length===1?"Q"+qs[0].number:qs.length+" questions"} saved`)};
 const tick=(y:number,q:TrackerQuestion)=>{if(isDone(subject,y,q.kind,q.itemKey))setRepeat({year:y,q});else void add(y,[q])};
 return <SafeAreaView style={s.root}>
  <View style={s.head}><Pressable disabled={entry.busy} accessibilityLabel="Back" onPress={()=>router.back()} style={s.icon}><Ionicons name="arrow-back" size={22} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={[s.subject,{color:accent}]}>{subject}</Text><Text style={s.title}>{section}</Text></View><Pressable accessibilityLabel="Attempt history" onPress={()=>router.push("/past-paper-history")} style={s.icon}><Ionicons name="time-outline" size={21} color={accent}/></Pressable></View>
  <ScrollView contentContainerStyle={s.content}>
   <Pressable accessibilityRole="button" onPress={()=>setPicker(true)} style={[s.yearPicker,{borderColor:accent+"70"}]}><Ionicons name="calendar-outline" size={21} color={accent}/><Text style={s.yearLabel}>{year??`${range.from}–${range.to}`}</Text><Text style={s.help}>{year?"Change year":"All years"}</Text><Ionicons name="chevron-down" size={18} color={accent}/></Pressable>
   <Text style={s.help}>Tap a question to record it. Tap a ticked question for another attempt.</Text>
   {!years.length&&<Text style={s.help}>No questions in this section for the selected year range. Change the range above.</Text>}
   {visible.map(y=>{const qs=trackerQuestions(subject,y,section),done=qs.filter(q=>isDone(subject,y,q.kind,q.itemKey)).length;return <View key={y} style={s.card}><View style={s.cardHead}><Text style={s.year}>{y}</Text><Text style={[s.count,{color:accent}]}>{done}/{qs.length} attempted</Text></View><PastPaperQuestionGrid questions={qs} accent={accent} selected={q=>isDone(subject,y,q.kind,q.itemKey)} attempts={q=>attemptCount(subject,y,q.kind,q.itemKey)} disabled={entry.busy||entry.loading} onPress={q=>tick(y,q)} groupActions={group=>{const remaining=group.filter(q=>!isDone(subject,y,q.kind,q.itemKey));void add(y,remaining)}}/></View>})}
   {subject.includes("Mathematics")&&section!=="Legacy paper"&&range.from<2000&&<Pressable onPress={()=>router.push({pathname:"/past-paper-section-tracker",params:{subjectName:subject,section:"Legacy paper"}})} style={s.yearPicker}><Text style={s.yearLabel}>Older-format papers</Text><Ionicons name="chevron-forward" size={20} color={accent}/></Pressable>}
  </ScrollView>
  <View style={s.dock}>{entry.error&&<Text accessibilityRole="alert" style={s.error}>{entry.error}</Text>}<View style={s.feedback}><Text accessibilityLiveRegion="polite" style={[s.help,{flex:1}]}>{entry.busy?"Saving…":message}</Text>{entry.canUndo&&<Pressable disabled={entry.busy} accessibilityRole="button" onPress={async()=>{if(await entry.undo())setMessage("Undone")}} style={s.undo}><Ionicons name="arrow-undo" size={18} color={accent}/><Text style={[s.count,{color:accent}]}>Undo</Text></Pressable>}</View><Pressable disabled={entry.busy} accessibilityRole="button" onPress={()=>router.push({pathname:"/paper-stopwatch",params:{subjectName:subject,topicName:"General",studyType:"Past Papers",paperSection:timerSection(section),paperYear:year?String(year):undefined,recordQuestions:"1"}})} style={[s.start,{backgroundColor:accent}]}><Ionicons name="play" size={20} color="#0A1320"/><Text style={s.startText}>Start timer</Text></Pressable></View>
  <Modal visible={picker} transparent animationType="fade" onRequestClose={()=>setPicker(false)}><Pressable style={s.overlay} onPress={()=>setPicker(false)}><Pressable style={s.sheet} onPress={e=>e.stopPropagation()}><View style={s.cardHead}><Text style={s.title}>Choose year</Text><Pressable accessibilityLabel="Close year picker" onPress={()=>setPicker(false)} style={s.icon}><Ionicons name="close" size={22} color="#FFF"/></Pressable></View><PastPaperYearRange value={range} subjectName={subject} onChange={r=>{setRange(r);setYear(null)}}/><Pressable onPress={()=>{setYear(null);setPicker(false)}} style={s.yearPicker}><Text style={s.yearLabel}>All years</Text></Pressable><ScrollView contentContainerStyle={s.yearGrid}>{years.map(y=><Pressable key={y} onPress={()=>{setYear(y);setPicker(false)}} style={[s.yearChip,year===y&&{borderColor:accent}]}><Text style={s.count}>{y}</Text></Pressable>)}</ScrollView></Pressable></Pressable></Modal>
  <Modal visible={repeat!==null} transparent animationType="fade" onRequestClose={()=>setRepeat(null)}><Pressable style={s.overlay} onPress={()=>setRepeat(null)}><Pressable style={s.sheet} onPress={e=>e.stopPropagation()}><Text style={s.title}>{repeat?.year} · Q{repeat?.q.number}</Text><Text style={s.help}>Already recorded. Save another attempt?</Text><Pressable disabled={entry.busy} onPress={()=>{if(repeat){void add(repeat.year,[repeat.q]);setRepeat(null)}}} style={[s.start,{backgroundColor:accent}]}><Text style={s.startText}>Add another attempt</Text></Pressable><Pressable onPress={()=>{setRepeat(null);router.push("/past-paper-history")}} style={s.yearPicker}><Text style={s.yearLabel}>View / edit attempts</Text></Pressable><Pressable onPress={()=>setRepeat(null)} style={s.undo}><Text style={s.help}>Cancel</Text></Pressable></Pressable></Pressable></Modal>
 </SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#090E17"},head:{padding:14,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#29374A"},icon:{width:42,height:42,borderRadius:13,backgroundColor:"#182331",alignItems:"center",justifyContent:"center"},subject:{fontSize:12,fontWeight:"700"},title:{color:"#F4F7FB",fontSize:23,fontWeight:"800"},content:{padding:16,gap:14,maxWidth:1000,width:"100%",alignSelf:"center"},yearPicker:{minHeight:52,padding:12,borderWidth:1,borderColor:"#34465A",borderRadius:14,flexDirection:"row",alignItems:"center",gap:10},yearLabel:{color:"#E8EEF6",fontWeight:"700",fontSize:15,flex:1},help:{color:"#A2B2C6",fontSize:12,lineHeight:18},card:{padding:16,borderRadius:19,borderWidth:1,borderColor:"#2C3B50",backgroundColor:"#101A26"},cardHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:10,marginBottom:12},year:{fontSize:22,color:"#F4F7FB",fontWeight:"800"},count:{fontSize:13,fontWeight:"700",color:"#D3DFEC"},dock:{backgroundColor:"#101925",borderTopWidth:1,borderTopColor:"#29374A",paddingHorizontal:16,paddingBottom:12},feedback:{minHeight:43,flexDirection:"row",alignItems:"center",gap:10},undo:{minHeight:42,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6,paddingHorizontal:12},start:{minHeight:52,borderRadius:15,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:8},startText:{fontWeight:"800",fontSize:16,color:"#0A1320"},error:{color:"#FFAAB7",fontSize:12,paddingTop:8},overlay:{flex:1,backgroundColor:"#000000BB",justifyContent:"center",padding:16},sheet:{width:"100%",maxWidth:540,maxHeight:"85%",alignSelf:"center",backgroundColor:"#101A26",borderRadius:22,padding:18,gap:12,borderWidth:1,borderColor:"#384C65"},yearGrid:{flexDirection:"row",flexWrap:"wrap",gap:8},yearChip:{minWidth:64,minHeight:44,paddingHorizontal:12,borderRadius:12,borderWidth:1,borderColor:"#34465A",alignItems:"center",justifyContent:"center"}});
