import {useThemeRefresh} from "../context/AppThemeContext";
import {createThemeStyles} from "../lib/themeStyles";
import {Ionicons} from "@expo/vector-icons";
import {useFocusEffect,useRouter} from "expo-router";
import React,{useCallback,useMemo,useState} from "react";
import {Modal,Pressable,SafeAreaView,StyleSheet,Text,useWindowDimensions,View} from "react-native";
import {loadPreferredPastPaperRange} from "../components/PastPaperYearRange";
import {usePastPaperTracker} from "../context/PastPaperTrackerContext";
import {defaultPastPaperRange,type PastPaperRange} from "../lib/pastPaperTracker";
import {paperSubjects,subjectAccent,subjectProgress,subjectSections} from "../lib/pastPaperUi";

export default function PastPaperScreen(){
 useThemeRefresh();
 const router=useRouter();const {isDone,loading}=usePastPaperTracker();const {height,width}=useWindowDimensions();const compact=height<650;const narrow=width<500;const landscape=height<480&&width>600;
 const [subject,setSubject]=useState<string|null>(null);const [tools,setTools]=useState(false);
 const [ranges,setRanges]=useState<Record<string,PastPaperRange>>({});
 useFocusEffect(useCallback(()=>{let live=true;void Promise.all(paperSubjects.map(async s=>[s,await loadPreferredPastPaperRange(s)] as const)).then(rows=>{if(live)setRanges(Object.fromEntries(rows))});return()=>{live=false}},[]));
 const progress=useMemo(()=>Object.fromEntries(paperSubjects.map(s=>[s,subjectProgress(s,ranges[s]??defaultPastPaperRange(),isDone)])),[ranges,isDone]);
 const accent=subjectAccent(subject??"Pure Mathematics");
 const select=(section:string)=>{if(!subject)return;setSubject(null);router.push(section==="Full Paper"?{pathname:"/paper-stopwatch",params:{subjectName:subject,topicName:"General",studyType:"Past Papers",paperSection:section,recordQuestions:"1"}}:{pathname:"/past-paper-section-tracker",params:{subjectName:subject,section}})};
 const tool=(path:"/past-paper-history"|"/past-paper-settings"|"/paper-analysis"|"/past-paper-question-report")=>{setTools(false);router.push(path)};
 return <SafeAreaView style={s.root}>
  <View style={[s.head,compact&&{paddingVertical:8}]}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>router.back()} style={s.icon}><Ionicons name="arrow-back" size={22} color="#F4F6FA"/></Pressable><View style={{flex:1}}><Text style={s.title}>Past papers</Text><Text style={s.muted}>Choose a subject to begin</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Past paper tools" onPress={()=>setTools(true)} style={s.icon}><Ionicons name="options-outline" size={22} color="#CCD4E1"/></Pressable></View>
  <View style={[s.content,{padding:compact?10:16}]}>
   {(landscape?[paperSubjects]:[paperSubjects.slice(0,2),paperSubjects.slice(2)]).map((row,i)=><View key={i} style={s.row}>{row.map(name=>{const color=subjectAccent(name),p=progress[name],r=ranges[name]??defaultPastPaperRange();return <Pressable key={name} accessibilityRole="button" accessibilityLabel={`${name}, ${p.percent}% attempted. Choose section`} onPress={()=>setSubject(name)} style={[s.card,{backgroundColor:color+"12",borderColor:color+"65",padding:compact?12:narrow?14:24}]}>
    <View style={s.cardTop}><View style={[s.subjectIcon,{backgroundColor:color+"22",width:compact?32:42,height:compact?32:42}]}><Ionicons name={name.includes("Mathematics")?"calculator-outline":name==="Physics"?"flash-outline":"flask-outline"} size={compact?19:24} color={color}/></View><Ionicons name="arrow-forward" size={19} color={color}/></View>
    <Text style={[s.subjectName,{fontSize:compact?15:narrow?17:25,marginTop:compact?8:14}]}>{name}</Text>
    <View style={{flex:1,minHeight:4}}/>
    <Text style={[s.percent,{color,fontSize:compact?26:narrow?32:42}]}>{loading?"…":p.percent+"%"}</Text>
    <View accessibilityRole="progressbar" accessibilityValue={{min:0,max:100,now:p.percent}} accessibilityLabel={`${name} completion`} style={s.meter}><View style={{height:"100%",width:`${p.percent}%`,backgroundColor:color,borderRadius:5}}/></View>
    <Text style={[s.count,{fontSize:compact?10:12}]}>{loading?"Loading progress…":`${p.done.toLocaleString()} / ${p.total.toLocaleString()} attempted`}</Text>
    {!compact&&<Text style={s.range}>{r.from}–{r.to}</Text>}
   </Pressable>})}</View>)}
   <View style={s.footer}><Text style={[s.muted,{flex:1,fontSize:11}]}>Each question counts once.</Text><Pressable accessibilityRole="button" onPress={()=>router.push("/past-paper-history")} style={s.history}><Ionicons name="time-outline" size={16} color="#CAD3E0"/><Text style={s.link}>History</Text></Pressable></View>
  </View>
  <Modal visible={subject!==null} transparent animationType="fade" onRequestClose={()=>setSubject(null)}><Pressable style={s.overlay} onPress={()=>setSubject(null)}><Pressable style={[s.sheet,{borderColor:accent+"70"}]} onPress={e=>e.stopPropagation()}><View style={s.sheetHead}><View style={{flex:1}}><Text style={[s.muted,{color:accent}]}>{subject}</Text><Text style={s.title}>Choose a section</Text></View><Pressable accessibilityLabel="Close sections" onPress={()=>setSubject(null)} style={s.icon}><Ionicons name="close" size={22} color="#FFF"/></Pressable></View>{subjectSections(subject??"").map(section=><Pressable accessibilityRole="button" key={section} onPress={()=>select(section)} style={[s.option,section==="Full Paper"&&{backgroundColor:accent+"22",borderColor:accent+"70"}]}><Ionicons name={section==="Full Paper"?"timer-outline":"checkbox-outline"} size={23} color={accent}/><View style={{flex:1}}><Text style={s.optionTitle}>{section==="Full Paper"?"Full paper":section}</Text><Text style={s.muted}>{section==="Full Paper"?"Start timer · record questions when finished":"Tick completed questions"}</Text></View><Ionicons name="chevron-forward" size={20} color={accent}/></Pressable>)}<Pressable onPress={()=>{const name=subject;setSubject(null);router.push({pathname:"/past-paper-record",params:{subjectName:name??"Physics",paperSection:"Full Paper"}})}} style={s.record}><Text style={[s.link,{color:accent}]}>Already done? Record questions</Text></Pressable></Pressable></Pressable></Modal>
  <Modal visible={tools} transparent animationType="fade" onRequestClose={()=>setTools(false)}><Pressable style={s.overlay} onPress={()=>setTools(false)}><Pressable style={s.sheet} onPress={e=>e.stopPropagation()}><View style={s.sheetHead}><Text style={[s.title,{flex:1}]}>Past paper tools</Text><Pressable accessibilityLabel="Close tools" onPress={()=>setTools(false)} style={s.icon}><Ionicons name="close" size={22} color="#FFF"/></Pressable></View>{([{title:"Attempt history",path:"/past-paper-history"},{title:"Year ranges",path:"/past-paper-settings"},{title:"Paper analysis",path:"/paper-analysis"},{title:"Question report",path:"/past-paper-question-report"}] as const).map(x=><Pressable key={x.path} onPress={()=>tool(x.path)} style={s.option}><Text style={[s.optionTitle,{flex:1}]}>{x.title}</Text><Ionicons name="chevron-forward" size={20} color="#CAD3E0"/></Pressable>)}</Pressable></Pressable></Modal>
 </SafeAreaView>
}
const s=createThemeStyles({root:{flex:1,backgroundColor:"#090E17"},head:{paddingHorizontal:16,paddingVertical:14,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#243040"},icon:{width:42,height:42,borderRadius:13,backgroundColor:"#17212E",alignItems:"center",justifyContent:"center"},title:{fontSize:23,fontWeight:"800",color:"#F3F6FA"},muted:{color:"#A2B0C2",fontSize:12,marginTop:3},content:{flex:1,width:"100%",maxWidth:1000,alignSelf:"center",gap:12},row:{flex:1,flexDirection:"row",gap:12,minHeight:0},card:{flex:1,minWidth:0,borderRadius:22,borderWidth:1},cardTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},subjectIcon:{borderRadius:13,alignItems:"center",justifyContent:"center"},subjectName:{color:"#F4F6FA",fontWeight:"800"},percent:{fontWeight:"800",fontVariant:["tabular-nums"]},meter:{height:8,borderRadius:5,backgroundColor:"#273344",overflow:"hidden",marginTop:5},count:{color:"#D0D8E4",marginTop:8,fontWeight:"600"},range:{color:"#91A2B8",fontSize:11,marginTop:4},footer:{flexDirection:"row",alignItems:"center",gap:8},history:{minHeight:36,flexDirection:"row",gap:6,alignItems:"center",paddingHorizontal:8},link:{color:"#CAD3E0",fontWeight:"700",fontSize:12},overlay:{flex:1,backgroundColor:"#000000BB",padding:16,justifyContent:"center"},sheet:{width:"100%",maxWidth:500,alignSelf:"center",padding:18,borderRadius:24,borderWidth:1,borderColor:"#384A60",backgroundColor:"#101924"},sheetHead:{flexDirection:"row",alignItems:"center",gap:10,marginBottom:14},option:{minHeight:65,padding:12,borderWidth:1,borderColor:"#2E4054",borderRadius:15,backgroundColor:"#172332",marginBottom:9,flexDirection:"row",alignItems:"center",gap:12},optionTitle:{color:"#F0F4FA",fontSize:16,fontWeight:"700"},record:{minHeight:44,alignItems:"center",justifyContent:"center"}});
