import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React,{useMemo}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{usePlanning}from"../context/PlanningContext";
import{useStudent}from"../context/StudentContext";
import{expandSubjectChoices}from"../data/subjects";
import{planningBucketFor}from"../lib/planner";

const signed=(m:number)=>`${m>0?"+":m<0?"−":""}${Math.abs(m)} min/week`;
export default function PlannerControls(){
 const router=useRouter();const{profile,saveProfile}=useStudent();const{preferences,updatePreferences,setSubjectAdjustment,resetDefaults}=usePlanning();const subjects=useMemo(()=>[...new Set(expandSubjectChoices(profile.subjectChoices).map(planningBucketFor))],[profile.subjectChoices]);
 const target=async(d:number)=>saveProfile({selfStudyHours:Math.max(1,Math.min(18,Math.round((profile.selfStudyHours+d)*2)/2))});
 return <View style={s.root}><LinearGradient colors={["#171022","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.title}>Planner controls</Text><Text style={s.sub}>Workload, balance and recovery behavior</Text></View></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
 <Text style={s.section}>DAILY TARGET</Text><View style={s.card}><View style={s.settingRow}><View style={{flex:1}}><Text style={s.settingTitle}>Academic work target</Text><Text style={s.value}>{profile.selfStudyHours.toFixed(1)} hours/day</Text><Text style={s.help}>StudyArc will actively fill toward this target using assignments, classes and study. Very high targets use shorter blocks and more frequent recovery.</Text></View><View style={s.steps}><Pressable onPress={()=>target(-.5)} style={s.step}><Ionicons name="remove" size={18} color="#D7C2F0"/></Pressable><Pressable onPress={()=>target(.5)} style={s.step}><Ionicons name="add" size={18} color="#D7C2F0"/></Pressable></View></View><Toggle title="Count class time toward target" text="Effective class time excludes the interval/break recorded for that class." value={preferences.countClassTimeTowardTarget} onPress={()=>updatePreferences({countClassTimeTowardTarget:!preferences.countClassTimeTowardTarget})}/></View>
 <Text style={s.section}>FOCUS BLOCKS</Text><View style={s.card}><Text style={s.settingTitle}>Maximum uninterrupted study block</Text><View style={s.choices}>{([60,90,120,180] as const).map(v=><Pressable key={v} onPress={()=>updatePreferences({maxStudyBlockMinutes:v})} style={[s.choice,preferences.maxStudyBlockMinutes===v&&s.choiceOn]}><Text style={[s.choiceText,preferences.maxStudyBlockMinutes===v&&s.choiceTextOn]}>{v===60?"1h":v===90?"1h 30m":v===120?"2h":"3h"}</Text></Pressable>)}</View></View>
 <Text style={s.section}>CATCH-UP MODE</Text><View style={s.card}><Toggle title="Catch-up Mode" text="Prioritize weak/revise/recovery work without increasing your declared hours or scheduling through sleep/classes." value={preferences.catchUpMode} onPress={()=>updatePreferences({catchUpMode:!preferences.catchUpMode})}/></View>
 <Text style={s.section}>WEEKLY SUBJECT BALANCE</Text><Text style={s.help}>Pure Mathematics and Applied Mathematics are controlled independently. Positive values increase that subject's share; negative values reduce it while minimum-allocation safeguards remain active.</Text><View style={s.card}>{subjects.map(subject=>{const v=preferences.weeklySubjectAdjustments[subject]??0;return <View key={subject} style={s.balance}><View style={{flex:1}}><Text style={s.balanceName}>{subject}</Text><Text style={s.balanceValue}>{signed(v)}</Text></View><View style={s.steps}><Pressable onPress={()=>setSubjectAdjustment(subject,v-30)} style={s.step}><Ionicons name="remove" size={17} color="#D7C2F0"/></Pressable><Pressable onPress={()=>setSubjectAdjustment(subject,v+30)} style={s.step}><Ionicons name="add" size={17} color="#D7C2F0"/></Pressable></View></View>})}</View>
 <View style={s.highOutput}><Ionicons name="flame-outline" size={20} color="#F0B477"/><View style={{flex:1}}><Text style={s.highTitle}>High-output targets</Text><Text style={s.highSub}>Above 10 hours/day, StudyArc uses shorter focus blocks and recovery spacing. It will push toward the target, but it will not schedule through your sleep or fixed class/protected time.</Text></View></View>
 <Pressable onPress={async()=>{await resetDefaults();await saveProfile({selfStudyHours:3})}} style={s.reset}><Ionicons name="refresh-outline" size={18} color="#AAB5C2"/><View style={{flex:1}}><Text style={s.resetTitle}>Reset planner defaults</Text><Text style={s.resetSub}>3 hours/day, classes count, 3-hour max blocks, Catch-up off and neutral subject adjustments.</Text></View></Pressable>
 </ScrollView></View>
}
function Toggle({title,text,value,onPress}:{title:string;text:string;value:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={s.toggleRow}><View style={{flex:1}}><Text style={s.settingTitle}>{title}</Text><Text style={s.help}>{text}</Text></View><View style={[s.toggle,value&&s.toggleOn]}><View style={[s.knob,value&&s.knobOn]}/></View></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:11},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F5F6F8",fontSize:24,fontWeight:"900"},sub:{color:"#748194",fontSize:11,marginTop:3},content:{padding:20,paddingBottom:50,maxWidth:800,width:"100%",alignSelf:"center"},section:{color:"#8190A3",fontSize:10,fontWeight:"900",letterSpacing:1.3,marginTop:18,marginBottom:9},card:{borderRadius:19,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:14},settingRow:{flexDirection:"row",alignItems:"center",gap:10},settingTitle:{color:"#E9EDF2",fontSize:13,fontWeight:"900"},value:{color:"#D9C3F4",fontSize:22,fontWeight:"900",marginTop:5},help:{color:"#748194",fontSize:10.5,lineHeight:16,marginTop:4},steps:{flexDirection:"row",gap:6},step:{width:39,height:39,borderRadius:11,backgroundColor:"#21182D",alignItems:"center",justifyContent:"center"},toggleRow:{minHeight:74,flexDirection:"row",alignItems:"center",gap:10,borderTopWidth:1,borderTopColor:"#25303D",marginTop:12,paddingTop:12},toggle:{width:49,height:29,borderRadius:15,backgroundColor:"#283342",padding:3},toggleOn:{backgroundColor:"#704AA1"},knob:{width:23,height:23,borderRadius:12,backgroundColor:"#9AA5B3"},knobOn:{marginLeft:20,backgroundColor:"#FFF"},choices:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:11},choice:{minHeight:42,borderRadius:12,backgroundColor:"#17202B",borderWidth:1,borderColor:"#2C3948",paddingHorizontal:14,alignItems:"center",justifyContent:"center"},choiceOn:{backgroundColor:"#3A2752",borderColor:"#7756A2"},choiceText:{color:"#8290A2",fontSize:10.5,fontWeight:"900"},choiceTextOn:{color:"#F0E6FC"},balance:{minHeight:64,flexDirection:"row",alignItems:"center",gap:9,borderBottomWidth:1,borderBottomColor:"#25303D"},balanceName:{color:"#DDE2E8",fontSize:12,fontWeight:"900"},balanceValue:{color:"#8A789E",fontSize:10,marginTop:3},highOutput:{minHeight:78,borderRadius:17,backgroundColor:"#211A12",borderWidth:1,borderColor:"#4A3721",padding:12,flexDirection:"row",alignItems:"flex-start",gap:10,marginTop:14},highTitle:{color:"#E9D7BA",fontSize:12,fontWeight:"900"},highSub:{color:"#9B866B",fontSize:10.5,lineHeight:16,marginTop:3},reset:{minHeight:69,borderRadius:17,backgroundColor:"#111923",borderWidth:1,borderColor:"#293646",padding:12,flexDirection:"row",alignItems:"center",gap:10,marginTop:16},resetTitle:{color:"#DDE2E8",fontSize:12,fontWeight:"900"},resetSub:{color:"#748194",fontSize:10,lineHeight:14,marginTop:3}})
