import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useAppConfig } from "../context/AppConfigContext";

export default function PrivacyScreen(){const router=useRouter();const{settings}=useAppConfig();return <View style={s.root}><LinearGradient colors={["#151020","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><Text style={s.title}>Privacy Policy</Text></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text style={s.updated}>Study Arc · in-app privacy summary</Text><Section title="Information Study Arc stores">Account identifiers, selected A/L stream and subjects, planning preferences, classes, study sessions, paper activity, test results, topic progress, assignments, exam dates and settings you choose to save. Payment receipts are stored privately when manual payment is used.</Section><Section title="Why it is used">Your data is used to provide authentication, sync, offline recovery, study planning, readiness calculations, progress reports, reminders, subscription access and account support.</Section><Section title="Administrative access">Administrators receive role-based access. Operational dashboards are designed around aggregate information. User-level access is limited to functions such as account support, subscription/payment review, activation and account restrictions.</Section><Section title="Social features">Leaderboard and friend features are optional parts of the app and are not used to calculate readiness or planner priorities.</Section><Section title="Payments">Normal users cannot approve payments, change plan prices, grant themselves Premium or alter block status. Receipt files are stored in a private bucket and access is restricted to the submitting user and authorized administrators.</Section><Section title="Your controls">You can export your Study Arc data, clear study history and request permanent account deletion from Data & privacy controls. Clearing study history does not delete the account or timetable setup.</Section><Section title="Security">Study Arc uses authenticated Supabase access and row-level security for protected cloud data. No system can guarantee absolute security, so credentials should remain private and strong passwords should be used.</Section><Section title="Contact">Questions about privacy or account data can be sent to {settings.contactEmail}.</Section></ScrollView></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text><Text style={s.text}>{children}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:11},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F5F6F8",fontSize:22,fontWeight:"900"},content:{padding:20,paddingBottom:50,maxWidth:720,width:"100%",alignSelf:"center"},updated:{color:"#8B78A0",fontSize:9,fontWeight:"900",letterSpacing:1,marginBottom:10},card:{borderRadius:17,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:14,marginBottom:8},cardTitle:{color:"#E8EBEF",fontSize:11.5,fontWeight:"900"},text:{color:"#748194",fontSize:10,lineHeight:17,marginTop:6}})
