import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React, { useState } from "react";
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useStudent } from "../context/StudentContext";
import { type StudyMedium } from "../data/subjects";
import { availableExamYears } from "../lib/exams";

export default function ProfileScreen(){
  const router=useRouter();
  const{profile,saveProfile,uploadAvatar}=useStudent();
  const[name,setName]=useState(profile.fullName),[district,setDistrict]=useState(profile.district),[year,setYear]=useState(profile.examYear),[medium,setMedium]=useState<StudyMedium>(profile.medium),[saving,setSaving]=useState(false),[photoSaving,setPhotoSaving]=useState(false);
  const save=async()=>{if(!name.trim()){Alert.alert("Add your name","Your name helps personalize the plan.");return;}setSaving(true);try{await saveProfile({fullName:name.trim(),district:district.trim(),examYear:year,medium});router.back()}catch(e){Alert.alert("Could not save",e instanceof Error?e.message:"Try again.")}finally{setSaving(false)}};
  const changePhoto=async()=>{if(photoSaving)return;setPhotoSaving(true);try{await uploadAvatar()}catch(e){Alert.alert("Photo not updated",e instanceof Error?e.message:"Try again.")}finally{setPhotoSaving(false)}};
  return <View style={s.root}><LinearGradient colors={["#171023","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={22} color="#FFF"/></Pressable><Text style={s.title}>Profile</Text><Pressable disabled={saving} onPress={save} style={[s.save,saving&&{opacity:.55}]}><Text style={s.saveText}>{saving?"Saving…":"Save"}</Text></Pressable></View><ScrollView contentContainerStyle={s.content}>
    <Pressable disabled={photoSaving} onPress={changePhoto} style={[s.avatarWrap,photoSaving&&{opacity:.65}]}>{profile.avatarUrl?<Image source={{uri:profile.avatarUrl}} style={s.avatar}/>:<View style={[s.avatar,s.avatarEmpty]}><Ionicons name="person" size={42} color="#D8C5F2"/></View>}<View style={s.editPhoto}><Ionicons name={photoSaving?"hourglass-outline":"camera"} size={15} color="#FFF"/></View></Pressable><Text style={s.photoHint}>{photoSaving?"Uploading photo…":"Tap to choose a profile photo"}</Text>
    <Field label="FULL NAME" value={name} setValue={setName} placeholder="Your name"/><Field label="DISTRICT" value={district} setValue={setDistrict} placeholder="Optional"/>
    <Text style={s.labelTop}>STUDY MEDIUM</Text><Text style={s.help}>Subject names stay English. Lesson and sublesson names change with this setting.</Text><View style={s.mediumRow}>{(["English","Sinhala"] as StudyMedium[]).map(value=><Pressable key={value} onPress={()=>setMedium(value)} style={[s.medium,medium===value&&s.mediumActive]}><Ionicons name={value==="English"?"language-outline":"book-outline"} size={18} color={medium===value?"#E9D9FF":"#7A8798"}/><Text style={[s.mediumText,medium===value&&s.mediumTextActive]}>{value}</Text></Pressable>)}</View>
    <Text style={s.labelTop}>A/L EXAM YEAR</Text><View style={s.years}>{availableExamYears().map(y=><Pressable key={y} onPress={()=>setYear(y)} style={[s.year,year===y&&s.yearActive]}><Text style={[s.yearText,year===y&&s.yearTextActive]}>{y}</Text></Pressable>)}</View>
    <View style={s.note}><Ionicons name="cloud-done-outline" size={20} color="#B784FF"/><Text style={s.noteText}>Profile and medium changes sync to your Study Arc account. Profile photos use your private authenticated upload folder.</Text></View>
  </ScrollView></View>;
}
function Field({label,value,setValue,placeholder}:{label:string;value:string;setValue:(v:string)=>void;placeholder:string}){return <View style={{marginTop:19}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={setValue} placeholder={placeholder} placeholderTextColor="#526071" style={s.input}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},header:{height:76,paddingHorizontal:18,paddingTop:10,flexDirection:"row",alignItems:"center",gap:12},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151C27",alignItems:"center",justifyContent:"center"},title:{flex:1,color:"#F6F4F8",fontSize:22,fontWeight:"900"},save:{paddingHorizontal:18,height:42,borderRadius:14,backgroundColor:"#B784FF",alignItems:"center",justifyContent:"center"},saveText:{color:"#170D20",fontWeight:"900"},content:{padding:22,paddingBottom:45,maxWidth:700,width:"100%",alignSelf:"center"},avatarWrap:{alignSelf:"center",position:"relative"},avatar:{width:104,height:104,borderRadius:32},avatarEmpty:{backgroundColor:"#21192E",borderWidth:1,borderColor:"#4A3862",alignItems:"center",justifyContent:"center"},editPhoto:{position:"absolute",right:-5,bottom:-5,width:34,height:34,borderRadius:17,backgroundColor:"#7950C6",borderWidth:3,borderColor:"#0D121B",alignItems:"center",justifyContent:"center"},photoHint:{color:"#748194",fontSize:11,textAlign:"center",marginTop:12},label:{color:"#788596",fontSize:9,fontWeight:"900",letterSpacing:1.2,marginBottom:8},labelTop:{color:"#788596",fontSize:9,fontWeight:"900",letterSpacing:1.2,marginTop:22,marginBottom:8},input:{height:56,borderRadius:17,backgroundColor:"#111923",borderWidth:1,borderColor:"#283546",paddingHorizontal:16,color:"#F2F4F7",fontSize:14,fontWeight:"700"},help:{color:"#718092",fontSize:10,lineHeight:15,marginTop:-3,marginBottom:9},mediumRow:{flexDirection:"row",gap:9},medium:{flex:1,minHeight:52,borderRadius:16,backgroundColor:"#111923",borderWidth:1,borderColor:"#283546",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},mediumActive:{backgroundColor:"#382655",borderColor:"#7C5BB5"},mediumText:{color:"#8290A2",fontSize:12,fontWeight:"900"},mediumTextActive:{color:"#F0E6FF"},years:{flexDirection:"row",gap:9,flexWrap:"wrap"},year:{height:48,minWidth:80,paddingHorizontal:18,borderRadius:15,backgroundColor:"#111923",borderWidth:1,borderColor:"#283546",alignItems:"center",justifyContent:"center"},yearActive:{backgroundColor:"#382655",borderColor:"#7C5BB5"},yearText:{color:"#8290A2",fontWeight:"900"},yearTextActive:{color:"#F0E6FF"},note:{marginTop:25,backgroundColor:"#171322",borderWidth:1,borderColor:"#3C3050",borderRadius:17,padding:15,flexDirection:"row",gap:10},noteText:{flex:1,color:"#968CA4",fontSize:11,lineHeight:17}});
