import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useLocalSearchParams,useRouter } from "expo-router";
import React,{useMemo,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{useStudent}from"../context/StudentContext";
import{useStudy}from"../context/StudyContext";
import{expandSubjectChoices}from"../data/subjects";
import{paperSectionsForSubject,type FlexiblePaperSection}from"../lib/paperFormats";

export default function QuickPastPaper(){
 const router=useRouter();const p=useLocalSearchParams<{subjectName?:string}>();const{profile}=useStudent();const{getPaperAttemptCount}=useStudy();
 const subjects=useMemo(()=>{const x=expandSubjectChoices(profile.subjectChoices);return x.length?x:["Physics"]},[profile.subjectChoices]);
 const[subject,setSubject]=useState(subjects.includes(p.subjectName||"")?p.subjectName!:subjects[0]);
 const[section,setSection]=useState<FlexiblePaperSection>(paperSectionsForSubject(subject)[0]);
 const[year,setYear]=useState(String(Math.max(1900,(profile.examYear??new Date().getFullYear())-1)));
 const[target,setTarget]=useState("180");
 const[error,setError]=useState<string|null>(null);
 const chooseSubject=(x:string)=>{setSubject(x);setSection(paperSectionsForSubject(x)[0])};
 const start=()=>{const y=Number(year),minutes=Number(target);if(!/^\d{4}$/.test(year)||y<1900||y>new Date().getFullYear()){setError("Enter a valid past-paper year.");return}if(!Number.isFinite(minutes)||minutes<=0||minutes>600){setError("Enter a target time between 1 and 600 minutes.");return}setError(null);router.push({pathname:"/paper-stopwatch",params:{subjectName:subject,topicName:"General",studyType:"Past Papers",paperYear:String(y),paperSection:section,attemptNo:String(getPaperAttemptCount(subject,y,section as any)+1),targetMinutes:String(Math.round(minutes)),markAfter:"1"}})};
 return <View style={s.root}><LinearGradient colors={["#211432","#090D14","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View><Text style={s.kicker}>QUICK PAST PAPER</Text><Text style={s.title}>Set up & start</Text></View></View><ScrollView contentContainerStyle={s.content}>
  <View style={s.hero}><Ionicons name="timer-outline" size={28} color="#DCC5F8"/><View style={{flex:1}}><Text style={s.heroTitle}>Start a paper in a few seconds</Text><Text style={s.help}>Enter the paper year and your target time. StudyArc will time the attempt and take you to marks entry when you finish.</Text></View></View>
  <Text style={s.label}>SUBJECT</Text><View style={s.wrap}>{subjects.map(x=><Choice key={x} title={x} on={subject===x} press={()=>chooseSubject(x)}/>)}</View>
  <Text style={s.label}>PAPER SECTION</Text><View style={s.wrap}>{paperSectionsForSubject(subject).map(x=><Choice key={x} title={x} on={section===x} press={()=>setSection(x)}/>)}</View>
  <View style={s.row}><View style={{flex:1}}><Text style={s.label}>PAST-PAPER YEAR</Text><TextInput value={year} onChangeText={setYear} keyboardType="number-pad" placeholder="e.g. 2024" placeholderTextColor="#687587" style={s.input}/></View><View style={{flex:1}}><Text style={s.label}>TARGET MINUTES</Text><TextInput value={target} onChangeText={setTarget} keyboardType="number-pad" placeholder="e.g. 180" placeholderTextColor="#687587" style={s.input}/></View></View>
  <View style={s.presets}><Text style={s.presetLabel}>QUICK TIME</Text>{[60,90,120,180].map(n=><Pressable key={n} onPress={()=>setTarget(String(n))} style={[s.preset,target===String(n)&&s.presetOn]}><Text style={s.presetText}>{n}m</Text></Pressable>)}</View>
  {error?<Text style={s.error}>{error}</Text>:null}
  <Pressable onPress={start} style={s.start}><Ionicons name="play" size={20} color="#160B20"/><Text style={s.startText}>Start past-paper timer</Text></Pressable>
  <Pressable onPress={()=>router.push({pathname:"/manual-past-paper",params:{subjectName:subject,paperYear:year,paperSection:section}})} style={s.manual}><Ionicons name="create-outline" size={18} color="#D5B9F3"/><View><Text style={s.manualTitle}>Already completed it?</Text><Text style={s.help}>Enter the time and marks without starting a timer.</Text></View></Pressable>
 </ScrollView></View>
}
function Choice({title,on,press}:{title:string;on:boolean;press:()=>void}){return <Pressable onPress={press} style={[s.choice,on&&s.choiceOn]}><Text style={[s.choiceText,on&&s.choiceTextOn]}>{title}</Text></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{minHeight:78,padding:18,flexDirection:"row",alignItems:"center",gap:12},back:{width:42,height:42,borderRadius:14,backgroundColor:"#151C27",alignItems:"center",justifyContent:"center"},kicker:{color:"#A987D0",fontSize:8,fontWeight:"900",letterSpacing:1.3},title:{color:"#F7F4FA",fontSize:21,fontWeight:"900",marginTop:2},content:{padding:18,paddingBottom:50,maxWidth:760,width:"100%",alignSelf:"center"},hero:{minHeight:100,borderRadius:22,backgroundColor:"#171321",borderWidth:1,borderColor:"#503B62",padding:16,flexDirection:"row",alignItems:"center",gap:13},heroTitle:{color:"#F3EDF8",fontSize:14,fontWeight:"900"},help:{color:"#8995A5",fontSize:9,lineHeight:14,marginTop:4},label:{color:"#8B98A9",fontSize:8,fontWeight:"900",letterSpacing:1.1,marginTop:18,marginBottom:8},wrap:{flexDirection:"row",flexWrap:"wrap",gap:7},choice:{minHeight:39,paddingHorizontal:11,borderRadius:12,backgroundColor:"#121B25",borderWidth:1,borderColor:"#303E4E",alignItems:"center",justifyContent:"center"},choiceOn:{backgroundColor:"#3A2850",borderColor:"#8D65B8"},choiceText:{color:"#8592A3",fontSize:9,fontWeight:"900"},choiceTextOn:{color:"#F3E9FC"},row:{flexDirection:"row",gap:10},input:{height:50,borderRadius:14,backgroundColor:"#0C131C",borderWidth:1,borderColor:"#344355",paddingHorizontal:13,color:"#F5F3F7",fontSize:14,fontWeight:"800"},presets:{flexDirection:"row",alignItems:"center",gap:6,marginTop:10},presetLabel:{color:"#687688",fontSize:7,fontWeight:"900",marginRight:3},preset:{height:31,paddingHorizontal:9,borderRadius:9,backgroundColor:"#17202B",alignItems:"center",justifyContent:"center"},presetOn:{backgroundColor:"#3A2850"},presetText:{color:"#BDA5D8",fontSize:8,fontWeight:"900"},error:{color:"#FFB3B3",fontSize:9,marginTop:12},start:{height:54,borderRadius:16,backgroundColor:"#C094FA",marginTop:20,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},startText:{color:"#160B20",fontSize:12,fontWeight:"900"},manual:{minHeight:66,borderRadius:16,backgroundColor:"#15111D",borderWidth:1,borderColor:"#3C2F49",padding:12,marginTop:10,flexDirection:"row",alignItems:"center",gap:10},manualTitle:{color:"#E3D6EF",fontSize:10,fontWeight:"900"}});
