import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React,{useMemo,useState} from "react";
import { Pressable,ScrollView,StyleSheet,Text,View } from "react-native";
import FeatureDisabledScreen from "../components/FeatureDisabledScreen";
import { useRewards } from "../context/RewardsContext";
import { useAppConfig } from "../context/AppConfigContext";
import { rewardFlagEnabled } from "../lib/rewardFeatureFlags";

type Filter="all"|"earned"|"spent";
export default function RewardHistoryScreen(){
 const router=useRouter();
 const{settings}=useAppConfig();
 const historyEnabled=rewardFlagEnabled(settings.featureFlags,"rewardsSystem")&&rewardFlagEnabled(settings.featureFlags,"arcCoins")&&rewardFlagEnabled(settings.featureFlags,"rewardHistory");
 const xpOn=rewardFlagEnabled(settings.featureFlags,"rewardsSystem")&&rewardFlagEnabled(settings.featureFlags,"xpLevels");
 const{transactions,coinBalance,lifetimeCoins,xp}=useRewards();
 const[filter,setFilter]=useState<Filter>("all");
 const rows=useMemo(()=>transactions.filter(x=>filter==="all"||(filter==="earned"?x.coins>=0:x.coins<0)),[filter,transactions]);
 if(!historyEnabled)return <FeatureDisabledScreen title="Arc Coin history is off" message="The StudyArc administrator has temporarily disabled Arc Coin history. Existing reward and purchase records are preserved."/>;
 return <View style={s.root}><LinearGradient colors={["#15101F","#080D14","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><View style={{flex:1}}><Text style={s.kicker}>TRANSPARENT REWARD LEDGER</Text><Text style={s.title}>Arc Coin History</Text></View></View><ScrollView contentContainerStyle={s.content}>
  <View style={s.summary}><Mini label="CURRENT BALANCE" value={`${coinBalance} AC`} icon="diamond-outline"/><Mini label="LIFETIME EARNED" value={`${lifetimeCoins} AC`} icon="trending-up-outline"/>{xpOn?<Mini label="LIFETIME XP" value={xp.toLocaleString()} icon="sparkles-outline"/>:null}</View>
  <View style={s.filters}>{(["all","earned","spent"] as Filter[]).map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[s.filter,filter===x&&s.filterOn]}><Text style={[s.filterText,filter===x&&s.filterTextOn]}>{x==="all"?"All":x==="earned"?"Earned":"Spent"}</Text></Pressable>)}</View>
  <View style={s.list}>{rows.length?rows.map(row=><View key={row.id} style={s.row}><View style={[s.icon,row.coins<0?s.spendIcon:s.earnIcon]}><Ionicons name={row.coins<0?"bag-check-outline":"add-circle-outline"} size={18} color={row.coins<0?"#E6A7B2":"#9DE0B7"}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{row.label}</Text><Text style={s.rowMeta}>{new Date(row.createdAt).toLocaleString()} · {row.kind.replaceAll("-"," ").toUpperCase()}</Text><Text style={s.eventKey} numberOfLines={1}>{row.eventKey}</Text></View><View style={{alignItems:"flex-end"}}><Text style={[s.amount,row.coins<0&&s.spend]}>{row.coins>0?"+":""}{row.coins} AC</Text>{xpOn&&row.xp>0?<Text style={s.xp}>+{row.xp} XP</Text>:null}</View></View>):<View style={s.empty}><Ionicons name="receipt-outline" size={33} color="#566273"/><Text style={s.emptyText}>No Arc Coin transactions in this view yet.</Text></View>}</View>
  <Text style={s.note}>Each legitimate reward uses a unique event key, so the same completed work cannot award coins twice. Purchases are recorded as negative Arc Coin transactions; XP is never spent when XP is enabled.</Text>
 </ScrollView></View>
}
function Mini({label,value,icon}:{label:string;value:string;icon:string}){return <View style={s.mini}><Ionicons name={icon as any} size={18} color="#B993DD"/><Text style={s.miniValue}>{value}</Text><Text style={s.miniLabel}>{label}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},header:{minHeight:78,paddingHorizontal:18,paddingTop:12,paddingBottom:10,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#271E31"},back:{width:42,height:42,borderRadius:14,backgroundColor:"#151B24",alignItems:"center",justifyContent:"center"},kicker:{color:"#9277AA",fontSize:8,fontWeight:"900",letterSpacing:1.4},title:{color:"#FFF",fontSize:22,fontWeight:"900"},content:{padding:18,paddingBottom:50,maxWidth:900,width:"100%",alignSelf:"center"},summary:{flexDirection:"row",gap:8,flexWrap:"wrap"},mini:{flex:1,minWidth:160,minHeight:96,borderRadius:18,backgroundColor:"#111923",borderWidth:1,borderColor:"#293646",padding:13},miniValue:{color:"#F1F3F6",fontSize:19,fontWeight:"900",marginTop:9},miniLabel:{color:"#6D7989",fontSize:7,fontWeight:"900",letterSpacing:.8,marginTop:3},filters:{flexDirection:"row",gap:7,marginTop:14},filter:{height:37,paddingHorizontal:14,borderRadius:12,backgroundColor:"#141C26",borderWidth:1,borderColor:"#2A3746",justifyContent:"center"},filterOn:{backgroundColor:"#C59AFF",borderColor:"#C59AFF"},filterText:{color:"#9AA7B4",fontSize:8.5,fontWeight:"900"},filterTextOn:{color:"#160B20"},list:{borderRadius:19,backgroundColor:"#101720",borderWidth:1,borderColor:"#263341",paddingHorizontal:12,marginTop:12},row:{minHeight:76,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:"#202B37"},icon:{width:40,height:40,borderRadius:13,alignItems:"center",justifyContent:"center"},earnIcon:{backgroundColor:"#143024"},spendIcon:{backgroundColor:"#321C23"},rowTitle:{color:"#EBEEF2",fontSize:10.5,fontWeight:"900"},rowMeta:{color:"#687587",fontSize:7.5,marginTop:3},eventKey:{color:"#4F5B69",fontSize:6.5,marginTop:3,maxWidth:420},amount:{color:"#9EE0B8",fontSize:10,fontWeight:"900"},spend:{color:"#E2A1AC"},xp:{color:"#A88AC6",fontSize:7.5,fontWeight:"800",marginTop:3},empty:{minHeight:220,alignItems:"center",justifyContent:"center"},emptyText:{color:"#687587",fontSize:9.5,marginTop:9},note:{color:"#625A6A",fontSize:8.5,lineHeight:14,textAlign:"center",marginTop:17}});
