import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useLocalSearchParams,useRouter } from "expo-router";
import React,{useEffect,useRef,useState} from "react";
import {Animated,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {useStudy} from "../context/StudyContext";
import {useStudent} from "../context/StudentContext";
import {topicDisplayName} from "../data/subjects";

const fmt=(sec:number)=>{const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${h}h ${m}m ${s}s`:m?`${m}m ${s}s`:`${s}s`};
export default function SessionComplete(){
 const router=useRouter();const p=useLocalSearchParams<{sessionId?:string;duration?:string;subjectName?:string;topicName?:string;studyType?:string}>();const{updateSessionAnalysis}=useStudy();const{profile}=useStudent();
 const[focus,setFocus]=useState<number|null>(null),[understanding,setUnderstanding]=useState<number|null>(null),[note,setNote]=useState(""),[saving,setSaving]=useState(false);const pop=useRef(new Animated.Value(.8)).current,glow=useRef(new Animated.Value(0)).current;
 useEffect(()=>{Animated.parallel([Animated.spring(pop,{toValue:1,useNativeDriver:true,friction:5}),Animated.timing(glow,{toValue:1,duration:650,useNativeDriver:true})]).start()},[glow,pop]);
 const save=async()=>{if(p.sessionId){setSaving(true);try{await updateSessionAnalysis(p.sessionId,{focusRating:focus,understandingRating:understanding,sessionNote:note.trim()||null})}finally{setSaving(false)}}router.replace("/(tabs)")};
 const keep=()=>router.replace({pathname:"/stopwatch",params:{subjectName:p.subjectName,topicName:p.topicName,studyType:p.studyType||"Study Session"}});
 const displayTopic=p.subjectName&&p.topicName?topicDisplayName(p.subjectName,p.topicName,profile.medium):(p.topicName||"Focused work");
 return <View style={s.root}><LinearGradient colors={["#2C1941","#121424","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.topbar}><View><Text style={s.topKicker}>SESSION COMPLETE</Text><Text style={s.topTitle}>Nice work.</Text></View><Pressable disabled={saving} onPress={save} style={s.saveTop}><Ionicons name="checkmark" size={16} color="#160C20"/><Text style={s.saveTopText}>{saving?"Saving…":"Save session"}</Text></Pressable></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <Animated.View style={[s.reward,{transform:[{scale:pop}],opacity:glow}]}><LinearGradient colors={["#6B43AA","#382154","#192031"]} style={s.rewardInner}><View style={s.trophy}><Ionicons name="trophy" size={36} color="#F5D77B"/></View><Text style={s.rewardTitle}>Session saved ✦</Text><Text style={s.rewardTime}>{fmt(Number(p.duration||0))} recorded</Text><Text style={s.rewardSub}>{p.subjectName||"Study"} · {displayTopic}</Text><View style={s.sparkRow}>{[0,1,2,3,4].map(i=><Ionicons key={i} name={i%2?"sparkles":"star"} size={13+i%2*3} color={i%2?"#CFA8FF":"#F4D884"}/>)}</View></LinearGradient></Animated.View>
  <Text style={s.optional}>OPTIONAL REFLECTION</Text><Text style={s.help}>Skip this if you want. Your study time is already safely recorded.</Text>
  <View style={s.card}><Text style={s.cardTitle}>Focus score</Text><View style={s.scaleLabels}><Text style={s.scaleText}>Distracted</Text><Text style={s.scaleText}>Deep focus</Text></View><View style={s.ratingRow}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setFocus(focus===n?null:n)} style={[s.number,focus===n&&s.numberOn]}><Text style={[s.numberText,focus===n&&s.numberTextOn]}>{n}</Text></Pressable>)}</View></View>
  <View style={s.card}><Text style={s.cardTitle}>Understanding</Text><Text style={s.cardSub}>How well did the material make sense?</Text><View style={s.stars}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setUnderstanding(understanding===n?null:n)}><Ionicons name={(understanding??0)>=n?"star":"star-outline"} size={35} color={(understanding??0)>=n?"#F4C96B":"#596679"}/></Pressable>)}</View></View>
  <View style={s.card}><Text style={s.cardTitle}>Quick note</Text><Text style={s.cardSub}>Optional detail for your future self.</Text><TextInput value={note} onChangeText={setNote} multiline placeholder="What clicked? What should you review?" placeholderTextColor="#586577" style={s.note}/></View>
  <View style={s.actions}><Pressable onPress={keep} style={s.primary}><Ionicons name="play" size={17} color="#150B1E"/><Text style={s.primaryText}>Keep studying</Text></Pressable><Pressable onPress={()=>router.replace("/(tabs)/plan")} style={s.secondary}><Ionicons name="calendar-outline" size={17} color="#DCC8F5"/><Text style={s.secondaryText}>View plan</Text></Pressable></View>
 </ScrollView></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},topbar:{minHeight:78,paddingHorizontal:18,paddingTop:15,paddingBottom:10,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:12,borderBottomWidth:1,borderBottomColor:"#30243E",backgroundColor:"#100D17CC"},topKicker:{color:"#A783D5",fontSize:8,fontWeight:"900",letterSpacing:1.4},topTitle:{color:"#FAF8FC",fontSize:22,fontWeight:"900",marginTop:3},saveTop:{height:45,paddingHorizontal:16,borderRadius:15,backgroundColor:"#B784FF",flexDirection:"row",alignItems:"center",gap:6},saveTopText:{color:"#160C20",fontSize:12,fontWeight:"900"},content:{padding:20,paddingBottom:45,maxWidth:720,width:"100%",alignSelf:"center"},reward:{borderRadius:28,overflow:"hidden"},rewardInner:{minHeight:260,borderRadius:28,borderWidth:1,borderColor:"#7857A5",padding:25,alignItems:"center",justifyContent:"center"},trophy:{width:72,height:72,borderRadius:24,backgroundColor:"#F5D77B1C",borderWidth:1,borderColor:"#F5D77B44",alignItems:"center",justifyContent:"center"},rewardTitle:{color:"#FFF9FF",fontSize:28,fontWeight:"900",marginTop:17},rewardTime:{color:"#F0D8FF",fontSize:17,fontWeight:"900",marginTop:6},rewardSub:{color:"#AA9CB9",fontSize:11,marginTop:7,textAlign:"center"},sparkRow:{flexDirection:"row",gap:11,marginTop:17,alignItems:"center"},optional:{color:"#8B789E",fontSize:9,fontWeight:"900",letterSpacing:1.3,marginTop:29},help:{color:"#798596",fontSize:11,lineHeight:17,marginTop:5,marginBottom:10},card:{borderRadius:20,backgroundColor:"#111923",borderWidth:1,borderColor:"#293646",padding:17,marginBottom:10},cardTitle:{color:"#F0F2F6",fontSize:15,fontWeight:"900"},cardSub:{color:"#748194",fontSize:10.5,marginTop:4},scaleLabels:{flexDirection:"row",justifyContent:"space-between",marginTop:13},scaleText:{color:"#6E7A8B",fontSize:9},ratingRow:{flexDirection:"row",gap:8,marginTop:7},number:{flex:1,height:49,borderRadius:14,backgroundColor:"#17202C",borderWidth:1,borderColor:"#2B3848",alignItems:"center",justifyContent:"center"},numberOn:{backgroundColor:"#6D46A7",borderColor:"#A47BD8"},numberText:{color:"#778496",fontSize:15,fontWeight:"900"},numberTextOn:{color:"#FFF"},stars:{flexDirection:"row",justifyContent:"space-between",marginTop:15,paddingHorizontal:4},note:{minHeight:88,borderRadius:14,backgroundColor:"#0D141D",borderWidth:1,borderColor:"#263241",color:"#EEF1F5",padding:12,textAlignVertical:"top",fontSize:12,marginTop:12},actions:{flexDirection:"row",gap:10,marginTop:10},primary:{flex:1,height:54,borderRadius:17,backgroundColor:"#B784FF",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},primaryText:{color:"#150B1E",fontSize:12,fontWeight:"900"},secondary:{flex:1,height:54,borderRadius:17,backgroundColor:"#171522",borderWidth:1,borderColor:"#433452",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},secondaryText:{color:"#DCC8F5",fontSize:12,fontWeight:"900"}});
