import {Ionicons} from "@expo/vector-icons";
import {LinearGradient} from "expo-linear-gradient";
import {useLocalSearchParams,useRouter} from "expo-router";
import React,{useEffect,useMemo,useRef,useState} from "react";
import {Animated,PanResponder,Pressable,ScrollView,StyleSheet,Text,TextInput,View,useWindowDimensions} from "react-native";
import Screen from "../components/Screen";
import {useAcademic} from "../context/AcademicContext";
import {useTaskPlanning,type PlannedTask} from "../context/TaskPlanningContext";
const key=(d:Date)=>d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");
const dateFrom=(v:string)=>new Date(v+"T12:00:00"); const plus=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return key(d)};
const dayLabel=(v:string)=>dateFrom(v).toLocaleDateString(undefined,{weekday:"short",day:"numeric"});
function DraggableTask({task,onDrop,onToggle}:{task:PlannedTask;onDrop:(id:string,dx:number,dy:number)=>void;onToggle:()=>void}){
 const pan=useRef(new Animated.ValueXY()).current;
 const responder=useMemo(()=>PanResponder.create({onStartShouldSetPanResponder:()=>false,onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>8||Math.abs(g.dy)>8,onPanResponderGrant:()=>pan.setOffset({x:(pan.x as any)._value,y:(pan.y as any)._value}),onPanResponderMove:Animated.event([null,{dx:pan.x,dy:pan.y}],{useNativeDriver:false}),onPanResponderRelease:(_,g)=>{pan.flattenOffset();pan.setValue({x:0,y:0});onDrop(task.id,g.dx,g.dy)},onPanResponderTerminate:()=>{pan.flattenOffset();pan.setValue({x:0,y:0})}}),[onDrop,pan,task.id]);
 return <Animated.View {...responder.panHandlers} style={[s.task,{transform:pan.getTranslateTransform()}]}><Pressable onPress={onToggle}><Ionicons name={task.completed?"checkmark-circle":"ellipse-outline"} size={24} color={task.completed?"#75D09C":"#7C899A"}/></Pressable><View style={{flex:1}}><Text style={[s.taskTitle,task.completed&&s.done]}>{task.title}</Text><Text style={s.meta}>{task.plannedDate??"Unscheduled"} · {task.estimatedMinutes} min{task.assignmentId?" · Assignment":""}</Text></View><Ionicons name="reorder-three" size={24} color="#8D789F"/></Animated.View>
}
export default function Tasks(){
 const router=useRouter(),p=useLocalSearchParams<{assignmentId?:string}>(),{width}=useWindowDimensions();const{assignments}=useAcademic();const{tasks,addTask,toggleTask,rescheduleTask,reorderTask}=useTaskPlanning();const[tab,setTab]=useState<"Today"|"Tomorrow"|"Week"|"Unscheduled">("Today"),[title,setTitle]=useState("");const today=key(new Date()),tomorrow=plus(1),assignment=assignments.find(x=>x.id===p.assignmentId);
 useEffect(()=>{if(assignment)setTitle(assignment.title)},[assignment?.id]);
 const week=useMemo(()=>Array.from({length:7},(_,i)=>plus(i)),[today]); const visible=useMemo(()=>tasks.filter(t=>tab==="Today"?t.plannedDate===today:tab==="Tomorrow"?t.plannedDate===tomorrow:tab==="Unscheduled"?!t.plannedDate:!!t.plannedDate&&t.plannedDate>=today&&t.plannedDate<=plus(6)).sort((a,b)=>(a.plannedDate??"9999").localeCompare(b.plannedDate??"9999")||a.sortOrder-b.sortOrder),[tasks,tab,today,tomorrow]);
 const create=async()=>{if(!title.trim())return;await addTask({title,plannedDate:tab==="Tomorrow"?tomorrow:tab==="Unscheduled"?null:today,assignmentId:assignment?.id??null,estimatedMinutes:assignment?.estimatedMinutes??30});setTitle("")};
 const drop=async(id:string,dx:number,dy:number)=>{const t=tasks.find(x=>x.id===id);if(!t)return;if(tab==="Week"){const col=Math.max(0,Math.min(6,Math.round(dx/Math.max(1,(width-32)/7))+(t.plannedDate?week.indexOf(t.plannedDate):0)));await rescheduleTask(id,week[col]);return}if(t.plannedDate&&Math.abs(dx)>55){const d=dateFrom(t.plannedDate);d.setDate(d.getDate()+(dx>0?1:-1));await rescheduleTask(id,key(d));return}const peers=visible.filter(x=>x.id!==id);if(Math.abs(dy)>25&&peers.length){const current=visible.findIndex(x=>x.id===id),next=Math.max(0,Math.min(visible.length-1,current+Math.round(dy/70))),before=visible.filter(x=>x.id!==id)[Math.min(next,visible.length-2)]?.id??null;await reorderTask(id,before,t.plannedDate??today)}};
 return <Screen><LinearGradient colors={["#171020","#080D14","#080D14"]} style={StyleSheet.absoluteFill}/><ScrollView contentContainerStyle={s.content}><View style={s.head}><Pressable onPress={()=>router.back()} style={s.icon}><Ionicons name="arrow-back" size={21} color="#fff"/></Pressable><View style={{flex:1}}><Text style={s.eyebrow}>WEEKLY ACTION PLAN</Text><Text style={s.h1}>Tasks</Text><Text style={s.sub}>Drag tasks to reorder them. In Week, drag sideways to move them to another day.</Text></View></View><View style={s.tabs}>{(["Today","Tomorrow","Week","Unscheduled"] as const).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.tabOn]}><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</View><View style={s.add}><TextInput value={title} onChangeText={setTitle} placeholder={assignment?"Schedule this assignment…":"Add a task…"} placeholderTextColor="#718094" style={s.input}/><Pressable onPress={create} style={s.addBtn}><Ionicons name="add" size={22} color="#180D21"/></Pressable></View>{assignment?<Text style={s.from}>FROM ASSIGNMENT · {assignment.subjectName}</Text>:null}
 {tab==="Week"?<View style={s.weekHead}>{week.map(d=><View key={d} style={s.weekDay}><Text style={s.weekText}>{dayLabel(d)}</Text></View>)}</View>:null}
 {visible.length?visible.map(t=><DraggableTask key={t.id} task={t} onDrop={drop} onToggle={()=>toggleTask(t.id)}/>):<View style={s.empty}><Ionicons name="checkmark-done-outline" size={30} color="#9A82B6"/><Text style={s.emptyTitle}>Nothing planned here</Text><Text style={s.emptyText}>Add a task or bring work in from Assignments.</Text></View>}</ScrollView></Screen>
}
const s=StyleSheet.create({content:{padding:16,paddingBottom:48,maxWidth:900,width:"100%",alignSelf:"center"},head:{flexDirection:"row",gap:12,alignItems:"center"},icon:{width:44,height:44,borderRadius:15,borderWidth:1,borderColor:"#303746",alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:9,fontWeight:"900",letterSpacing:1.3,color:"#9D83B7"},h1:{fontSize:27,fontWeight:"900",color:"#F5EFF8"},sub:{fontSize:10,color:"#8390A0",marginTop:3},tabs:{flexDirection:"row",gap:7,marginTop:20,flexWrap:"wrap"},tab:{minHeight:42,paddingHorizontal:14,borderRadius:14,borderWidth:1,borderColor:"#303746",alignItems:"center",justifyContent:"center"},tabOn:{backgroundColor:"#C9A4F4",borderColor:"#C9A4F4"},tabText:{fontSize:11,fontWeight:"800",color:"#9CA7B6"},tabTextOn:{color:"#190E21"},add:{flexDirection:"row",gap:8,marginTop:15},input:{flex:1,minHeight:48,borderRadius:15,borderWidth:1,borderColor:"#303746",backgroundColor:"#101620",paddingHorizontal:14,color:"#F4EEF8",fontSize:14},addBtn:{width:48,height:48,borderRadius:15,backgroundColor:"#C9A4F4",alignItems:"center",justifyContent:"center"},from:{color:"#9C86B4",fontSize:9,fontWeight:"900",letterSpacing:1,marginTop:8},weekHead:{flexDirection:"row",marginTop:14,gap:3},weekDay:{flex:1,minHeight:38,borderRadius:9,backgroundColor:"#121923",alignItems:"center",justifyContent:"center"},weekText:{fontSize:8,fontWeight:"800",color:"#9AA6B5"},task:{minHeight:72,borderRadius:18,borderWidth:1,borderColor:"#293240",backgroundColor:"#0F151E",padding:13,marginTop:10,flexDirection:"row",alignItems:"center",gap:11},taskTitle:{color:"#F1EBF5",fontSize:13,fontWeight:"800"},done:{textDecorationLine:"line-through",color:"#788391"},meta:{fontSize:9,color:"#748193",marginTop:5},empty:{alignItems:"center",padding:30,marginTop:20},emptyTitle:{color:"#EAE2EF",fontWeight:"900",marginTop:10},emptyText:{color:"#788596",fontSize:10,marginTop:5}});
