import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useAppConfig } from "../context/AppConfigContext";

export default function TermsScreen(){const router=useRouter();const{settings}=useAppConfig();return <View style={s.root}><LinearGradient colors={["#151020","#080D14"]} style={StyleSheet.absoluteFill}/><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color="#FFF"/></Pressable><Text style={s.title}>Terms</Text></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text style={s.updated}>Study Arc · in-app terms summary</Text><Section title="Study tool, not a result guarantee">Study Arc provides planning, timing, progress and readiness tools. Readiness percentages are estimates based on recorded Study Arc activity and do not guarantee or predict an examination grade.</Section><Section title="Your account">Keep your login credentials private and provide accurate study/exam information where it affects planning. Public sign-up creates a student account; administrative access is granted only through protected role controls.</Section><Section title="Plans and access">When Paid Mode is enabled, some accounts may require an active plan. Plan names, prices, duration and availability may be changed by Study Arc administration. Existing-user/grandfathering rules are determined by the active access policy.</Section><Section title="Manual payments">When manual bank payment is available, use the payment reference shown by Study Arc and submit genuine proof of payment. Premium is activated only after valid approval or successful activation-code redemption.</Section><Section title="Account restrictions">Study Arc may restrict an account for abuse, fraud, security concerns or violations of these terms. A blocked account cannot enter normal app features even if a subscription is active. Contact support if you believe a restriction is incorrect.</Section><Section title="Data and deletion">You may export data, clear study history or permanently delete the account using the available data controls. Permanent deletion cannot be undone.</Section><Section title="Changes and availability">Features, planner logic, pricing, academic content and service availability may change as Study Arc is improved. Important changes should be communicated in-app where appropriate.</Section><Section title="Support">Questions about these terms can be sent to {settings.contactEmail}.</Section></ScrollView></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text><Text style={s.text}>{children}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},head:{padding:18,paddingTop:22,flexDirection:"row",alignItems:"center",gap:11},back:{width:43,height:43,borderRadius:14,backgroundColor:"#151B25",alignItems:"center",justifyContent:"center"},title:{color:"#F5F6F8",fontSize:22,fontWeight:"900"},content:{padding:20,paddingBottom:50,maxWidth:720,width:"100%",alignSelf:"center"},updated:{color:"#8B78A0",fontSize:9,fontWeight:"900",letterSpacing:1,marginBottom:10},card:{borderRadius:17,backgroundColor:"#101720",borderWidth:1,borderColor:"#293646",padding:14,marginBottom:8},cardTitle:{color:"#E8EBEF",fontSize:11.5,fontWeight:"900"},text:{color:"#748194",fontSize:10,lineHeight:17,marginTop:6}})
