import {Ionicons} from "@expo/vector-icons";
import {useRouter} from "expo-router";
import React,{useState} from "react";
import {Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from "react-native";
import {useAppTheme} from "../context/AppThemeContext";
import {APP_THEMES} from "../lib/appTheme";
export default function ThemeSettings(){
 const router=useRouter();const {theme,setTheme,saving}=useAppTheme();const [error,setError]=useState<string|null>(null);
 return <SafeAreaView style={[s.root,{backgroundColor:theme.background}]}><View style={s.head}><Pressable accessibilityLabel="Back" onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={22} color="#FFF"/></Pressable><View><Text style={s.title}>App colour theme</Text><Text style={s.help}>Choose the main colour across StudyArc.</Text></View></View><ScrollView contentContainerStyle={s.content}><View style={[s.preview,{backgroundColor:theme.surface,borderColor:theme.accent+"70"}]}><Text style={s.title}>Your StudyArc</Text><Text style={s.help}>Buttons, highlights and page backgrounds</Text><View style={[s.sample,{backgroundColor:theme.accent}]}><Ionicons name="play" size={18} color="#0A1320"/><Text style={s.sampleText}>Start studying</Text></View><View style={s.bar}><View style={{height:7,width:"65%",backgroundColor:theme.accent,borderRadius:5}}/></View></View><View style={s.options}>{APP_THEMES.map(option=><Pressable key={option.id} accessibilityRole="radio" accessibilityState={{selected:theme.id===option.id,disabled:saving}} disabled={saving} onPress={async()=>{setError(null);try{await setTheme(option.id)}catch{setError("Could not save this theme. Please try again.")}}} style={[s.option,{backgroundColor:option.surface,borderColor:theme.id===option.id?option.accent:"#344354"}]}><View style={[s.swatch,{backgroundColor:option.accent}]}/><Text style={[s.optionName,{flex:1}]}>{option.name}</Text>{theme.id===option.id&&<Ionicons name="checkmark-circle" size={24} color={option.accent}/>}</Pressable>)}</View>{error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<Text accessibilityLiveRegion="polite" style={s.help}>{saving?"Saving theme…":"Saved on this device. You can change it anytime."}</Text><Text style={s.help}>Subject colours and result indicators stay recognisable. Purchased store themes remain available.</Text></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1},head:{padding:18,flexDirection:"row",alignItems:"center",gap:12},back:{width:42,height:42,borderRadius:14,backgroundColor:"#1C2735",alignItems:"center",justifyContent:"center"},title:{fontSize:23,fontWeight:"800",color:"#F4F6FA"},help:{fontSize:13,color:"#A8B6C8",lineHeight:20,marginTop:5},content:{padding:18,maxWidth:760,width:"100%",alignSelf:"center",gap:16},preview:{padding:22,borderWidth:1,borderRadius:23},sample:{marginTop:18,minHeight:48,paddingHorizontal:18,borderRadius:14,alignSelf:"flex-start",flexDirection:"row",alignItems:"center",gap:8},sampleText:{fontSize:14,fontWeight:"800",color:"#0A1320"},bar:{height:7,marginTop:20,backgroundColor:"#FFFFFF18",borderRadius:5,overflow:"hidden"},options:{gap:10},option:{minHeight:70,padding:15,borderRadius:18,borderWidth:1,flexDirection:"row",alignItems:"center",gap:12},swatch:{width:35,height:35,borderRadius:12},optionName:{color:"#F4F6FA",fontSize:16,fontWeight:"700"},error:{fontSize:13,color:"#FFA8B3"}});
