import {useThemeRefresh} from "../context/AppThemeContext";
import {createThemeStyles} from "../lib/themeStyles";
import {appColor} from "../lib/appTheme";
import {Ionicons} from "@expo/vector-icons";
import {useRouter} from "expo-router";
import React,{useMemo} from "react";
import {Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import {useAcademic} from "../context/AcademicContext";
import {useTaskPlanning} from "../context/TaskPlanningContext";
import {subjectDisplayName} from "../lib/subjectDisplay";

const at=(date:string,time:string|null)=>new Date(date+"T"+(time&&/^\d{2}:\d{2}$/.test(time)?time:"18:00")+":00");
const time=(d:Date)=>d.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"});
const dayLabel=(d:Date)=>{const now=new Date(),a=d.toDateString(),b=now.toDateString();if(a===b)return"TODAY";const t=new Date(now);t.setDate(t.getDate()+1);if(a===t.toDateString())return"TOMORROW";return d.toLocaleDateString(undefined,{weekday:"short",day:"numeric",month:"short"}).toUpperCase()};

export default function AssignmentTimetableStrip(){
 useThemeRefresh();
 const router=useRouter();const{assignments}=useAcademic();const{tasks}=useTaskPlanning();
 const rows=useMemo(()=>tasks.filter(t=>!t.completed&&t.plannedDate&&t.plannedTime).map(task=>{const start=at(task.plannedDate!,task.plannedTime),end=new Date(start.getTime()+Math.max(5,task.estimatedMinutes)*60000),assignment=task.assignmentId?assignments.find(a=>a.id===task.assignmentId):null;return{task,start,end,assignment}}).filter(x=>x.end.getTime()>=Date.now()-86400000).sort((a,b)=>a.start.getTime()-b.start.getTime()).slice(0,16),[assignments,tasks]);
 if(!rows.length)return null;
 const start=(row:typeof rows[number])=>{if(row.assignment)router.push({pathname:"/stopwatch",params:{subjectName:row.assignment.subjectName,topicName:row.assignment.topicName??"General",studyType:"Study Session",assignmentId:row.assignment.id,assignmentTitle:row.assignment.title,goalText:"Make progress on "+row.assignment.title}});else router.push("/tasks")};
 return <View style={s.root}><View style={s.head}><View style={s.headIcon}><Ionicons name="calendar-outline" size={17} color="#79DCA2"/></View><View style={{flex:1}}><Text style={s.title}>Tasks in your timetable</Text><Text style={s.sub}>Scheduled Tasks and assignments appear here using the date and time from your Tasks planner.</Text></View><Pressable onPress={()=>router.push("/tasks")}><Text style={s.manage}>MANAGE</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.list}>{rows.map(row=><View key={row.task.id} style={s.card}><View style={s.cardTop}><Text style={s.when}>{dayLabel(row.start)}</Text><Text style={s.timeText}>{time(row.start)}–{time(row.end)}</Text></View><View style={s.timeline}><View style={s.dot}/><View style={s.bar}/><View style={s.dot}/></View><Text style={s.name} numberOfLines={1}>{row.task.title}</Text><Text style={s.subject} numberOfLines={1}>{row.assignment?subjectDisplayName(row.assignment.subjectName)+" · Assignment":"Task"}</Text><View style={s.bottom}><Text style={s.duration}>{row.task.estimatedMinutes} min</Text><Pressable onPress={()=>start(row)} style={s.start}><Ionicons name="play" size={11} color={appColor("#160B20")}/><Text style={s.startText}>{row.assignment?"START":"OPEN"}</Text></Pressable></View></View>)}</ScrollView></View>
}
const s=createThemeStyles({root:{backgroundColor:"#0C1219",borderBottomWidth:1,borderBottomColor:"#263442",paddingTop:8,paddingBottom:10},head:{paddingHorizontal:12,flexDirection:"row",alignItems:"center",gap:8},headIcon:{width:34,height:34,borderRadius:11,backgroundColor:"#65D79A13",alignItems:"center",justifyContent:"center"},title:{color:"#E4E9EE",fontSize:10.5,fontWeight:"900"},sub:{color:"#697789",fontSize:7.8,lineHeight:12,marginTop:2},manage:{color:"#B995E5",fontSize:8.5,fontWeight:"900"},list:{paddingHorizontal:12,paddingTop:8,gap:8},card:{width:220,minHeight:116,borderRadius:15,backgroundColor:"#111923",borderWidth:1,borderColor:"#2C3A48",padding:10},cardTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:7},when:{color:"#67C98E",fontSize:7.4,fontWeight:"900",letterSpacing:.7},timeText:{color:"#B9C4D0",fontSize:8,fontWeight:"900"},timeline:{height:14,flexDirection:"row",alignItems:"center",marginTop:6},dot:{width:7,height:7,borderRadius:4,backgroundColor:"#79DCA2"},bar:{flex:1,height:4,borderRadius:4,backgroundColor:"#2F7650",marginHorizontal:4},name:{color:"#EDF0F4",fontSize:10.5,fontWeight:"900",marginTop:3},subject:{color:"#718093",fontSize:7.8,marginTop:3},bottom:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:8},duration:{color:"#8E9AA7",fontSize:7.8,fontWeight:"800"},start:{height:28,borderRadius:9,backgroundColor:"#B784FF",paddingHorizontal:9,flexDirection:"row",alignItems:"center",gap:4},startText:{color:"#160B20",fontSize:6.8,fontWeight:"900"}});