import {useThemeRefresh} from "../context/AppThemeContext";
import {createThemeStyles} from "../lib/themeStyles";
import React from "react";
import {Pressable,StyleSheet,Text,View} from "react-native";
import type {TrackerQuestion} from "../lib/pastPaperTracker";
export const questionKey=(q:TrackerQuestion)=>q.kind+":"+q.itemKey;
export default function PastPaperQuestionGrid({questions,accent,selected,onPress,disabled=false,attempts,groupActions}:{questions:TrackerQuestion[];accent:string;selected:(q:TrackerQuestion)=>boolean;onPress:(q:TrackerQuestion)=>void;disabled?:boolean;attempts?:(q:TrackerQuestion)=>number;groupActions?:(questions:TrackerQuestion[])=>void}){
 useThemeRefresh();
 const groups=[...new Set(questions.map(q=>q.kind))];
 return <View style={{gap:14}}>{groups.map(kind=>{const group=questions.filter(q=>q.kind===kind);return <View key={kind}><View style={s.head}><Text style={s.label}>{kind==="Legacy"?"Legacy paper":kind}</Text>{groupActions&&<Pressable disabled={disabled} accessibilityRole="button" onPress={()=>groupActions(group)} style={s.select}><Text style={{color:accent,fontSize:12,fontWeight:"700"}}>Select all</Text></Pressable>}</View><View style={s.grid}>{group.map(q=>{const on=selected(q),count=attempts?.(q)??0;return <Pressable key={questionKey(q)} accessibilityRole="button" accessibilityState={{selected:on,disabled}} accessibilityLabel={`${q.kind} question ${q.number}${count?`, ${count} attempts`:""}`} disabled={disabled} onPress={()=>onPress(q)} style={[s.question,on&&{backgroundColor:accent+"28",borderColor:accent},disabled&&{opacity:.6}]}><Text style={[s.number,on&&{color:accent}]}>{q.number}</Text>{on&&<Text style={[s.check,{color:accent}]}>✓</Text>}{count>1&&<Text style={[s.repeat,{color:accent}]}>×{count}</Text>}</Pressable>})}</View></View>})}</View>
}
const s=createThemeStyles({head:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:6},label:{color:"#B9C7D8",fontSize:12,fontWeight:"700"},select:{minHeight:36,justifyContent:"center",paddingHorizontal:6},grid:{flexDirection:"row",flexWrap:"wrap",gap:8},question:{width:54,height:54,borderRadius:13,borderWidth:1,borderColor:"#34465A",backgroundColor:"#162230",alignItems:"center",justifyContent:"center"},number:{color:"#E0E7F0",fontSize:17,fontWeight:"700"},check:{position:"absolute",right:4,top:1,fontSize:12},repeat:{fontSize:10,fontWeight:"700"}});
