import{Ionicons}from"@expo/vector-icons";
import{useRouter}from"expo-router";
import React,{useMemo}from"react";
import{Pressable,StyleSheet,Text,View}from"react-native";
import{useAcademic}from"../context/AcademicContext";
import{useAssignmentEnhancements}from"../context/AssignmentEnhancementsContext";
import{useScheduleAdjustments}from"../context/ScheduleAdjustmentsContext";
import{useStudent}from"../context/StudentContext";
import{format12Hour}from"../lib/time";
const DAYS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],TASK_PREFIX="__REPETITIVE_TASK__:";
const startOfWeek=(d=new Date())=>{const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-x.getDay());return x};
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
export default function WeeklyWorkloadBoard(){
 const router=useRouter(),{assignments}=useAcademic(),{priorities}=useAssignmentEnhancements(),{protectedTimes}=useScheduleAdjustments(),{classes}=useStudent();
 const weekStart=useMemo(()=>startOfWeek(),[]),weekEnd=useMemo(()=>addDays(weekStart,7),[weekStart]);
 const assignmentRows=useMemo(()=>assignments.filter(x=>!x.completed).filter(x=>!x.dueAt||new Date(x.dueAt).getTime()<weekEnd.getTime()).sort((a,b)=>(priorities[a.id]??1000)-(priorities[b.id]??1000)||(a.dueAt??"9999").localeCompare(b.dueAt??"9999")),[assignments,priorities,weekEnd]);
 const repetitive=protectedTimes.filter(x=>(x.recurrence==="Daily"||x.recurrence==="Weekly")&&x.title.startsWith(TASK_PREFIX)).sort((a,b)=>a.recurrence.localeCompare(b.recurrence)||a.dayOfWeek-b.dayOfWeek||a.startTime.localeCompare(b.startTime));
 const classWork=classes.flatMap(c=>[{id:`homework-${c.id}`,title:`${c.subjectName} homework`,sub:`${DAYS[(c.dayOfWeek+1)%7]} · 3 hours`,icon:"school-outline" as const,color:"#F0B477"},...((c.classType==="Paper"||c.classType==="Paper Discussion")?[{id:`paper-${c.id}`,title:`${c.subjectName} Paper Review`,sub:`${DAYS[(c.dayOfWeek+2)%7]} · 2 hours`,icon:"documents-outline" as const,color:"#D4A6F6"}]:[]) ]);
 const repeating=[...repetitive.map(x=>({id:x.id,title:x.title.slice(TASK_PREFIX.length),sub:`${x.recurrence==="Daily"?"Every day":DAYS[x.dayOfWeek]} · ${format12Hour(x.startTime)}–${format12Hour(x.endTime)}`,icon:"repeat-outline" as const,color:"#8FB9F4"})),...classWork,{id:"day-review",title:"Review the day",sub:"Every day · 30 min before wind-down",icon:"moon-outline" as const,color:"#82D0A0"}];
 const assignmentMinutes=assignmentRows.reduce((sum,x)=>sum+x.estimatedMinutes,0),fixedMinutes=classes.length*180+classes.filter(c=>c.classType==="Paper"||c.classType==="Paper Discussion").length*120;
 return <View style={s.root}>
  <View style={s.summary}><Metric value={assignmentRows.length} label="OPEN ASSIGNMENTS" icon="clipboard-outline" color="#82D0A0"/><Metric value={`${Math.round(assignmentMinutes/60*10)/10}h`} label="ASSIGNMENT LOAD" icon="time-outline" color="#F0B477"/><Metric value={`${Math.round(fixedMinutes/60*10)/10}h`} label="CLASS FOLLOW-UP" icon="school-outline" color="#AFA0F3"/></View>
  <View style={s.sectionHead}><View><Text style={s.sectionTitle}>Assignments</Text><Text style={s.sectionSub}>Your drag priority is used first, then deadline urgency.</Text></View><Pressable onPress={()=>router.push("/assignment")} style={s.open}><Text style={s.openText}>Open</Text><Ionicons name="arrow-forward" size={15} color="#D9C3F2"/></Pressable></View>
  <View style={s.card}>{assignmentRows.length?assignmentRows.map((a,index)=><View key={a.id} style={s.row}><View style={s.rank}><Text style={s.rankText}>{index+1}</Text></View><View style={{flex:1}}><Text style={s.rowTitle}>{a.title}</Text><Text style={s.rowSub}>{a.subjectName} · {a.estimatedMinutes} min{a.dueAt?` · due ${new Date(a.dueAt).toLocaleDateString(undefined,{weekday:"short",day:"numeric",month:"short"})}`:" · no deadline"}</Text></View></View>):<Text style={s.empty}>No open assignments this week.</Text>}</View>
  <View style={s.sectionHead}><View><Text style={s.sectionTitle}>Repeating & class work</Text><Text style={s.sectionSub}>Daily tasks, weekly tasks, class homework, paper review and day review.</Text></View><Pressable onPress={()=>router.push("/classes")} style={s.open}><Text style={s.openText}>Classes</Text><Ionicons name="arrow-forward" size={15} color="#D9C3F2"/></Pressable></View>
  <View style={s.card}>{repeating.map(x=><View key={x.id} style={s.row}><View style={[s.icon,{backgroundColor:x.color+"18"}]}><Ionicons name={x.icon} size={18} color={x.color}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{x.title}</Text><Text style={s.rowSub}>{x.sub}</Text></View></View>)}</View>
 </View>
}
function Metric({value,label,icon,color}:{value:string|number;label:string;icon:keyof typeof Ionicons.glyphMap;color:string}){return <View style={s.metric}><View style={[s.metricIcon,{backgroundColor:color+"18"}]}><Ionicons name={icon} size={18} color={color}/></View><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({root:{gap:10},summary:{flexDirection:"row",gap:7},metric:{flex:1,minHeight:92,borderRadius:18,backgroundColor:"#111923",borderWidth:1,borderColor:"#293646",padding:10,justifyContent:"center"},metricIcon:{width:34,height:34,borderRadius:11,alignItems:"center",justifyContent:"center"},metricValue:{color:"#EEF1F4",fontSize:18,fontWeight:"900",marginTop:7},metricLabel:{color:"#758294",fontSize:8,fontWeight:"900",marginTop:2},sectionHead:{marginTop:8,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},sectionTitle:{color:"#F0ECF4",fontSize:16,fontWeight:"900"},sectionSub:{color:"#748193",fontSize:10.5,lineHeight:16,marginTop:3},open:{minHeight:38,borderRadius:12,backgroundColor:"#21182D",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:4},openText:{color:"#D9C3F2",fontSize:10,fontWeight:"900"},card:{borderRadius:19,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#293646",paddingHorizontal:11},row:{minHeight:62,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:"#202B36",paddingVertical:9},rank:{width:34,height:34,borderRadius:11,backgroundColor:"#26311F",alignItems:"center",justifyContent:"center"},rankText:{color:"#A9D3B5",fontSize:12,fontWeight:"900"},icon:{width:38,height:38,borderRadius:12,alignItems:"center",justifyContent:"center"},rowTitle:{color:"#DDE3E9",fontSize:12.5,fontWeight:"900"},rowSub:{color:"#748193",fontSize:10,lineHeight:14,marginTop:3},empty:{color:"#657385",fontSize:11,paddingVertical:18,textAlign:"center"}});
