import React,{createContext,useCallback,useContext,useEffect,useMemo,useState}from"react";
import{SUBJECTS,type SubjectConfig,type TopicConfig,type StudyMedium}from"../data/subjects";
import{paperComponentsForSubject}from"../data/alStreams";
import{cacheKey,readJson,writeJson}from"../lib/offlineStore";
import{setRuntimeSubjectLabels}from"../lib/subjectDisplay";
import{supabase}from"../lib/supabase";
import{useAuth}from"./AuthContext";
import{useOffline}from"./OfflineContext";

export type CatalogSubject={subjectName:string;displayNameEn:string;displayNameSi:string|null;displayNameTa:string|null;streams:string[];paperComponents:string[];enabled:boolean;sourceLabel:string;sourceUrl:string;verificationStatus:"verified"|"needs_review"|"draft";verifiedAt:string|null};
export type CatalogTopic={id:string;subjectName:string;topicKey:string;titleEn:string;titleSi:string|null;titleTa:string|null;unitName:string|null;sortOrder:number;enabled:boolean;sourceLabel:string;sourceUrl:string;verificationStatus:"verified"|"needs_review"|"draft";verifiedAt:string|null};
export type CatalogSubtopic={id:string;subjectName:string;topicKey:string;subtopicKey:string;titleEn:string;titleSi:string|null;titleTa:string|null;sortOrder:number;enabled:boolean;sourceLabel:string;sourceUrl:string;verificationStatus:"verified"|"needs_review"|"draft";verifiedAt:string|null};
type Cache={subjects:CatalogSubject[];topics:CatalogTopic[];subtopics:CatalogSubtopic[]};
type Value=Cache&{loading:boolean;refreshCatalog:()=>Promise<void>;paperComponentsFor:(subjectName:string)=>string[];displayNameFor:(subjectName:string,medium?:StudyMedium)=>string};
const CatalogContext=createContext<Value|null>(null);
const EMPTY:Cache={subjects:[],topics:[],subtopics:[]};

const palette=[["#B784FF","#7651B4"],["#63B8FF","#2A7DD0"],["#65D79A","#2B9D67"],["#FF9AAE","#CC536E"],["#F0BE6B","#B77A28"],["#48D6D2","#168C91"],["#A5A9FF","#6168C9"],["#E79AEF","#A84BB4"]]as const;
function hash(value:string){let h=0;for(let i=0;i<value.length;i++)h=(h*31+value.charCodeAt(i))>>>0;return h}
function ensureSubject(subjectName:string):SubjectConfig{const map=SUBJECTS as unknown as Record<string,SubjectConfig>;if(map[subjectName])return map[subjectName];const[color,accent]=palette[hash(subjectName)%palette.length];map[subjectName]={icon:"book-open-page-variant",color,accent,topics:[]};return map[subjectName]}
function toTopic(row:CatalogTopic,subtopics:CatalogSubtopic[]):TopicConfig{const allRows=subtopics.filter(x=>x.subjectName===row.subjectName&&x.topicKey===row.topicKey).sort((a,b)=>a.sortOrder-b.sortOrder||a.titleEn.localeCompare(b.titleEn));const enabledRows=allRows.filter(x=>x.enabled);return{id:row.topicKey,title:row.titleEn,sinhala:row.titleSi??row.titleEn,unit:row.unitName??undefined,subtopics:allRows.length?enabledRows.map(x=>x.titleEn):[row.titleEn],subtopicsSinhala:allRows.length?enabledRows.map(x=>x.titleSi??x.titleEn):[row.titleSi??row.titleEn]}}
function applyCatalog(rows:CatalogTopic[],subtopics:CatalogSubtopic[]){const grouped=new Map<string,CatalogTopic[]>();for(const row of rows){const list=grouped.get(row.subjectName)??[];list.push(row);grouped.set(row.subjectName,list)}for(const[subjectName,list]of grouped){const subject=ensureSubject(subjectName);const ordered=[...list].filter(x=>x.enabled).sort((a,b)=>a.sortOrder-b.sortOrder||a.titleEn.localeCompare(b.titleEn));subject.topics=ordered.map(row=>toTopic(row,subtopics))}}
function applySubjectLabels(rows:CatalogSubject[]){setRuntimeSubjectLabels(rows.map(row=>({subjectName:row.subjectName,displayNameEn:row.displayNameEn})))}

export function AcademicCatalogProvider({children}:{children:React.ReactNode}){
 const{user,loading:authLoading}=useAuth();const{isOnline,syncTick}=useOffline();const[subjects,setSubjects]=useState<CatalogSubject[]>([]),[topics,setTopics]=useState<CatalogTopic[]>([]),[subtopics,setSubtopics]=useState<CatalogSubtopic[]>([]),[loading,setLoading]=useState(true);
 const loadCache=useCallback(async()=>{if(!user){setSubjects([]);setTopics([]);setSubtopics([]);setRuntimeSubjectLabels([]);setLoading(false);return}const cached=await readJson<Cache>(cacheKey(user.id,"academic-catalog"),EMPTY);setSubjects(cached.subjects??[]);setTopics(cached.topics??[]);setSubtopics(cached.subtopics??[]);applySubjectLabels(cached.subjects??[]);applyCatalog(cached.topics??[],cached.subtopics??[]);setLoading(false)},[user]);
 const refreshCatalog=useCallback(async()=>{if(!user)return;if(!isOnline){await loadCache();return}try{const[sr,tr,subr]=await Promise.all([supabase.from("academic_subject_catalog").select("*").eq("enabled",true).order("subject_name"),supabase.from("academic_topic_catalog").select("*").order("subject_name").order("sort_order"),supabase.from("academic_subtopic_catalog").select("*").order("subject_name").order("topic_key").order("sort_order")]);if(sr.error||tr.error||subr.error)throw sr.error??tr.error??subr.error;const nextSubjects:CatalogSubject[]=(sr.data??[]).map((r:any)=>({subjectName:r.subject_name,displayNameEn:r.display_name_en||r.subject_name,displayNameSi:r.display_name_si??null,displayNameTa:r.display_name_ta??null,streams:r.streams??[],paperComponents:r.paper_components??paperComponentsForSubject(r.subject_name),enabled:Boolean(r.enabled),sourceLabel:r.source_label,sourceUrl:r.source_url,verificationStatus:r.verification_status,verifiedAt:r.verified_at}));const nextTopics:CatalogTopic[]=(tr.data??[]).map((r:any)=>({id:r.id,subjectName:r.subject_name,topicKey:r.topic_key,titleEn:r.title_en,titleSi:r.title_si,titleTa:r.title_ta,unitName:r.unit_name,sortOrder:Number(r.sort_order??0),enabled:Boolean(r.enabled),sourceLabel:r.source_label,sourceUrl:r.source_url,verificationStatus:r.verification_status,verifiedAt:r.verified_at}));const nextSubtopics:CatalogSubtopic[]=(subr.data??[]).map((r:any)=>({id:r.id,subjectName:r.subject_name,topicKey:r.topic_key,subtopicKey:r.subtopic_key,titleEn:r.title_en,titleSi:r.title_si,titleTa:r.title_ta,sortOrder:Number(r.sort_order??0),enabled:Boolean(r.enabled),sourceLabel:r.source_label,sourceUrl:r.source_url,verificationStatus:r.verification_status,verifiedAt:r.verified_at}));setSubjects(nextSubjects);setTopics(nextTopics);setSubtopics(nextSubtopics);applySubjectLabels(nextSubjects);applyCatalog(nextTopics,nextSubtopics);await writeJson(cacheKey(user.id,"academic-catalog"),{subjects:nextSubjects,topics:nextTopics,subtopics:nextSubtopics})}catch{await loadCache()}finally{setLoading(false)}},[isOnline,loadCache,user]);
 useEffect(()=>{if(!authLoading)loadCache().then(()=>refreshCatalog())},[authLoading,loadCache,refreshCatalog]);useEffect(()=>{if(user&&isOnline)refreshCatalog()},[isOnline,refreshCatalog,syncTick,user]);
 const paperComponentsFor=useCallback((subjectName:string)=>subjects.find(x=>x.subjectName===subjectName)?.paperComponents??paperComponentsForSubject(subjectName),[subjects]);
 const displayNameFor=useCallback((subjectName:string,medium:StudyMedium="English")=>{const row=subjects.find(x=>x.subjectName===subjectName);if(!row)return subjectName;return medium==="Sinhala"?(row.displayNameSi||row.displayNameEn||subjectName):(row.displayNameEn||subjectName)},[subjects]);
 const value=useMemo<Value>(()=>({subjects,topics,subtopics,loading,refreshCatalog,paperComponentsFor,displayNameFor}),[displayNameFor,loading,paperComponentsFor,refreshCatalog,subjects,subtopics,topics]);
 return <CatalogContext.Provider value={value}>{children}</CatalogContext.Provider>
}
export function useAcademicCatalog(){const value=useContext(CatalogContext);if(!value)throw new Error("useAcademicCatalog must be used inside AcademicCatalogProvider.");return value}