import React,{createContext,useCallback,useContext,useEffect,useMemo,useState}from"react";
import{setRuntimeAssignmentPriorities}from"../lib/assignmentPriorityRuntime";
import{cacheKey,makeUuid,readJson,writeJson}from"../lib/offlineStore";
import{supabase}from"../lib/supabase";
import{useAuth}from"./AuthContext";
import{useOffline}from"./OfflineContext";

export type AssignmentSubtask={id:string;assignmentId:string;title:string;completed:boolean;sortOrder:number};
type Cache={progress:Record<string,number>;subtasks:AssignmentSubtask[];priorities:Record<string,number>;priorityDirty:boolean};
const EMPTY:Cache={progress:{},subtasks:[],priorities:{},priorityDirty:false};
type Value={progress:Record<string,number>;subtasks:AssignmentSubtask[];priorities:Record<string,number>;loading:boolean;refresh:()=>Promise<void>;setProgress:(assignmentId:string,progress:number)=>Promise<void>;addSubtask:(assignmentId:string,title:string)=>Promise<string>;toggleSubtask:(id:string,completed:boolean)=>Promise<void>;deleteSubtask:(id:string)=>Promise<void>;setPriorityOrder:(assignmentIds:string[])=>Promise<void>};
const Ctx=createContext<Value|null>(null);

export function AssignmentEnhancementsProvider({children}:{children:React.ReactNode}){
 const{user}=useAuth();const{isOnline,syncTick}=useOffline();const[state,setState]=useState<Cache>(EMPTY);const[loading,setLoading]=useState(true);
 setRuntimeAssignmentPriorities(state.priorities);
 const persist=useCallback(async(next:Cache)=>{if(user)await writeJson(cacheKey(user.id,"assignment-enhancements-v2"),next)},[user]);
 const loadCache=useCallback(async()=>{if(!user){setState(EMPTY);setLoading(false);return}const v2=await readJson<Cache|null>(cacheKey(user.id,"assignment-enhancements-v2"),null);if(v2){const next={...EMPTY,...v2};setState(next);setRuntimeAssignmentPriorities(next.priorities);setLoading(false);return}const old=await readJson<{progress:Record<string,number>;subtasks:AssignmentSubtask[]}>(cacheKey(user.id,"assignment-enhancements-v1"),{progress:{},subtasks:[]});const next={...EMPTY,...old};setState(next);setRuntimeAssignmentPriorities({});await persist(next);setLoading(false)},[persist,user]);
 const pushPriorities=useCallback(async(priorities:Record<string,number>)=>{if(!user||!isOnline)return false;const rows=Object.entries(priorities);if(!rows.length)return true;const results=await Promise.all(rows.map(([id,rank])=>supabase.from("assignments").update({priority_rank:rank,updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id)));return results.every(x=>!x.error)},[isOnline,user]);
 const refresh=useCallback(async()=>{if(!user){setState(EMPTY);setLoading(false);return}if(!isOnline){await loadCache();return}setLoading(true);try{let local=await readJson<Cache>(cacheKey(user.id,"assignment-enhancements-v2"),state);if(local.priorityDirty){const ok=await pushPriorities(local.priorities);if(ok){local={...local,priorityDirty:false};await persist(local)}}const[a,s]=await Promise.all([supabase.from("assignments").select("id,progress_percent,priority_rank").eq("user_id",user.id),supabase.from("assignment_subtasks").select("id,assignment_id,title,completed,sort_order").eq("user_id",user.id).order("sort_order")]);if(a.error)throw a.error;if(s.error)throw s.error;const progress=Object.fromEntries((a.data??[]).map((x:any)=>[x.id,Number(x.progress_percent??0)]));const priorities=Object.fromEntries((a.data??[]).map((x:any)=>[x.id,Number(x.priority_rank??1000)]));const subtasks=(s.data??[]).map((x:any)=>({id:x.id,assignmentId:x.assignment_id,title:x.title,completed:Boolean(x.completed),sortOrder:Number(x.sort_order??0)}));const next:Cache={progress,subtasks,priorities,priorityDirty:false};setState(next);setRuntimeAssignmentPriorities(priorities);await persist(next)}catch{await loadCache()}finally{setLoading(false)}},[isOnline,loadCache,persist,pushPriorities,state,user]);
 useEffect(()=>{loadCache().then(()=>refresh())},[loadCache,refresh]);useEffect(()=>{if(isOnline&&user)refresh()},[isOnline,refresh,syncTick,user]);
 const setPriorityOrder=useCallback(async(ids:string[])=>{if(!user)return;const priorities={...state.priorities};ids.forEach((id,index)=>{priorities[id]=(index+1)*10});let next={...state,priorities,priorityDirty:true};setState(next);setRuntimeAssignmentPriorities(priorities);await persist(next);if(isOnline){const ok=await pushPriorities(priorities);if(ok){next={...next,priorityDirty:false};setState(next);await persist(next)}}},[isOnline,persist,pushPriorities,state,user]);
 const setProgress=useCallback(async(assignmentId:string,value:number)=>{if(!user)return;const progressValue=Math.max(0,Math.min(100,Math.round(value)));const next={...state,progress:{...state.progress,[assignmentId]:progressValue}};setState(next);await persist(next);if(isOnline){const{error}=await supabase.from("assignments").update({progress_percent:progressValue,completed:progressValue>=100,updated_at:new Date().toISOString()}).eq("id",assignmentId).eq("user_id",user.id);if(error)throw error}},[isOnline,persist,state,user]);
 const addSubtask=useCallback(async(assignmentId:string,title:string)=>{if(!user)throw new Error("Sign in first.");const clean=title.trim();if(!clean)throw new Error("Enter a subtask.");const id=makeUuid(),sortOrder=state.subtasks.filter(x=>x.assignmentId===assignmentId).length*10,local={id,assignmentId,title:clean,completed:false,sortOrder};const next={...state,subtasks:[...state.subtasks,local]};setState(next);await persist(next);if(isOnline){const{error}=await supabase.from("assignment_subtasks").insert({id,user_id:user.id,assignment_id:assignmentId,title:clean,completed:false,sort_order:sortOrder});if(error)throw error}return id},[isOnline,persist,state,user]);
 const toggleSubtask=useCallback(async(id:string,completed:boolean)=>{if(!user)return;const row=state.subtasks.find(x=>x.id===id);if(!row)return;const subtasks=state.subtasks.map(x=>x.id===id?{...x,completed}:x),siblings=subtasks.filter(x=>x.assignmentId===row.assignmentId),derived=siblings.length?Math.round(siblings.filter(x=>x.completed).length/siblings.length*100):state.progress[row.assignmentId]??0;const next={...state,subtasks,progress:{...state.progress,[row.assignmentId]:derived}};setState(next);await persist(next);if(isOnline){const[e1,e2]=await Promise.all([supabase.from("assignment_subtasks").update({completed,updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id),supabase.from("assignments").update({progress_percent:derived,completed:derived>=100,updated_at:new Date().toISOString()}).eq("id",row.assignmentId).eq("user_id",user.id)]);if(e1.error||e2.error)throw e1.error??e2.error}},[isOnline,persist,state,user]);
 const deleteSubtask=useCallback(async(id:string)=>{if(!user)return;const row=state.subtasks.find(x=>x.id===id);if(!row)return;const subtasks=state.subtasks.filter(x=>x.id!==id),siblings=subtasks.filter(x=>x.assignmentId===row.assignmentId),derived=siblings.length?Math.round(siblings.filter(x=>x.completed).length/siblings.length*100):state.progress[row.assignmentId]??0;const next={...state,subtasks,progress:{...state.progress,[row.assignmentId]:derived}};setState(next);await persist(next);if(isOnline){await supabase.from("assignment_subtasks").delete().eq("id",id).eq("user_id",user.id);await supabase.from("assignments").update({progress_percent:derived,completed:derived>=100,updated_at:new Date().toISOString()}).eq("id",row.assignmentId).eq("user_id",user.id)}},[isOnline,persist,state,user]);
 const value=useMemo(()=>({progress:state.progress,subtasks:state.subtasks,priorities:state.priorities,loading,refresh,setProgress,addSubtask,toggleSubtask,deleteSubtask,setPriorityOrder}),[addSubtask,deleteSubtask,loading,refresh,setPriorityOrder,setProgress,state.priorities,state.progress,state.subtasks,toggleSubtask]);
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}
export function useAssignmentEnhancements(){const v=useContext(Ctx);if(!v)throw new Error("useAssignmentEnhancements must be used inside provider");return v;}
