import AsyncStorage from "@react-native-async-storage/async-storage";
import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from "react";
import {useAuth} from "./AuthContext";
import {supabase} from "../lib/supabase";

export type PastPaperQuestionStatus="completed"|"incorrect"|"review";
export type PastPaperTick={id:string;subjectName:string;paperYear:number;paperSection:string;itemKey:string;topicName:string|null;status:PastPaperQuestionStatus;attemptNo:number;createdAt:string};
type Value={ticks:PastPaperTick[];loading:boolean;addAttempt:(subjectName:string,paperYear:number,paperSection:string,itemKey:string,topicName?:string|null,status?:PastPaperQuestionStatus)=>Promise<string>;setQuestionStatus:(subjectName:string,paperYear:number,paperSection:string,itemKey:string,status:PastPaperQuestionStatus,topicName?:string|null)=>Promise<void>;removeAttempt:(id:string)=>Promise<void>;isDone:(subjectName:string,paperYear:number,paperSection:string,itemKey:string)=>boolean;latestStatus:(subjectName:string,paperYear:number,paperSection:string,itemKey:string)=>PastPaperQuestionStatus|null;attemptCount:(subjectName:string,paperYear:number,paperSection:string,itemKey:string)=>number;count:(subjectName:string,paperYear:number,paperSection:string)=>number};
const C=createContext<Value|null>(null);
const CACHE="studyarc.pastPaperItemTicks.v2";
const key=(s:string,y:number,p:string,i:string)=>`${s}::${y}::${p}::${i}`;
const uuid=()=>{const c=(globalThis as any).crypto;if(c?.randomUUID)return c.randomUUID();return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,x=>{const r=Math.random()*16|0,v=x==="x"?r:(r&3)|8;return v.toString(16)})};

export function PastPaperTrackerProvider({children}:{children:React.ReactNode}){
 const{user}=useAuth();const[ticks,setTicks]=useState<PastPaperTick[]>([]);const ticksRef=useRef<PastPaperTick[]>([]);const[loading,setLoading]=useState(true);const cacheKey=user?.id?CACHE+"::"+user.id:CACHE+"::signed-out";
 useEffect(()=>{let live=true;ticksRef.current=[];setTicks([]);(async()=>{setLoading(true);try{const raw=await AsyncStorage.getItem(cacheKey);if(raw&&live){const cached=(JSON.parse(raw) as PastPaperTick[]).map(t=>({...t,status:(t.status??"completed") as PastPaperQuestionStatus}));ticksRef.current=cached;setTicks(cached)}}catch{}if(!user?.id){if(live)setLoading(false);return}try{const{data,error}=await supabase.from("past_paper_item_ticks").select("id,subject_name,paper_year,paper_section,item_key,topic_name,status,attempt_no,created_at").order("created_at",{ascending:false});if(error)throw error;const rows=(data??[]).map((r:any)=>({id:r.id,subjectName:r.subject_name,paperYear:r.paper_year,paperSection:r.paper_section,itemKey:r.item_key,topicName:r.topic_name??null,status:(r.status??"completed") as PastPaperQuestionStatus,attemptNo:r.attempt_no??1,createdAt:r.created_at}));if(live){ticksRef.current=rows;setTicks(rows);await AsyncStorage.setItem(cacheKey,JSON.stringify(rows))}}catch{}finally{if(live)setLoading(false)}})();return()=>{live=false}},[cacheKey,user?.id]);
 const persist=useCallback(async(next:PastPaperTick[])=>{ticksRef.current=next;setTicks(next);try{await AsyncStorage.setItem(cacheKey,JSON.stringify(next))}catch{}},[cacheKey]);
 const addAttempt=useCallback(async(subjectName:string,paperYear:number,paperSection:string,itemKey:string,topicName:string|null=null,status:PastPaperQuestionStatus="completed")=>{if(!user?.id)throw new Error("Sign in to save past-paper progress.");const before=ticksRef.current;const same=before.filter(t=>key(t.subjectName,t.paperYear,t.paperSection,t.itemKey)===key(subjectName,paperYear,paperSection,itemKey));const attemptNo=Math.max(0,...same.map(t=>t.attemptNo||1))+1;const local:PastPaperTick={id:uuid(),subjectName,paperYear,paperSection,itemKey,topicName,status,attemptNo,createdAt:new Date().toISOString()};await persist([local,...before]);const{data,error}=await supabase.from("past_paper_item_ticks").insert({user_id:user.id,subject_name:subjectName,paper_year:paperYear,paper_section:paperSection,item_key:itemKey,topic_name:topicName,status,attempt_no:attemptNo}).select("id,attempt_no,created_at").single();if(error){await persist(ticksRef.current.filter(t=>t.id!==local.id));throw error}if(data){const current=ticksRef.current;await persist(current.map(t=>t.id===local.id?{...t,id:data.id,attemptNo:data.attempt_no??attemptNo,createdAt:data.created_at}:t))}return data?.id??local.id},[persist,user?.id]);
 const setQuestionStatus=useCallback(async(subjectName:string,paperYear:number,paperSection:string,itemKey:string,status:PastPaperQuestionStatus,topicName:string|null=null)=>{if(!user?.id)throw new Error("Sign in to save past-paper progress.");const existing=ticksRef.current.find(t=>key(t.subjectName,t.paperYear,t.paperSection,t.itemKey)===key(subjectName,paperYear,paperSection,itemKey));if(!existing){await addAttempt(subjectName,paperYear,paperSection,itemKey,topicName,status);return}const before=ticksRef.current;await persist(before.map(t=>t.id===existing.id?{...t,status,topicName:topicName??t.topicName}:t));const{error}=await supabase.from("past_paper_item_ticks").update({status,topic_name:topicName??existing.topicName}).eq("id",existing.id);if(error){await persist(before);throw error}},[addAttempt,persist,user?.id]);
 const removeAttempt=useCallback(async(id:string)=>{if(!user?.id)throw new Error("Sign in to change past-paper history.");const before=ticksRef.current;const existing=before.find(t=>t.id===id);if(!existing)return;await persist(before.filter(t=>t.id!==id));const{error}=await supabase.from("past_paper_item_ticks").delete().eq("id",id);if(error){await persist(before);throw error}},[persist,user?.id]);
 const grouped=useMemo(()=>{const m=new Map<string,number>();for(const t of ticks){const k=key(t.subjectName,t.paperYear,t.paperSection,t.itemKey);m.set(k,(m.get(k)??0)+1)}return m},[ticks]);
 const isDone=useCallback((s:string,y:number,p:string,i:string)=>(grouped.get(key(s,y,p,i))??0)>0,[grouped]);
 const latestStatus=useCallback((s:string,y:number,p:string,i:string)=>ticks.find(t=>key(t.subjectName,t.paperYear,t.paperSection,t.itemKey)===key(s,y,p,i))?.status??null,[ticks]);
 const attemptCount=useCallback((s:string,y:number,p:string,i:string)=>grouped.get(key(s,y,p,i))??0,[grouped]);
 const count=useCallback((s:string,y:number,p:string)=>new Set(ticks.filter(t=>t.subjectName===s&&t.paperYear===y&&t.paperSection===p).map(t=>t.itemKey)).size,[ticks]);
 const value=useMemo(()=>({ticks,loading,addAttempt,setQuestionStatus,removeAttempt,isDone,latestStatus,attemptCount,count}),[addAttempt,attemptCount,count,isDone,latestStatus,loading,removeAttempt,setQuestionStatus,ticks]);
 return <C.Provider value={value}>{children}</C.Provider>
}
export function usePastPaperTracker(){const v=useContext(C);if(!v)throw new Error("usePastPaperTracker must be used inside PastPaperTrackerProvider");return v}
