import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { cacheKey, readJson, writeJson } from "../lib/offlineStore";
import { supabase } from "../lib/supabase";
import { useAuth } from "./AuthContext";
import { useOffline } from "./OfflineContext";
import { useStudent } from "./StudentContext";
import { useStudy } from "./StudyContext";

export type LeaderboardEntry={userId:string;displayName:string;avatarUrl:string|null;studySeconds:number;rank:number;isMe:boolean};
export type FriendEntry={friendshipId:string;userId:string;displayName:string;avatarUrl:string|null;friendCode:string;isStudying:boolean;subjectName:string|null;topicName:string|null;presenceUpdatedAt:string|null};
export type FriendRequest={friendshipId:string;userId:string;displayName:string;avatarUrl:string|null;friendCode:string};
type FriendshipRow={id:string;requester_id:string;addressee_id:string;status:"pending"|"accepted"|"rejected"};
type SocialCache={leaderboard:LeaderboardEntry[];friends:FriendEntry[];pendingRequests:FriendRequest[];friendships:FriendshipRow[]};
type SocialContextValue={friendCode:string;leaderboard:LeaderboardEntry[];myRank:LeaderboardEntry|null;friends:FriendEntry[];pendingRequests:FriendRequest[];loading:boolean;error:string|null;refreshSocial:()=>Promise<void>;sendFriendRequest:(friendCode:string)=>Promise<string>;acceptFriendRequest:(friendshipId:string)=>Promise<void>;declineFriendRequest:(friendshipId:string)=>Promise<void>;removeFriend:(friendUserId:string)=>Promise<void>;setStudying:(isStudying:boolean,subjectName?:string|null,topicName?:string|null)=>Promise<void>};
const SocialContext=createContext<SocialContextValue|null>(null);
const localDateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const friendCodeFromUserId=(id:string)=>`ARC-${id.replace(/-/g,"").slice(0,8).toUpperCase()}`;
const recentPresence=(x?:string|null)=>!!x&&Date.now()-new Date(x).getTime()<=10*60*1000;

export function SocialProvider({children}:{children:React.ReactNode}){
 const{user}=useAuth();const{isOnline,syncTick}=useOffline();const{profile}=useStudent();const{todaySeconds}=useStudy();
 const[leaderboard,setLeaderboard]=useState<LeaderboardEntry[]>([]);const[friends,setFriends]=useState<FriendEntry[]>([]);const[pendingRequests,setPendingRequests]=useState<FriendRequest[]>([]);const[friendships,setFriendships]=useState<FriendshipRow[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const friendCode=user?friendCodeFromUserId(user.id):"";
 const loadCache=useCallback(async()=>{if(!user)return;const c=await readJson<SocialCache>(cacheKey(user.id,"social"),{leaderboard:[],friends:[],pendingRequests:[],friendships:[]});setLeaderboard(c.leaderboard);setFriends(c.friends.map(f=>({...f,isStudying:false,subjectName:null,topicName:null})));setPendingRequests(c.pendingRequests);setFriendships(c.friendships)},[user]);
 const persist=useCallback(async(l:LeaderboardEntry[],f:FriendEntry[],p:FriendRequest[],r:FriendshipRow[])=>{if(user)await writeJson(cacheKey(user.id,"social"),{leaderboard:l,friends:f,pendingRequests:p,friendships:r} satisfies SocialCache)},[user]);
 const syncMe=useCallback(async()=>{if(!user||!isOnline)return;let{error:e}=await supabase.from("social_profiles").upsert({user_id:user.id,display_name:profile.fullName.trim()||"Student",avatar_url:profile.avatarUrl,friend_code:friendCodeFromUserId(user.id),updated_at:new Date().toISOString()});if(e)throw e;({error:e}=await supabase.from("daily_study_rankings").upsert({user_id:user.id,study_date:localDateKey(),study_seconds:Math.max(0,Math.floor(todaySeconds)),updated_at:new Date().toISOString()},{onConflict:"user_id,study_date"}));if(e)throw e},[isOnline,profile.avatarUrl,profile.fullName,todaySeconds,user]);
 const refreshSocial=useCallback(async()=>{if(!user){setLeaderboard([]);setFriends([]);setPendingRequests([]);setFriendships([]);return}if(!isOnline){await loadCache();setError("Offline · showing cached social information");return}setLoading(true);setError(null);try{await syncMe();const[rankRes,friendRes]=await Promise.all([supabase.from("daily_study_rankings").select("user_id,study_seconds").eq("study_date",localDateKey()).order("study_seconds",{ascending:false}).limit(100),supabase.from("friendships").select("id,requester_id,addressee_id,status").or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`)]);if(rankRes.error)throw rankRes.error;if(friendRes.error)throw friendRes.error;const rows=(friendRes.data??[]) as FriendshipRow[];const ids=new Set<string>((rankRes.data??[]).map((x:any)=>x.user_id));rows.forEach(r=>{ids.add(r.requester_id);ids.add(r.addressee_id)});ids.add(user.id);const idsArray=[...ids];const[profilesRes,presenceRes]=await Promise.all([supabase.from("social_profiles").select("user_id,display_name,avatar_url,friend_code").in("user_id",idsArray),supabase.from("study_presence").select("user_id,is_studying,subject_name,topic_name,updated_at").in("user_id",idsArray)]);if(profilesRes.error)throw profilesRes.error;if(presenceRes.error)throw presenceRes.error;const pm=new Map((profilesRes.data??[]).map((r:any)=>[r.user_id,r]));const sm=new Map((presenceRes.data??[]).map((r:any)=>[r.user_id,r]));const l=(rankRes.data??[]).map((r:any,i:number)=>({userId:r.user_id,displayName:(pm.get(r.user_id) as any)?.display_name||"Student",avatarUrl:(pm.get(r.user_id) as any)?.avatar_url??null,studySeconds:Number(r.study_seconds??0),rank:i+1,isMe:r.user_id===user.id}));const f=rows.filter(r=>r.status==="accepted").map(r=>{const uid=r.requester_id===user.id?r.addressee_id:r.requester_id;const p:any=pm.get(uid);const sp:any=sm.get(uid);const active=Boolean(sp?.is_studying)&&recentPresence(sp?.updated_at);return{friendshipId:r.id,userId:uid,displayName:p?.display_name||"Student",avatarUrl:p?.avatar_url??null,friendCode:p?.friend_code||"",isStudying:active,subjectName:active?sp?.subject_name??null:null,topicName:active?sp?.topic_name??null:null,presenceUpdatedAt:sp?.updated_at??null}}).sort((a,b)=>Number(b.isStudying)-Number(a.isStudying)||a.displayName.localeCompare(b.displayName));const p=rows.filter(r=>r.status==="pending"&&r.addressee_id===user.id).map(r=>{const x:any=pm.get(r.requester_id);return{friendshipId:r.id,userId:r.requester_id,displayName:x?.display_name||"Student",avatarUrl:x?.avatar_url??null,friendCode:x?.friend_code||""}});setLeaderboard(l);setFriends(f);setPendingRequests(p);setFriendships(rows);await persist(l,f,p,rows)}catch{await loadCache();setError("Could not reach Study Arc network. Cached social information is shown.")}finally{setLoading(false)}},[isOnline,loadCache,persist,syncMe,user]);
 useEffect(()=>{loadCache().then(()=>refreshSocial())},[loadCache,refreshSocial]);useEffect(()=>{if(isOnline)refreshSocial()},[isOnline,syncTick,refreshSocial]);
 useEffect(()=>{if(!user||!isOnline)return;const ch=supabase.channel(`study-arc-social-${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"daily_study_rankings"},refreshSocial).on("postgres_changes",{event:"*",schema:"public",table:"friendships"},refreshSocial).on("postgres_changes",{event:"*",schema:"public",table:"study_presence"},refreshSocial).subscribe();return()=>{supabase.removeChannel(ch)}},[isOnline,refreshSocial,user]);
 const requireOnline=()=>{if(!isOnline)throw new Error("This social action needs internet. Your study app still works offline.")};
 const sendFriendRequest=useCallback(async(code:string)=>{requireOnline();if(!user)throw new Error("You must be signed in.");const normalized=code.trim().toUpperCase();if(!normalized)throw new Error("Enter a Study Arc friend code.");const{data:target,error:e}=await supabase.from("social_profiles").select("user_id,display_name").eq("friend_code",normalized).maybeSingle();if(e)throw e;if(!target)throw new Error("No student was found with that friend code.");if(target.user_id===user.id)throw new Error("That is your own friend code.");const existing=friendships.find(r=>(r.requester_id===user.id&&r.addressee_id===target.user_id)||(r.requester_id===target.user_id&&r.addressee_id===user.id));if(existing?.status==="accepted")return`${target.display_name||"Student"} is already your friend.`;if(existing?.status==="pending"&&existing.addressee_id===user.id){const{error}=await supabase.from("friendships").update({status:"accepted",updated_at:new Date().toISOString()}).eq("id",existing.id).eq("addressee_id",user.id);if(error)throw error;await refreshSocial();return`${target.display_name||"Student"} added to your friends.`}if(existing?.status==="pending")return"Friend request already sent.";if(existing)await supabase.from("friendships").delete().eq("id",existing.id);const{error}=await supabase.from("friendships").insert({requester_id:user.id,addressee_id:target.user_id,status:"pending"});if(error)throw error;await refreshSocial();return`Friend request sent to ${target.display_name||"Student"}.`},[friendships,isOnline,refreshSocial,user]);
 const acceptFriendRequest=useCallback(async(id:string)=>{requireOnline();if(!user)return;const{error}=await supabase.from("friendships").update({status:"accepted",updated_at:new Date().toISOString()}).eq("id",id).eq("addressee_id",user.id);if(error)throw error;await refreshSocial()},[isOnline,refreshSocial,user]);
 const declineFriendRequest=useCallback(async(id:string)=>{requireOnline();if(!user)return;const{error}=await supabase.from("friendships").delete().eq("id",id).or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`);if(error)throw error;await refreshSocial()},[isOnline,refreshSocial,user]);
 const removeFriend=useCallback(async(uid:string)=>{requireOnline();if(!user)return;const rel=friendships.find(r=>(r.requester_id===user.id&&r.addressee_id===uid)||(r.requester_id===uid&&r.addressee_id===user.id));if(!rel)return;const{error}=await supabase.from("friendships").delete().eq("id",rel.id);if(error)throw error;await refreshSocial()},[friendships,isOnline,refreshSocial,user]);
 const setStudying=useCallback(async(studying:boolean,subjectName:string|null=null,topicName:string|null=null)=>{if(!user||!isOnline)return;await supabase.from("study_presence").upsert({user_id:user.id,is_studying:studying,subject_name:studying?subjectName:null,topic_name:studying?topicName:null,updated_at:new Date().toISOString()})},[isOnline,user]);
 const myRank=useMemo(()=>leaderboard.find(x=>x.isMe)??null,[leaderboard]);const value=useMemo<SocialContextValue>(()=>({friendCode,leaderboard,myRank,friends,pendingRequests,loading,error,refreshSocial,sendFriendRequest,acceptFriendRequest,declineFriendRequest,removeFriend,setStudying}),[friendCode,leaderboard,myRank,friends,pendingRequests,loading,error,refreshSocial,sendFriendRequest,acceptFriendRequest,declineFriendRequest,removeFriend,setStudying]);return <SocialContext.Provider value={value}>{children}</SocialContext.Provider>;
}
export function useSocial(){const v=useContext(SocialContext);if(!v)throw new Error("useSocial must be used inside SocialProvider.");return v;}
