import React,{createContext,useCallback,useContext,useEffect,useMemo,useState}from"react";
import{cacheKey,enqueueMutation,makeUuid,queuedMutationsFor,readJson,removeQueuedMutation,writeJson}from"../lib/offlineStore";
import{supabase}from"../lib/supabase";
import{useAuth}from"./AuthContext";
import{useOffline}from"./OfflineContext";

export type StudyType="Tute Questions"|"Past Papers"|"Study Session"|"Revision"|"Class"|"Paper Discussion"|"Paper Review"|"Paper Correction";
export type PaperSection="MCQ"|"Essay"|"Full Paper";
export type SavedLap={id:string;number:number;durationMilliseconds:number;totalMilliseconds:number};
export type PastPaperHistory={id:string;subjectName:string;paperYear:number;paperSection:PaperSection;attempts:number};
export type StudySession={id:string;subjectName:string;topicName:string;studyType:StudyType;startedAt:string;durationSeconds:number;focusRating:number|null;understandingRating:number|null;paperYear:number|null;paperSection:PaperSection|null;attemptNo:number|null;sessionNote:string|null;laps:SavedLap[];sourceClassId:string|null;occurrenceKey:string|null};
type NewLap={number:number;duration:number;total:number};
type NewStudySession={subjectName:string;topicName:string;studyType:StudyType;startedAt:string;durationSeconds:number;paperYear?:number|null;paperSection?:PaperSection|null;attemptNo?:number|null;laps?:NewLap[];sourceClassId?:string|null;occurrenceKey?:string|null};
type SessionAnalysis={focusRating?:number|null;understandingRating?:number|null;sessionNote?:string|null};
type Cache={sessions:StudySession[];paperHistory:PastPaperHistory[]};
type Value={sessions:StudySession[];paperHistory:PastPaperHistory[];todaySeconds:number;totalSeconds:number;subjectSeconds:Record<string,number>;topicSeconds:Record<string,number>;loading:boolean;error:string|null;addSession:(s:NewStudySession)=>Promise<string>;updateSessionAnalysis:(id:string,a:SessionAnalysis)=>Promise<void>;updateSessionClassification:(id:string,subjectName:string,topicName:string,studyType?:StudyType)=>Promise<void>;refreshSessions:()=>Promise<void>;deleteSession:(id:string)=>Promise<void>;getPaperAttemptCount:(subject:string,year:number,section?:PaperSection)=>number;addManualPastPaperAttempt:(subject:string,year:number,section:PaperSection)=>Promise<void>;setManualPastPaperAttempts:(subject:string,year:number,section:PaperSection,attempts:number)=>Promise<void>};

const Ctx=createContext<Value|null>(null);const KINDS=["study_session_upsert","study_session_analysis","study_session_reclassify","study_session_delete","paper_history_set"];
const isToday=(iso:string)=>{const d=new Date(iso),n=new Date();return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate()};
const mapSession=(r:any):StudySession=>({id:r.id,subjectName:r.subject_name,topicName:r.topic_name,studyType:r.study_type,startedAt:r.started_at,durationSeconds:Number(r.duration_seconds??0),focusRating:r.focus_rating,understandingRating:r.understanding_rating,paperYear:r.paper_year==null?null:Number(r.paper_year),paperSection:r.paper_section,attemptNo:r.attempt_no==null?null:Number(r.attempt_no),sessionNote:r.session_note,laps:[...(r.study_laps??[])].sort((a:any,b:any)=>a.lap_number-b.lap_number).map((l:any)=>({id:l.id,number:l.lap_number,durationMilliseconds:Number(l.duration_milliseconds),totalMilliseconds:Number(l.total_milliseconds)})),sourceClassId:r.source_class_id??null,occurrenceKey:r.occurrence_key??null});

export function StudyProvider({children}:{children:React.ReactNode}){
 const{user,loading:authLoading}=useAuth();const{isOnline,syncTick}=useOffline();const[sessions,setSessions]=useState<StudySession[]>([]);const[paperHistory,setPaperHistory]=useState<PastPaperHistory[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const persist=useCallback(async(next:StudySession[],hist:PastPaperHistory[])=>{if(user)await writeJson(cacheKey(user.id,"study"),{sessions:next,paperHistory:hist} satisfies Cache)},[user]);
 const loadCache=useCallback(async()=>{if(!user){setSessions([]);setPaperHistory([]);setLoading(false);return}const c=await readJson<Cache>(cacheKey(user.id,"study"),{sessions:[],paperHistory:[]});setSessions(c.sessions??[]);setPaperHistory(c.paperHistory??[]);setLoading(false)},[user]);
 const touchTopic=useCallback(async(subjectName:string,topicName:string,studyType:StudyType)=>{if(!user||subjectName==="Quick Study"||topicName==="General")return;const{data,error}=await supabase.from("topic_progress").select("coverage,knowledge,memory,performance").eq("user_id",user.id).eq("subject_name",subjectName).eq("topic_name",topicName).maybeSingle();if(error)throw error;const now=new Date(),c=data??{coverage:0,knowledge:0,memory:0,performance:0};const isClass=studyType==="Class";const isPaper=["Past Papers","Paper Discussion","Paper Review","Paper Correction"].includes(studyType);const knowledge=Math.min(100,Number(c.knowledge??0)+(isClass?1:studyType==="Revision"?2:3));const memory=Math.min(100,Math.max(Number(c.memory??0),studyType==="Revision"?48:38)+(studyType==="Revision"?6:isClass?1:2));const performance=Math.min(100,Number(c.performance??0)+(isPaper?4:1));const days=memory<45?2:memory<70?5:memory<85?10:21;await supabase.from("topic_progress").upsert({user_id:user.id,subject_name:subjectName,topic_name:topicName,coverage:Number(c.coverage??0),knowledge,memory,performance,last_studied_at:now.toISOString(),next_recall_at:new Date(now.getTime()+days*86400000).toISOString(),updated_at:now.toISOString()},{onConflict:"user_id,subject_name,topic_name"})},[user]);
 const syncQueue=useCallback(async()=>{if(!user||!isOnline)return;const q=await queuedMutationsFor(user.id,KINDS);for(const item of q){try{const p=item.payload;if(item.kind==="study_session_upsert"){const{error:e}=await supabase.from("study_sessions").upsert(p.sessionRow,{onConflict:"id"});if(e)throw e;if(p.lapRows?.length){const{error:le}=await supabase.from("study_laps").upsert(p.lapRows,{onConflict:"id"});if(le)throw le}if(p.touch)await touchTopic(p.touch.subjectName,p.touch.topicName,p.touch.studyType)}else if(item.kind==="study_session_analysis"){const{error:e}=await supabase.from("study_sessions").update(p.updates).eq("id",p.sessionId).eq("user_id",user.id);if(e)throw e}else if(item.kind==="study_session_reclassify"){const{error:e}=await supabase.from("study_sessions").update({subject_name:p.subjectName,topic_name:p.topicName,study_type:p.studyType}).eq("id",p.sessionId).eq("user_id",user.id);if(e)throw e;await touchTopic(p.subjectName,p.topicName,p.studyType)}else if(item.kind==="study_session_delete"){const{error:e}=await supabase.from("study_sessions").delete().eq("id",p.sessionId).eq("user_id",user.id);if(e)throw e}else if(item.kind==="paper_history_set"){if(p.attempts<=0){const{error:e}=await supabase.from("past_paper_history").delete().eq("user_id",user.id).eq("subject_name",p.subject).eq("paper_year",p.year).eq("paper_section",p.section);if(e)throw e}else{const{error:e}=await supabase.from("past_paper_history").upsert({user_id:user.id,subject_name:p.subject,paper_year:p.year,paper_section:p.section,attempts:p.attempts,updated_at:new Date().toISOString()},{onConflict:"user_id,subject_name,paper_year,paper_section"});if(e)throw e}}await removeQueuedMutation(item.id)}catch{break}}},[isOnline,touchTopic,user]);
 const refreshSessions=useCallback(async()=>{if(!user){setSessions([]);setPaperHistory([]);setLoading(false);return}setError(null);if(!isOnline){await loadCache();return}try{const[{data,error:e},{data:h,error:he}]=await Promise.all([supabase.from("study_sessions").select("id,subject_name,topic_name,study_type,started_at,duration_seconds,focus_rating,understanding_rating,paper_year,paper_section,attempt_no,session_note,source_class_id,occurrence_key,study_laps(id,lap_number,duration_milliseconds,total_milliseconds)").eq("user_id",user.id).order("started_at",{ascending:false}),supabase.from("past_paper_history").select("id,subject_name,paper_year,paper_section,attempts").eq("user_id",user.id)]);if(e||he)throw e??he;const next=(data??[]).map(mapSession),hist=(h??[]).map((r:any)=>({id:r.id,subjectName:r.subject_name,paperYear:Number(r.paper_year),paperSection:r.paper_section as PaperSection,attempts:Number(r.attempts??0)}));setSessions(next);setPaperHistory(hist);await persist(next,hist)}catch{await loadCache();setError("Offline copy shown. New changes will sync automatically when internet returns.")}finally{setLoading(false)}},[isOnline,loadCache,persist,user]);
 useEffect(()=>{if(!authLoading)loadCache().then(()=>refreshSessions())},[authLoading,loadCache,refreshSessions]);useEffect(()=>{if(isOnline&&user)syncQueue().then(()=>refreshSessions())},[isOnline,refreshSessions,syncQueue,syncTick,user]);
 const addSession=useCallback(async(s:NewStudySession)=>{if(!user)throw new Error("You must be signed in before saving a study session.");if(s.occurrenceKey){const existing=sessions.find(x=>x.occurrenceKey===s.occurrenceKey);if(existing)return existing.id}const id=makeUuid(),local:StudySession={id,subjectName:s.subjectName,topicName:s.topicName,studyType:s.studyType,startedAt:s.startedAt,durationSeconds:Math.max(0,Math.floor(s.durationSeconds)),focusRating:null,understandingRating:null,paperYear:s.paperYear??null,paperSection:s.paperSection??null,attemptNo:s.attemptNo??null,sessionNote:null,laps:(s.laps??[]).map(l=>({id:makeUuid(),number:l.number,durationMilliseconds:Math.max(0,Math.floor(l.duration)),totalMilliseconds:Math.max(0,Math.floor(l.total))})),sourceClassId:s.sourceClassId??null,occurrenceKey:s.occurrenceKey??null};const next=[local,...sessions];setSessions(next);await persist(next,paperHistory);await enqueueMutation({userId:user.id,kind:"study_session_upsert",payload:{sessionRow:{id,user_id:user.id,subject_name:local.subjectName,topic_name:local.topicName,study_type:local.studyType,started_at:local.startedAt,duration_seconds:local.durationSeconds,paper_year:local.paperYear,paper_section:local.paperSection,attempt_no:local.attemptNo,source_class_id:local.sourceClassId,occurrence_key:local.occurrenceKey},lapRows:local.laps.map(l=>({id:l.id,session_id:id,user_id:user.id,lap_number:l.number,duration_milliseconds:l.durationMilliseconds,total_milliseconds:l.totalMilliseconds})),touch:{subjectName:local.subjectName,topicName:local.topicName,studyType:local.studyType}}});if(isOnline)syncQueue().catch(()=>undefined);return id},[isOnline,paperHistory,persist,sessions,syncQueue,user]);
 const updateSessionAnalysis=useCallback(async(id:string,a:SessionAnalysis)=>{if(!user)throw new Error("You must be signed in.");const updates:any={};if(a.focusRating!==undefined)updates.focus_rating=a.focusRating;if(a.understandingRating!==undefined)updates.understanding_rating=a.understandingRating;if(a.sessionNote!==undefined)updates.session_note=a.sessionNote;const next=sessions.map(s=>s.id===id?{...s,focusRating:a.focusRating!==undefined?a.focusRating:s.focusRating,understandingRating:a.understandingRating!==undefined?a.understandingRating:s.understandingRating,sessionNote:a.sessionNote!==undefined?a.sessionNote:s.sessionNote}:s);setSessions(next);await persist(next,paperHistory);await enqueueMutation({userId:user.id,kind:"study_session_analysis",payload:{sessionId:id,updates}});if(isOnline)syncQueue().catch(()=>undefined)},[isOnline,paperHistory,persist,sessions,syncQueue,user]);
 const updateSessionClassification=useCallback(async(id:string,subjectName:string,topicName:string,studyType?:StudyType)=>{if(!user)throw new Error("You must be signed in.");const current=sessions.find(s=>s.id===id);if(!current)return;const type=studyType??current.studyType,next=sessions.map(s=>s.id===id?{...s,subjectName,topicName,studyType:type}:s);setSessions(next);await persist(next,paperHistory);await enqueueMutation({userId:user.id,kind:"study_session_reclassify",payload:{sessionId:id,subjectName,topicName,studyType:type}});if(isOnline)syncQueue().catch(()=>undefined)},[isOnline,paperHistory,persist,sessions,syncQueue,user]);
 const deleteSession=useCallback(async(id:string)=>{if(!user)return;const next=sessions.filter(s=>s.id!==id);setSessions(next);await persist(next,paperHistory);await enqueueMutation({userId:user.id,kind:"study_session_delete",payload:{sessionId:id}});if(isOnline)syncQueue().catch(()=>undefined)},[isOnline,paperHistory,persist,sessions,syncQueue,user]);
 const totalSeconds=useMemo(()=>sessions.reduce((t,s)=>t+s.durationSeconds,0),[sessions]),todaySeconds=useMemo(()=>sessions.reduce((t,s)=>t+(isToday(s.startedAt)?s.durationSeconds:0),0),[sessions]),subjectSeconds=useMemo(()=>sessions.reduce<Record<string,number>>((a,s)=>{a[s.subjectName]=(a[s.subjectName]??0)+s.durationSeconds;return a},{}),[sessions]),topicSeconds=useMemo(()=>sessions.reduce<Record<string,number>>((a,s)=>{const k=`${s.subjectName}::${s.topicName}`;a[k]=(a[k]??0)+s.durationSeconds;return a},{}),[sessions]);
 const getPaperAttemptCount=useCallback((subject:string,year:number,section?:PaperSection)=>sessions.filter(s=>s.studyType==="Past Papers"&&s.subjectName===subject&&s.paperYear===year&&(!section||s.paperSection===section)).length+paperHistory.filter(r=>r.subjectName===subject&&r.paperYear===year&&(!section||r.paperSection===section).reduce?false:false).length,[sessions,paperHistory]);
 const setManualPastPaperAttempts=useCallback(async(subject:string,year:number,section:PaperSection,attempts:number)=>{if(!user)throw new Error("You must be signed in.");const safe=Math.max(0,Math.floor(attempts)),existing=paperHistory.find(r=>r.subjectName===subject&&r.paperYear===year&&r.paperSection===section);let next=paperHistory.filter(r=>!(r.subjectName===subject&&r.paperYear===year&&r.paperSection===section));if(safe>0)next=[...next,{id:existing?.id??makeUuid(),subjectName:subject,paperYear:year,paperSection:section,attempts:safe}];setPaperHistory(next);await persist(sessions,next);await enqueueMutation({userId:user.id,kind:"paper_history_set",payload:{subject,year,section,attempts:safe}});if(isOnline)syncQueue().catch(()=>undefined)},[isOnline,paperHistory,persist,sessions,syncQueue,user]);
 const addManualPastPaperAttempt=useCallback(async(subject:string,year:number,section:PaperSection)=>{const current=paperHistory.find(r=>r.subjectName===subject&&r.paperYear===year&&r.paperSection===section)?.attempts??0;await setManualPastPaperAttempts(subject,year,section,current+1)},[paperHistory,setManualPastPaperAttempts]);
 const actualGetPaperAttemptCount=useCallback((subject:string,year:number,section?:PaperSection)=>{const timed=sessions.filter(s=>s.studyType==="Past Papers"&&s.subjectName===subject&&s.paperYear===year&&(!section||s.paperSection===section)).length;const manual=paperHistory.filter(r=>r.subjectName===subject&&r.paperYear===year&&(!section||r.paperSection===section)).reduce((sum,r)=>sum+r.attempts,0);return timed+manual},[sessions,paperHistory]);
 const value=useMemo<Value>(()=>({sessions,paperHistory,todaySeconds,totalSeconds,subjectSeconds,topicSeconds,loading,error,addSession,updateSessionAnalysis,updateSessionClassification,refreshSessions,deleteSession,getPaperAttemptCount:actualGetPaperAttemptCount,addManualPastPaperAttempt,setManualPastPaperAttempts}),[sessions,paperHistory,todaySeconds,totalSeconds,subjectSeconds,topicSeconds,loading,error,addSession,updateSessionAnalysis,updateSessionClassification,refreshSessions,deleteSession,actualGetPaperAttemptCount,addManualPastPaperAttempt,setManualPastPaperAttempts]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}
export function useStudy(){const v=useContext(Ctx);if(!v)throw new Error("useStudy must be used inside StudyProvider.");return v}
