import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';
import { Platform } from 'react-native';
import { supabase } from './supabase';
export type Recall = {id:string;uri?:string;subjectName:string;topicName:string;createdAt:string;durationSeconds:number;mimeType?:string;synced?:boolean;legacy?:boolean};
const KEY='@study-arc/audio-recall/local-v1';
const key=(owner:string)=>`${KEY}:${owner}`;
const MAX=10*1024*1024;
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(new Error('This browser cannot keep recordings offline.'));return}const req=indexedDB.open('studyarc-audio-recall',1);req.onupgradeneeded=()=>req.result.createObjectStore('audio');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function blobStore(owner:string,id:string,value?:Blob,remove=false):Promise<Blob|undefined>{const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('audio',value||remove?'readwrite':'readonly'),store=tx.objectStore('audio');const req=remove?store.delete(`${owner}:${id}`):value?store.put(value,`${owner}:${id}`):store.get(`${owner}:${id}`);let result:Blob|undefined;req.onsuccess=()=>{result=req.result instanceof Blob?req.result:undefined};tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error)}})}
export async function saveLocalAudio(owner:string,note:Recall):Promise<Recall>{if(!note.uri)throw new Error('Recording file is missing.');if(Platform.OS==='web'){const response=await fetch(note.uri);const blob=await response.blob();await blobStore(owner,note.id,blob);return {...note,mimeType:blob.type.split(';')[0]||'audio/webm'}}return note}
export async function localAudioUri(owner:string,note:Recall):Promise<string|null>{if(Platform.OS==='web'){const blob=await blobStore(owner,note.id).catch(()=>undefined);if(blob)return URL.createObjectURL(blob);if(note.uri){try{const r=await fetch(note.uri);if(r.ok)return note.uri}catch{}}return null}if(note.uri){const info=await FileSystem.getInfoAsync(note.uri);if(info.exists)return note.uri}return null}
export async function loadRecallCache(owner:string):Promise<Recall[]>{const raw=await AsyncStorage.getItem(key(owner));const rows=raw?JSON.parse(raw):[];return Array.isArray(rows)?rows.filter(n=>n&&typeof n.id==='string'&&typeof n.subjectName==='string'):[]}
export async function saveRecallCache(owner:string,notes:Recall[]){await AsyncStorage.setItem(key(owner),JSON.stringify(notes))}
export async function legacyRecalls():Promise<Recall[]>{const raw=await AsyncStorage.getItem(KEY);const rows=raw?JSON.parse(raw):[];return Array.isArray(rows)?rows.filter(n=>n&&typeof n.id==='string').map(n=>({...n,legacy:true})):[]}
export async function removeLegacyRecall(id:string){const rows=await legacyRecalls();await AsyncStorage.setItem(KEY,JSON.stringify(rows.filter(n=>n.id!==id)))}
export async function clearLocalAudio(owner:string,note:Recall){if(Platform.OS==='web')await blobStore(owner,note.id,undefined,true);else if(note.uri?.startsWith('file://'))await FileSystem.deleteAsync(note.uri,{idempotent:true})}
async function call(body:Record<string,unknown>,owner:string):Promise<any>{const {data:auth}=await supabase.auth.getSession();if(!auth.session||auth.session.user.id!==owner)throw new Error('Sign in to the same account to sync this recording.');const {data,error}=await supabase.functions.invoke('audio-recall-github',{body,headers:{Authorization:`Bearer ${auth.session.access_token}`}});if(error){let detail='';try{detail=(await (error as any).context?.json())?.error??''}catch{}throw new Error(detail||error.message||'Could not sync recordings.')}if(data?.error)throw new Error(data.error);return data}
export async function listCloudRecalls(owner:string):Promise<{notes:Recall[];deletedIds:string[]}>{const data=await call({action:'list'},owner);return {notes:(data.notes??[]).map((n:any)=>({id:n.id,subjectName:n.subjectName,topicName:n.topicName,createdAt:n.createdAt,durationSeconds:n.durationSeconds,mimeType:n.mimeType,synced:true})),deletedIds:data.deletedIds??[]}}
export function mergeRecalls(local:Recall[],remote:Recall[],deletedIds:string[]){const deleted=new Set(deletedIds),rows=new Map(local.filter(n=>!deleted.has(n.id)).map(n=>[n.id,n]));for(const n of remote){if(!deleted.has(n.id))rows.set(n.id,{...rows.get(n.id),...n})}return [...rows.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export async function uploadRecall(owner:string,note:Recall):Promise<Recall>{const uri=await localAudioUri(owner,note);if(!uri)throw new Error('The original recording is not available on this device.');let content:string,mimeType=note.mimeType??(uri.toLowerCase().includes('.3gp')?'audio/3gpp':'audio/mp4');try{if(Platform.OS==='web'){const blob=await (await fetch(uri)).blob();if(blob.size>MAX)throw new Error('Recordings must be under 10 MB to sync.');mimeType=blob.type.split(';')[0]||mimeType;const bytes=new Uint8Array(await blob.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));content=btoa(raw)}else{const info=await FileSystem.getInfoAsync(uri);if(!info.exists||('size' in info&&info.size>MAX))throw new Error('Recording is missing or larger than 10 MB.');content=await FileSystem.readAsStringAsync(uri,{encoding:FileSystem.EncodingType.Base64})}await call({action:'upload',id:note.id,subjectName:note.subjectName,topicName:note.topicName,createdAt:note.createdAt,durationSeconds:note.durationSeconds,mimeType,content},owner);return {...note,mimeType,synced:true,legacy:false}}finally{if(Platform.OS==='web'&&uri!==note.uri&&uri.startsWith('blob:'))URL.revokeObjectURL(uri)}}
export async function cloudAudioUri(owner:string,note:Recall):Promise<string>{const data=await call({action:'audio',id:note.id},owner);if(Platform.OS==='web'){const raw=atob(data.content),blob=new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:data.mimeType});await blobStore(owner,note.id,blob).catch(()=>undefined);return URL.createObjectURL(blob)}const dir=FileSystem.cacheDirectory;if(!dir)throw new Error('Audio cache is not available.');const ext=data.mimeType==='audio/webm'?'webm':data.mimeType==='audio/ogg'?'ogg':data.mimeType==='audio/mpeg'?'mp3':data.mimeType==='audio/wav'?'wav':data.mimeType==='audio/3gpp'?'3gp':'m4a';const uri=`${dir}recall-${owner}-${note.id}.${ext}`;await FileSystem.writeAsStringAsync(uri,data.content,{encoding:FileSystem.EncodingType.Base64});return uri}
export async function deleteCloudRecall(owner:string,id:string){await call({action:'delete',id},owner)}
