import type { StudentProfile, SubtopicCoverage, TopicProgress } from "../context/StudentContext";
import type { StudySession } from "../context/StudyContext";
import type { PaperQuestionResult, SessionOutcome, StudyMistake } from "../context/IntelligenceContext";
import { SUBJECTS, type SubjectName } from "../data/subjects";

const DAY=86_400_000;
const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
const dayKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const ageDays=(iso:string|null|undefined)=>iso?Math.max(0,(Date.now()-new Date(iso).getTime())/DAY):999;
const isPaper=(s:StudySession)=>["Past Papers","Paper Discussion","Paper Review","Paper Correction"].includes(s.studyType);

export type RiskStatus="Safe"|"Watch"|"Critical";
export type TopicRisk={subjectName:string;topicName:string;mastery:number;paperAccuracy:number|null;unresolvedMistakes:number;forgettingRisk:number;examRisk:number;status:RiskStatus;reason:string};

export function buildTopicRiskMap(subjects:SubjectName[],progress:TopicProgress[],coverage:SubtopicCoverage[],mistakes:StudyMistake[],questions:PaperQuestionResult[]):TopicRisk[]{
  const now=Date.now();const rows:TopicRisk[]=[];
  for(const subjectName of subjects){const subject=SUBJECTS[subjectName];if(!subject)continue;for(const topic of subject.topics){const p=progress.find(x=>x.subjectName===subjectName&&x.topicName===topic.title);const covered=coverage.some(x=>x.subjectName===subjectName&&x.topicName===topic.title&&x.covered);const q=questions.filter(x=>x.subjectName===subjectName&&x.topicName===topic.title);const marks=q.reduce((a,x)=>a+x.marksAwarded,0),total=q.reduce((a,x)=>a+x.marksTotal,0);const paperAccuracy=total>0?Math.round(marks/total*100):null;const unresolved=mistakes.filter(x=>!x.resolved&&x.subjectName===subjectName&&x.topicName===topic.title).length;const mastery=covered?Math.round((p?.knowledge??25)*.35+(p?.memory??25)*.35+(p?.performance??25)*.30):0;const last=p?.lastStudiedAt?new Date(p.lastStudiedAt).getTime():0;const next=p?.nextRecallAt?new Date(p.nextRecallAt).getTime():0;const staleDays=last?Math.max(0,(now-last)/DAY):60;let forgetting=clamp(staleDays*3+(next&&next<=now?28:0)+(p?.memory!=null?Math.max(0,55-p.memory):20));if(!covered)forgetting=100;let risk=clamp((100-mastery)*.48+(paperAccuracy==null?18:(100-paperAccuracy)*.27)+Math.min(25,unresolved*7)+(next&&next<=now?12:0));if(!covered)risk=Math.max(risk,86);const status:RiskStatus=risk>=68?"Critical":risk>=38?"Watch":"Safe";const reasons:string[]=[];if(!covered)reasons.push("not covered");if(paperAccuracy!=null&&paperAccuracy<65)reasons.push(`paper accuracy ${paperAccuracy}%`);if(unresolved)reasons.push(`${unresolved} unresolved mistake${unresolved===1?"":"s"}`);if(next&&next<=now)reasons.push("revision due");if(!reasons.length)reasons.push(status==="Safe"?"stable recent performance":"mastery needs reinforcement");rows.push({subjectName,topicName:topic.title,mastery,paperAccuracy,unresolvedMistakes:unresolved,forgettingRisk:Math.round(forgetting),examRisk:Math.round(risk),status,reason:reasons.join(" · ")})}}
  return rows.sort((a,b)=>b.examRisk-a.examRisk);
}

export function productivityEfficiency(sessions:StudySession[],outcomes:SessionOutcome[],days=7){const cutoff=Date.now()-days*DAY;const recent=sessions.filter(x=>new Date(x.startedAt).getTime()>=cutoff),seconds=recent.reduce((a,x)=>a+x.durationSeconds,0);const ids=new Set(recent.map(x=>x.id));const o=outcomes.filter(x=>x.sessionId&&ids.has(x.sessionId));const focus=recent.filter(x=>x.focusRating!=null);const understanding=recent.filter(x=>x.understandingRating!=null);const focusScore=focus.length?focus.reduce((a,x)=>a+(x.focusRating??0),0)/focus.length/5*100:65;const understandingScore=understanding.length?understanding.reduce((a,x)=>a+(x.understandingRating??0),0)/understanding.length/5*100:65;const outputRows=o.filter(x=>x.targetCount!=null&&x.targetCount!>0&&x.completedCount!=null);const outputScore=outputRows.length?outputRows.reduce((a,x)=>a+Math.min(1.2,(x.completedCount??0)/(x.targetCount??1)),0)/outputRows.length/1.2*100:70;const interruptionPenalty=o.length?Math.min(30,o.reduce((a,x)=>a+x.interruptionCount,0)/o.length*5):0;const score=clamp(focusScore*.34+understandingScore*.31+outputScore*.35-interruptionPenalty);return{score:Math.round(score),focusScore:Math.round(focusScore),understandingScore:Math.round(understandingScore),outputScore:Math.round(outputScore),hours:Math.round(seconds/360)/10,sessions:recent.length}}

export function consistencyMetrics(sessions:StudySession[]){const days=new Set(sessions.map(x=>dayKey(new Date(x.startedAt))));const today=new Date();let active7=0,active30=0;for(let i=0;i<30;i++){const d=new Date(today);d.setDate(d.getDate()-i);if(days.has(dayKey(d))){if(i<7)active7++;active30++}}let streak=0;for(let i=0;i<365;i++){const d=new Date(today);d.setDate(d.getDate()-i);if(days.has(dayKey(d)))streak++;else if(i===0)continue;else break}let recoveryStreak=0;const sorted=[...days].sort();for(let i=1;i<sorted.length;i++){const prev=new Date(`${sorted[i-1]}T00:00:00`).getTime(),cur=new Date(`${sorted[i]}T00:00:00`).getTime();if(cur-prev>=2*DAY&&cur-prev<=8*DAY)recoveryStreak++}return{active7,active30,weeklyConsistency:Math.round(active7/7*100),monthlyConsistency:Math.round(active30/30*100),streak,recoveryStreak}}

export function subjectNeglect(subjects:string[],sessions:StudySession[]){return subjects.map(subject=>{const latest=sessions.filter(x=>x.subjectName===subject).sort((a,b)=>new Date(b.startedAt).getTime()-new Date(a.startedAt).getTime())[0];const days=latest?Math.floor(ageDays(latest.startedAt)):999;return{subject,days,lastStudiedAt:latest?.startedAt??null,neglected:days>=6}}).sort((a,b)=>b.days-a.days)}

export function personalBests(sessions:StudySession[],questions:PaperQuestionResult[]){const byDay=new Map<string,number>();const countByDay=new Map<string,number>();for(const s of sessions){const key=dayKey(new Date(s.startedAt));byDay.set(key,(byDay.get(key)??0)+s.durationSeconds);countByDay.set(key,(countByDay.get(key)??0)+1)}const bestDay=[...byDay.entries()].sort((a,b)=>b[1]-a[1])[0]??null;const bestCount=[...countByDay.entries()].sort((a,b)=>b[1]-a[1])[0]??null;const paper=sessions.filter(isPaper).sort((a,b)=>b.durationSeconds-a.durationSeconds)[0]??null;const qMarks=questions.reduce((a,x)=>a+x.marksAwarded,0),qTotal=questions.reduce((a,x)=>a+x.marksTotal,0);return{bestDayDate:bestDay?.[0]??null,bestDaySeconds:bestDay?.[1]??0,mostSessionsDate:bestCount?.[0]??null,mostSessions:bestCount?.[1]??0,longestPaperSeconds:paper?.durationSeconds??0,questionAccuracy:qTotal?Math.round(qMarks/qTotal*100):null}}

export function discoverFocusWindows(sessions:StudySession[],outcomes:SessionOutcome[]){const outcomeMap=new Map(outcomes.filter(x=>x.sessionId).map(x=>[x.sessionId!,x]));const hours=Array.from({length:24},(_,hour)=>({hour,weighted:0,count:0,focus:0,understanding:0,energy:0}));for(const s of sessions){const row=hours[new Date(s.startedAt).getHours()];const o=outcomeMap.get(s.id);const f=s.focusRating??3,u=s.understandingRating??3,e=o?.energyBefore??3;const weight=Math.min(2,Math.max(.25,s.durationSeconds/3600));row.weighted+=(f*.45+u*.35+e*.20)*weight;row.focus+=f;row.understanding+=u;row.energy+=e;row.count++}return hours.filter(x=>x.count>0).map(x=>({...x,score:Math.round(x.weighted/Math.max(1,x.count)/5*100),focus:Math.round(x.focus/x.count*20),understanding:Math.round(x.understanding/x.count*20),energy:Math.round(x.energy/x.count*20)})).sort((a,b)=>b.score-a.score)}

export function paperTimePressure(results:PaperQuestionResult[]){const grouped=new Map<string,PaperQuestionResult[]>();for(const r of results){const key=`${r.subjectName}::${r.paperLabel??"Paper"}`;grouped.set(key,[...(grouped.get(key)??[]),r])}const analyses=[] as Array<{label:string;subjectName:string;firstAccuracy:number;lastAccuracy:number;drop:number;secondsPerMark:number|null;timePressure:boolean;sample:number}>;for(const[key,rows]of grouped){if(rows.length<6)continue;const sorted=[...rows].sort((a,b)=>{const na=parseFloat(a.questionNo),nb=parseFloat(b.questionNo);return Number.isFinite(na)&&Number.isFinite(nb)?na-nb:a.createdAt.localeCompare(b.createdAt)});const n=Math.max(2,Math.floor(sorted.length/3)),first=sorted.slice(0,n),last=sorted.slice(-n);const acc=(x:PaperQuestionResult[])=>{const t=x.reduce((a,r)=>a+r.marksTotal,0);return t?Math.round(x.reduce((a,r)=>a+r.marksAwarded,0)/t*100):0};const timed=sorted.filter(x=>x.durationSeconds!=null);const totalMarks=timed.reduce((a,x)=>a+x.marksTotal,0);const spm=totalMarks?Math.round(timed.reduce((a,x)=>a+(x.durationSeconds??0),0)/totalMarks):null;const firstAccuracy=acc(first),lastAccuracy=acc(last),drop=firstAccuracy-lastAccuracy;const[subjectName,label]=key.split("::");analyses.push({label,subjectName,firstAccuracy,lastAccuracy,drop,secondsPerMark:spm,timePressure:drop>=15&&lastAccuracy<70,sample:rows.length})}return analyses.sort((a,b)=>b.drop-a.drop)}

export function confidenceCalibration(results:PaperQuestionResult[]){const rated=results.filter(x=>x.confidence!=null);const highWrong=rated.filter(x=>(x.confidence??0)>=4&&x.marksAwarded/x.marksTotal<.5);const lowRight=rated.filter(x=>(x.confidence??6)<=2&&x.marksAwarded/x.marksTotal>=.8);const score=rated.length?clamp(100-(highWrong.length*18+lowRight.length*7)/rated.length*5):null;return{sample:rated.length,highConfidenceMistakes:highWrong.length,underConfidenceWins:lowRight.length,calibrationScore:score==null?null:Math.round(score)}}

export function normalizedPaperPerformance(results:PaperQuestionResult[]){const groups=new Map<string,PaperQuestionResult[]>();for(const r of results){if(!r.paperLabel)continue;groups.set(`${r.subjectName}::${r.paperLabel}`,[...(groups.get(`${r.subjectName}::${r.paperLabel}`)??[]),r])}const rows=[...groups.entries()].map(([key,q])=>{const total=q.reduce((a,x)=>a+x.marksTotal,0),awarded=q.reduce((a,x)=>a+x.marksAwarded,0),accuracy=total?awarded/total*100:0,difficulty=q.filter(x=>x.difficultyRating!=null);const difficultyAvg=difficulty.length?difficulty.reduce((a,x)=>a+(x.difficultyRating??3),0)/difficulty.length:3;const normalized=clamp(accuracy+(difficultyAvg-3)*4);const[subjectName,paperLabel]=key.split("::");return{subjectName,paperLabel,accuracy:Math.round(accuracy),difficulty:Math.round(difficultyAvg*10)/10,normalized:Math.round(normalized),questions:q.length}});return rows.sort((a,b)=>b.normalized-a.normalized)}

export function burnoutRisk(profile:StudentProfile,sessions:StudySession[],outcomes:SessionOutcome[]){const cutoff=Date.now()-7*DAY,recent=sessions.filter(x=>new Date(x.startedAt).getTime()>=cutoff),hours=recent.reduce((a,x)=>a+x.durationSeconds,0)/3600;const byDay=new Map<string,number>();recent.forEach(x=>{const k=dayKey(new Date(x.startedAt));byDay.set(k,(byDay.get(k)??0)+x.durationSeconds/3600)});const extremeDays=[...byDay.values()].filter(x=>x>=8).length;const energy=outcomes.filter(x=>new Date(x.createdAt).getTime()>=cutoff&&x.energyAfter!=null);const avgEnergy=energy.length?energy.reduce((a,x)=>a+(x.energyAfter??3),0)/energy.length:3;const sleepHours=(()=>{const[wH,wM]=profile.wakeTime.split(":").map(Number),[sH,sM]=profile.sleepTime.split(":").map(Number);let wake=wH*60+wM,sleep=sH*60+sM;if(sleep<=wake)sleep+=1440;return(sleep-wake)/60})();let risk=0;if(hours>=45)risk+=30;if(extremeDays>=2)risk+=25;if(avgEnergy<=2.3)risk+=30;if(sleepHours<7)risk+=25;return{score:clamp(risk),hours:Math.round(hours*10)/10,extremeDays,avgEnergy:Math.round(avgEnergy*10)/10,sleepHours:Math.round(sleepHours*10)/10,status:risk>=60?"High":risk>=30?"Watch":"Low" as "High"|"Watch"|"Low"}}

export function adaptiveBreakMinutes(lastSessionMinutes:number,focusRating:number|null,energyAfter:number|null){let value=10;if(lastSessionMinutes>=90)value=18;else if(lastSessionMinutes>=60)value=14;else if(lastSessionMinutes<=30)value=7;if((focusRating??3)<=2)value+=5;if((energyAfter??3)<=2)value+=7;return Math.max(5,Math.min(30,value))}

export function syllabusCompletionForecast(subjects:SubjectName[],coverage:SubtopicCoverage[],sessions:StudySession[]){let total=0,covered=0;for(const subjectName of subjects){const subject=SUBJECTS[subjectName];if(!subject)continue;total+=subject.topics.length;covered+=subject.topics.filter(t=>coverage.some(x=>x.subjectName===subjectName&&x.topicName===t.title&&x.covered)).length}const remaining=Math.max(0,total-covered);const cutoff=Date.now()-28*DAY;const recentTopicSessions=new Set(sessions.filter(x=>new Date(x.startedAt).getTime()>=cutoff&&x.topicName!=="General").map(x=>`${x.subjectName}::${x.topicName}`)).size;const weeklyPace=Math.max(.5,recentTopicSessions/4);const weeks=remaining/weeklyPace;const estimate=new Date(Date.now()+weeks*7*DAY);return{total,covered,remaining,coveragePercent:total?Math.round(covered/total*100):0,weeklyPace:Math.round(weeklyPace*10)/10,estimatedDate:remaining?estimate.toISOString():null,weeks:Math.round(weeks*10)/10}}

export function miniMockTopics(risks:TopicRisk[],mistakes:StudyMistake[],count=6){const unresolved=mistakes.filter(x=>!x.resolved);const seen=new Set<string>();const result:Array<{subjectName:string;topicName:string;reason:string;source:"risk"|"mistake"}>=[];for(const m of unresolved.sort((a,b)=>(b.confidence??0)-(a.confidence??0))){const key=`${m.subjectName}::${m.topicName}`;if(seen.has(key))continue;seen.add(key);result.push({subjectName:m.subjectName,topicName:m.topicName,reason:`Unresolved ${m.mistakeType.toLowerCase()}${m.questionRef?` · ${m.questionRef}`:""}`,source:"mistake"});if(result.length>=count)return result}for(const r of risks){const key=`${r.subjectName}::${r.topicName}`;if(seen.has(key))continue;seen.add(key);result.push({subjectName:r.subjectName,topicName:r.topicName,reason:`${r.status} risk · ${r.reason}`,source:"risk"});if(result.length>=count)break}return result}

export function planHealthScore(plannedStudyMinutes:number,freeMinutes:number,assignmentRiskCount:number,burnoutScore:number){let score=85;if(plannedStudyMinutes>8*60)score-=20;if(freeMinutes<30)score-=15;if(assignmentRiskCount>0)score-=Math.min(25,assignmentRiskCount*8);score-=Math.round(burnoutScore*.25);return clamp(score)}
