import type{PaperTopicResult}from"../context/AcademicContext";
import type{ClassSchedule,StudentProfile,SubtopicCoverage,TestMark,TopicProgress}from"../context/StudentContext";
import{SUBJECTS,expandSubjectChoices,type SubjectName}from"../data/subjects";
import{assignmentPriorityFor}from"./assignmentPriorityRuntime";
import{getRuntimePaperTopicResults}from"./academicRuntime";
import{getRuntimePhaseSettings}from"./phaseRuntime";
import{getRuntimePlanningPreferences}from"./planningRuntime";
import{isLessonExcludedFromRevise}from"./revisePreferences";
import{localDateKey,weekStartKey}from"./scheduleAdjustments";
import{getRuntimeScheduleAdjustments}from"./scheduleRuntime";
import type{StudyPhase}from"./studyPhases";
import{getRuntimeAssignments}from"./timetableRuntime";
import{durationMinutes,minutesToTime,parseTime}from"./time";

export type PlanBlockType="routine"|"study"|"revision"|"break"|"class"|"travel"|"meal"|"free";
export type PlanBlock={id:string;start:string;end:string;type:PlanBlockType;title:string;subtitle?:string;subjectName?:string;topicName?:string;priority?:"high"|"normal";breakMinutes?:number};
export type PlannerPhaseOptions={phase?:StudyPhase;examSubjects?:string[];examTopics?:Record<string,string[]>;doneSubjects?:string[]};
type FixedBlock={start:number;end:number;block:Omit<PlanBlock,"start"|"end">};
export type PlannerQueueItem={subjectName:SubjectName;topicName:string;score:number;reviewDue:boolean;memoryHeavy:boolean;bucket:string;classFocus:boolean;weaknessPercent:number};
export type MissedPlanDecision={action:"reschedule"|"split"|"reduce"|"drop";reason:string;parts:number[]};
type WorkNeed={id:string;title:string;subtitle:string;minutes:number;subjectName?:string;topicName?:string;mode:"study"|"revision";priorityRank?:number};
const DAY=86400000,TASK_PREFIX="__REPETITIVE_TASK__:";
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const block=(id:string,start:number,end:number,type:PlanBlockType,title:string,extra:Partial<PlanBlock>={}):PlanBlock=>({id,start:minutesToTime(start),end:minutesToTime(end),type,title,...extra});
export const planningBucketFor=(subjectName:string)=>subjectName;
const resolvePhase=(phase:PlannerPhaseOptions):PlannerPhaseOptions=>Object.keys(phase).length?phase:getRuntimePhaseSettings() as PlannerPhaseOptions;
function mergeFixed(items:FixedBlock[]){const sorted=items.filter(x=>x.end>x.start).sort((a,b)=>a.start-b.start),out:FixedBlock[]=[];for(const item of sorted){const prev=out[out.length-1];if(!prev||item.start>=prev.end){out.push(item);continue}if(item.end>prev.end)out.push({...item,start:prev.end})}return out}
function manualTopics(coverage:SubtopicCoverage[]){const result=new Set<string>();for(const[subjectName,subject]of Object.entries(SUBJECTS))for(const topic of subject.topics){if(!topic.subtopics.length)continue;const complete=topic.subtopics.every(subtopic=>coverage.some(r=>r.subjectName===subjectName&&r.topicName===topic.title&&r.subtopicName===subtopic&&r.covered&&r.source==="Manual"));if(complete)result.add(`${subjectName}::${topic.title}`)}return result}
function latestWeakness(results:PaperTopicResult[]){const map=new Map<string,number>();for(const result of results){const key=`${result.subjectName}::${result.topicName}`;if(!map.has(key)&&result.weaknessPercent!=null)map.set(key,clamp(Number(result.weaknessPercent),0,100))}return map}
function phaseAllows(subject:string,topic:string,phase:PlannerPhaseOptions){if(phase.phase==="Exam Month"&&(phase.doneSubjects??[]).includes(subject))return false;if(phase.phase!=="Main Exam Preparation"&&phase.phase!=="Exam Month")return true;if((phase.examSubjects??[]).length&&!phase.examSubjects!.includes(subject))return false;const topics=phase.examTopics?.[subject]??[];return !topics.length||topics.includes(topic)}
export function weaknessQueue(profile:StudentProfile,progress:TopicProgress[],testMarks:TestMark[]=[],coverage:SubtopicCoverage[]=[],phase:PlannerPhaseOptions={},paperTopicResults:PaperTopicResult[]=getRuntimePaperTopicResults()):PlannerQueueItem[]{const active=resolvePhase(phase),subjects=expandSubjectChoices(profile.subjectChoices),covered=manualTopics(coverage),weakness=latestWeakness(paperTopicResults),now=Date.now(),prefs=getRuntimePlanningPreferences(),queue:PlannerQueueItem[]=[];for(const subjectName of subjects){const subject=SUBJECTS[subjectName];if(!subject)continue;for(const topic of subject.topics){if(!covered.has(`${subjectName}::${topic.title}`)||!phaseAllows(subjectName,topic.title,active))continue;const p=progress.find(r=>r.subjectName===subjectName&&r.topicName===topic.title),weakHits=testMarks.filter(m=>m.subjectName===subjectName&&m.weakTopics.includes(topic.title)).length,reviewDue=Boolean(p?.nextRecallAt&&new Date(p.nextRecallAt).getTime()<=now),manualWeakness=weakness.get(`${subjectName}::${topic.title}`)??0,memoryHeavy=subjectName==="Biology",mastery=(p?.knowledge??0)*.35+(p?.memory??0)*.35+(p?.performance??0)*.3;let score=mastery-Math.min(42,weakHits*12)-(reviewDue?24:0)-manualWeakness*.35;if(prefs.catchUpMode){if(reviewDue)score-=18;if(mastery<55)score-=14;score-=manualWeakness*.15}queue.push({subjectName,topicName:topic.title,score,reviewDue,memoryHeavy,bucket:planningBucketFor(subjectName),classFocus:false,weaknessPercent:manualWeakness})}}return queue.sort((a,b)=>a.score-b.score)}
function currentOverride(classId:string,date:Date){return getRuntimeScheduleAdjustments().classWeekOverrides.find(x=>x.classId===classId&&x.weekStart===weekStartKey(date))}
function focusTopics(classId:string,date:Date){const target=new Date(`${weekStartKey(date)}T00:00:00`).getTime(),topics=new Set<string>();const rows=getRuntimeScheduleAdjustments().classWeekOverrides.filter(x=>x.classId===classId&&x.status!=="Missed").map(x=>({x,time:new Date(`${x.weekStart}T00:00:00`).getTime()})).filter(x=>x.time<=target&&target-x.time<=14*DAY);for(const{x}of rows){const names=x.topicNames?.length?x.topicNames:x.topicName?[x.topicName]:[];for(const name of names)topics.add(name)}return topics}
function daysUntilClass(date:Date,c:ClassSchedule){const o=currentOverride(c.id,date);if(o?.status==="Missed")return Infinity;if(o?.status==="Rescheduled"&&o.rescheduledDate){const diff=Math.round((new Date(`${o.rescheduledDate}T00:00:00`).getTime()-new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime())/DAY);if(diff>=0)return diff}return(c.dayOfWeek-date.getDay()+7)%7}
function classPriority(queue:PlannerQueueItem[],date:Date,classes:ClassSchedule[]){return queue.map(item=>{let score=item.score,classFocus=false;for(const c of classes.filter(x=>x.subjectName===item.subjectName)){const focused=focusTopics(c.id,date);if(focused.has(item.topicName)){score-=34;classFocus=true}const until=daysUntilClass(date,c);if(until<=2)score-=8;if(c.classType==="Paper"&&until<=2)score-=12}return{...item,score,classFocus}}).sort((a,b)=>a.score-b.score)}
function appendClass(result:FixedBlock[],c:ClassSchedule,startTime:string,endTime:string,suffix=""){const start=parseTime(startTime),end=start+durationMinutes(startTime,endTime),travel=c.deliveryMode==="Physical"?Math.max(0,c.travelMinutes||90):0,review=Math.max(0,c.preReviewMinutes||30,c.classType==="Paper"?60:0),tag=suffix?`-${suffix}`:"",breakMinutes=Math.max(0,Number((c as ClassSchedule&{breakMinutes?:number}).breakMinutes??0));if(review)result.push({start:start-travel-review,end:start-travel,block:{id:`review-${c.id}${tag}`,type:"revision",title:c.classType==="Paper"?`Paper-class preparation · ${c.subjectName}`:`Pre-class review · ${c.subjectName}`,subjectName:c.subjectName,priority:"high"}});if(travel)result.push({start:start-travel,end:start,block:{id:`travel-out-${c.id}${tag}`,type:"travel",title:"Travel to class",subjectName:c.subjectName}});result.push({start,end,block:{id:`class-${c.id}${tag}`,type:"class",title:`${c.subjectName} · ${c.classType} class`,subtitle:c.deliveryMode,subjectName:c.subjectName,breakMinutes}});if(travel)result.push({start:end,end:end+travel,block:{id:`travel-home-${c.id}${tag}`,type:"travel",title:"Travel home",subjectName:c.subjectName}})}
function classBlocks(date:Date,classes:ClassSchedule[]){const out:FixedBlock[]=[],week=weekStartKey(date),day=localDateKey(date),overrides=getRuntimeScheduleAdjustments().classWeekOverrides;for(const c of classes){const o=overrides.find(x=>x.classId===c.id&&x.weekStart===week);if(o?.status==="Missed")continue;if(o?.status==="Rescheduled"){if(o.rescheduledDate===day&&o.startTime&&o.endTime)appendClass(out,c,o.startTime,o.endTime,`makeup-${o.id}`);continue}if(c.dayOfWeek===date.getDay())appendClass(out,c,c.startTime,c.endTime)}return out}
function protectedBlocks(date:Date):FixedBlock[]{const today=localDateKey(date);return getRuntimeScheduleAdjustments().protectedTimes.filter(x=>x.recurrence==="Daily"||x.recurrence==="Weekly"?x.recurrence==="Daily"||x.dayOfWeek===date.getDay():x.date===today).map(x=>{const repetitive=x.title.startsWith(TASK_PREFIX),name=repetitive?x.title.slice(TASK_PREFIX.length):x.title;return{start:parseTime(x.startTime),end:parseTime(x.startTime)+durationMinutes(x.startTime,x.endTime),block:{id:`protected-${x.id}`,type:"free" as const,title:repetitive?`Repetitive task · ${name}`:`Protected time · ${name}`,subtitle:repetitive?`${x.recurrence==="Daily"?"Repeats every day":"Repeats every week"} · reserved from study`:"Unavailable time"}}})}
function targets(profile:StudentProfile,queue:PlannerQueueItem[]){const buckets=[...new Set(queue.map(x=>x.bucket))],prefs=getRuntimePlanningPreferences(),weekly=Math.max(7*60,Math.round((profile.selfStudyHours||3)*7*60));if(!buckets.length)return{} as Record<string,number>;const adjustments=prefs.weeklySubjectAdjustments,totalAdj=buckets.reduce((s,b)=>s+(adjustments[b]??0),0),base=Math.max(60,(weekly-totalAdj)/buckets.length);return Object.fromEntries(buckets.map(b=>[b,Math.max(60,base+(adjustments[b]??0))]))}
function choose(queue:PlannerQueueItem[],target:Record<string,number>,allocated:Record<string,number>,usage:Record<string,number>,preferredBucket?:string){const buckets=[...new Set(queue.map(x=>x.bucket))].sort();if(!buckets.length)return undefined;const bucket=preferredBucket&&buckets.includes(preferredBucket)?preferredBucket:[...buckets].sort((a,b)=>((allocated[a]??0)/(target[a]||1))-((allocated[b]??0)/(target[b]||1)))[0];return queue.filter(x=>x.bucket===bucket).sort((a,b)=>(a.score+(usage[`${a.subjectName}::${a.topicName}`]??0)*10)-(b.score+(usage[`${b.subjectName}::${b.topicName}`]??0)*10))[0]}
function assignmentNeeds(date:Date):WorkNeed[]{const dayStart=new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime();return getRuntimeAssignments().filter(x=>!x.completed).flatMap(item=>{const estimate=Math.max(5,Math.min(1440,Number(item.estimatedMinutes)||60));if(!item.dueAt){if(date.getDay()!==1)return[];return[{id:`assignment-${item.id}`,title:`Assignment · ${item.title}`,subtitle:`${item.subjectName} · no deadline · student priority`,minutes:Math.min(90,estimate),subjectName:item.subjectName,topicName:item.topicName??undefined,mode:"study" as const,priorityRank:assignmentPriorityFor(item.id)}]}const due=new Date(item.dueAt);if(Number.isNaN(due.getTime()))return[];const dueStart=new Date(due.getFullYear(),due.getMonth(),due.getDate()).getTime(),days=Math.floor((dueStart-dayStart)/DAY);if(days>7)return[];const share=days<0?Math.min(180,estimate):Math.max(30,Math.min(180,Math.ceil(estimate/Math.max(1,days+1)/15)*15));return[{id:`assignment-${item.id}`,title:`Assignment · ${item.title}`,subtitle:`${item.subjectName} · ${days<0?"overdue":days===0?"due today":`due in ${days} day${days===1?"":"s"}`} · assignments take priority`,minutes:share,subjectName:item.subjectName,topicName:item.topicName??undefined,mode:"study" as const,priorityRank:assignmentPriorityFor(item.id)}]}).sort((a,b)=>(a.priorityRank??1000)-(b.priorityRank??1000))}
function classWorkNeeds(date:Date,classes:ClassSchedule[]):WorkNeed[]{const out:WorkNeed[]=[];for(const c of classes){const homeworkDay=(c.dayOfWeek+1)%7,paperDay=(c.dayOfWeek+2)%7;if(date.getDay()===homeworkDay)out.push({id:`class-homework-${c.id}`,title:`Class homework · ${c.subjectName}`,subtitle:`3h weekly homework for ${c.classType} class`,minutes:180,subjectName:c.subjectName,mode:"study",priorityRank:50});if((c.classType==="Paper"||c.classType==="Paper Discussion")&&date.getDay()===paperDay)out.push({id:`paper-review-${c.id}`,title:`Paper Review · ${c.subjectName}`,subtitle:"2h weekly review after paper class",minutes:120,subjectName:c.subjectName,mode:"revision",priorityRank:60})}return out}
export function generateDailyPlan(date:Date,profile:StudentProfile,classes:ClassSchedule[],progress:TopicProgress[],testMarks:TestMark[]=[],coverage:SubtopicCoverage[]=[],phase:PlannerPhaseOptions={},paperTopicResults:PaperTopicResult[]=getRuntimePaperTopicResults()):PlanBlock[]{
 const active=resolvePhase(phase),prefs=getRuntimePlanningPreferences(),wake=parseTime(profile.wakeTime||"06:00");let sleep=parseTime(profile.sleepTime||"22:30");if(sleep<=wake)sleep+=1440;const examMode=active.phase==="Exam Month",mainMode=active.phase==="Main Exam Preparation",paperMode=active.phase==="Paper Practice",declared=Math.max(1,Math.min(18,profile.selfStudyHours||3)),highOutput=declared>10;
 const morning=Math.max(0,Math.min(360,profile.morningRoutineMinutes??90));const fixed:FixedBlock[]=[{start:wake,end:wake+morning,block:{id:"morning",type:"routine",title:"Wake up · morning routine"}},{start:clamp(12*60+30,wake+60,sleep-180),end:clamp(13*60+15,wake+105,sleep-135),block:{id:"lunch",type:"meal",title:"Lunch + reset"}},{start:clamp(19*60,wake+180,sleep-120),end:clamp(19*60+45,wake+225,sleep-75),block:{id:"dinner",type:"meal",title:"Dinner"}},{start:sleep-60,end:sleep-30,block:{id:"day-review",type:"routine",title:"Review the day",subtitle:"30 min · review output, mistakes and tomorrow's priorities"}},{start:sleep-30,end:sleep,block:{id:"wind-down",type:"routine",title:"Wind down"}},...classBlocks(date,classes),...protectedBlocks(date)];
 const safe=mergeFixed(fixed.map(x=>({...x,start:Math.max(wake,x.start),end:Math.min(sleep,x.end)}))),classMinutes=safe.filter(x=>x.block.type==="class").reduce((s,x)=>s+Math.max(0,x.end-x.start-(x.block.breakMinutes??0)),0),desired=Math.round(declared*60),targetStudy=Math.max(0,desired-(prefs.countClassTimeTowardTarget?classMinutes:0));
 const queue=classPriority(weaknessQueue(profile,progress,testMarks,coverage,active,paperTopicResults),date,classes),target=targets(profile,queue),weeklyBuckets=[...new Set(queue.map(x=>x.bucket))].sort(),fallbackSubjects=expandSubjectChoices(profile.subjectChoices).filter(s=>phaseAllows(s,"",active)),allocated:Record<string,number>={},usage:Record<string,number>={};let studied=0,index=0,cursor=wake;const plan:PlanBlock[]=[];
 const required=[...assignmentNeeds(date),...classWorkNeeds(date,classes)].sort((a,b)=>(a.priorityRank??1000)-(b.priorityRank??1000));const focusLimit=highOutput?Math.min(90,prefs.maxStudyBlockMinutes):prefs.maxStudyBlockMinutes,recovery=highOutput?8:20;
 const addRecovery=(p:number,end:number,label:string)=>{if(end-p<8)return{p};const b=Math.min(recovery,end-p);plan.push(block(`break-${localDateKey(date)}-${p}`,p,p+b,"break",label));return{p:p+b}};
 const fill=(start:number,end:number)=>{let p=start;while(p<end){const remaining=end-p,requiredItem=required.find(x=>x.minutes>0);if(requiredItem&&remaining>=30){const length=Math.min(requiredItem.minutes,focusLimit,remaining);if(length>=30){plan.push(block(`${requiredItem.id}-${localDateKey(date)}-${p}`,p,p+length,requiredItem.mode,requiredItem.title,{subtitle:requiredItem.subtitle,subjectName:requiredItem.subjectName,topicName:requiredItem.topicName,priority:"high"}));requiredItem.minutes-=length;studied+=length;p+=length;if(requiredItem.minutes>0){p=addRecovery(p,end,highOutput?"High-output recovery":"Recovery break").p}continue}}
  const need=targetStudy-studied;if(need>0&&remaining>=30){const preferred=Math.min(focusLimit,Math.max(30,need)),length=Math.min(preferred,remaining),weeklySubject=weeklyBuckets.length?weeklyBuckets[((date.getDay()+6)%7*4+index)%weeklyBuckets.length]:undefined,item=choose(queue,target,allocated,usage,weeklySubject);if(item){const key=`${item.subjectName}::${item.topicName}`,canRevise=!isLessonExcludedFromRevise(item.subjectName,item.topicName),revision=canRevise&&(item.reviewDue||item.classFocus||index%2===1||(mainMode&&index%3===1)||(prefs.catchUpMode&&item.weaknessPercent>=60)),paper=examMode||paperMode||(mainMode&&index%2===0);plan.push(block(`study-${localDateKey(date)}-${p}`,p,p+length,revision&&!paper?"revision":"study",paper?`Exam practice · ${item.topicName}`:revision?`Revise · ${item.topicName}`:item.topicName,{subtitle:paper?`${item.subjectName} · timed questions / paper practice`:revision?`${item.subjectName} · active recall / rewatch / reread${item.classFocus?" · after class":""}`:`${item.subjectName} · focused study`,subjectName:item.subjectName,topicName:item.topicName,priority:item.score<50||item.reviewDue||item.classFocus||item.weaknessPercent>=65?"high":"normal"}));allocated[item.bucket]=(allocated[item.bucket]??0)+length;usage[key]=(usage[key]??0)+1}else if(fallbackSubjects.length){const subject=fallbackSubjects[index%fallbackSubjects.length];plan.push(block(`general-${localDateKey(date)}-${p}-${index}`,p,p+length,"study",`Focused study · ${subject}`,{subtitle:"General subject work · use this block for the highest-value unfinished lesson, tute or class work",subjectName:subject,topicName:"General",priority:"normal"}))}else{plan.push(block(`free-${localDateKey(date)}-${p}`,p,end,"free","Your own time"));p=end;continue}studied+=length;index++;p+=length;if(studied<targetStudy)p=addRecovery(p,end,highOutput?"High-output recovery":"Recovery break").p;continue}
  const short=Math.max(0,targetStudy-studied);plan.push(block(`free-${localDateKey(date)}-${p}`,p,end,"free",short>0?"Maximum usable time reached":"Your own time",{subtitle:short>0?`${Math.ceil(short/60*10)/10}h of your declared target could not fit around sleep, routines, classes and protected time.`:"Daily academic target covered"}));p=end}}
 for(const item of safe){if(item.start>cursor)fill(cursor,item.start);plan.push({...item.block,start:minutesToTime(item.start),end:minutesToTime(item.end)});cursor=Math.max(cursor,item.end)}if(cursor<sleep)fill(cursor,sleep);return plan.sort((a,b)=>parseTime(a.start)-parseTime(b.start))
}
export function generateBonusWork(profile:StudentProfile,progress:TopicProgress[],testMarks:TestMark[]=[],count=5,coverage:SubtopicCoverage[]=[],phase:PlannerPhaseOptions={},paperTopicResults:PaperTopicResult[]=getRuntimePaperTopicResults()){return weaknessQueue(profile,progress,testMarks,coverage,phase,paperTopicResults).slice(0,Math.max(1,count)).map((item,index)=>({id:`bonus-${item.subjectName}-${item.topicName}`,subjectName:item.subjectName,topicName:item.topicName,title:item.reviewDue&&!isLessonExcludedFromRevise(item.subjectName,item.topicName)?`Revise · ${item.topicName}`:item.topicName,subtitle:item.weaknessPercent>0?`${item.subjectName} · ${item.weaknessPercent}% weakness signal`:item.reviewDue?`${item.subjectName} · memory review due`:`${item.subjectName} · priority practice`,studyType:(!isLessonExcludedFromRevise(item.subjectName,item.topicName)&&(item.reviewDue||index%3===0)?"Revision":"Study Session") as "Revision"|"Study Session"}))}
export function weeklySubjectMinutes(profile:StudentProfile,_classes:ClassSchedule[],plans:PlanBlock[][]){const result:Record<string,{selfStudy:number;classLearning:number;academic:number}>={};for(const subject of expandSubjectChoices(profile.subjectChoices))result[subject]={selfStudy:0,classLearning:0,academic:0};for(const b of plans.flat()){if(!b.subjectName)continue;const mins=durationMinutes(b.start,b.end);result[b.subjectName]??={selfStudy:0,classLearning:0,academic:0};if(b.type==="study"||b.type==="revision")result[b.subjectName].selfStudy+=mins;if(b.type==="class")result[b.subjectName].classLearning+=Math.max(0,mins-(b.breakMinutes??0))}for(const v of Object.values(result))v.academic=v.selfStudy+v.classLearning;return result}
export function recommendTaskNow(availableMinutes:number,profile:StudentProfile,progress:TopicProgress[],testMarks:TestMark[]=[],coverage:SubtopicCoverage[]=[],phase:PlannerPhaseOptions={},paperTopicResults:PaperTopicResult[]=getRuntimePaperTopicResults()){const item=weaknessQueue(profile,progress,testMarks,coverage,phase,paperTopicResults)[0];if(!item)return null;const minutes=clamp(Math.floor(availableMinutes/15)*15,15,Math.min(availableMinutes,90)),canRevise=!isLessonExcludedFromRevise(item.subjectName,item.topicName),reason=item.weaknessPercent>=50?`You marked this topic ${item.weaknessPercent}% weak.`:item.reviewDue?"Memory review is due.":item.score<45?"This is currently one of your weakest fully covered topics.":"This fits your available time and keeps subject balance moving.";return{subjectName:item.subjectName,topicName:item.topicName,minutes,studyType:item.reviewDue&&canRevise||item.weaknessPercent>=65&&canRevise?"Revision" as const:"Study Session" as const,reason}}
export function recoverMissedBlock(blockValue:PlanBlock,daysUntilDeadline:number,availableMinutes:number):MissedPlanDecision{const original=durationMinutes(blockValue.start,blockValue.end),high=blockValue.priority==="high"||daysUntilDeadline<=3;if(!high&&daysUntilDeadline>10)return{action:"drop",reason:"Low priority and no near deadline; protect the remaining plan.",parts:[]};if(availableMinutes>=original)return{action:"reschedule",reason:"Enough free time remains to recover the full task.",parts:[original]};if(availableMinutes>=Math.max(60,original*.7))return{action:"reduce",reason:"Keep the highest-value part without pushing the whole timetable forward.",parts:[availableMinutes]};if(availableMinutes>=45&&original>=90)return{action:"split",reason:"Recover the task in smaller blocks across later free windows.",parts:[Math.min(60,availableMinutes),Math.max(30,original-Math.min(60,availableMinutes))]};return{action:high?"split":"drop",reason:high?"The task matters, so preserve a smaller recovery block.":"Not enough useful time remains for a low-priority recovery.",parts:high?[Math.max(30,availableMinutes)]:[]}}
