import { SUBJECTS, expandSubjectChoices, type SubjectName } from "../data/subjects";
import type { ClassSchedule, StudentProfile, SubtopicCoverage, TopicProgress, TestMark } from "../context/StudentContext";
import { getRuntimePhaseSettings } from "./phaseRuntime";
import { getRuntimePlanningPreferences } from "./planningRuntime";
import { localDateKey, weekStartKey } from "./scheduleAdjustments";
import { getRuntimeScheduleAdjustments } from "./scheduleRuntime";
import type { StudyPhase } from "./studyPhases";
import { durationMinutes, minutesToTime, parseTime } from "./time";

export type PlanBlockType = "routine"|"study"|"revision"|"break"|"class"|"travel"|"meal"|"free";
export type PlanBlock = { id:string;start:string;end:string;type:PlanBlockType;title:string;subtitle?:string;subjectName?:string;topicName?:string;priority?:"high"|"normal" };
export type PlannerPhaseOptions={phase?:StudyPhase;examSubjects?:string[];examTopics?:Record<string,string[]>;doneSubjects?:string[]};
type FixedBlock={start:number;end:number;block:Omit<PlanBlock,"start"|"end">};
export type PlannerQueueItem={subjectName:SubjectName;topicName:string;score:number;reviewDue:boolean;memoryHeavy:boolean;bucket:string;classFocus:boolean};
export type MissedPlanDecision={action:"reschedule"|"split"|"reduce"|"drop";reason:string;parts:number[]};

const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const block=(id:string,start:number,end:number,type:PlanBlockType,title:string,extra:Partial<PlanBlock>={}):PlanBlock=>({id,start:minutesToTime(start),end:minutesToTime(end),type,title,...extra});
export const planningBucketFor=(subjectName:string)=>subjectName;
const resolvePhase=(phase:PlannerPhaseOptions):PlannerPhaseOptions=>Object.keys(phase).length?phase:getRuntimePhaseSettings() as PlannerPhaseOptions;

function mergeFixed(items:FixedBlock[]){
 const sorted=items.filter(x=>x.end>x.start).sort((a,b)=>a.start-b.start);const out:FixedBlock[]=[];
 for(const item of sorted){const prev=out[out.length-1];if(!prev||item.start>=prev.end){out.push(item);continue}if(item.end>prev.end)out.push({...item,start:prev.end})}
 return out;
}
function manualTopics(coverage:SubtopicCoverage[]){return new Set(coverage.filter(r=>r.covered&&r.source==="Manual").map(r=>`${r.subjectName}::${r.topicName}`))}
function phaseAllows(subject:string,topic:string,phase:PlannerPhaseOptions){if(phase.phase==="Exam Month"&&(phase.doneSubjects??[]).includes(subject))return false;if(phase.phase!=="Main Exam Preparation"&&phase.phase!=="Exam Month")return true;if((phase.examSubjects??[]).length&&!phase.examSubjects!.includes(subject))return false;const topics=phase.examTopics?.[subject]??[];return !topics.length||topics.includes(topic)}

export function weaknessQueue(profile:StudentProfile,progress:TopicProgress[],testMarks:TestMark[]=[],coverage:SubtopicCoverage[]=[],phase:PlannerPhaseOptions={}):PlannerQueueItem[]{
 const active=resolvePhase(phase),subjects=expandSubjectChoices(profile.subjectChoices),covered=manualTopics(coverage),now=Date.now(),queue:PlannerQueueItem[]=[];
 for(const subjectName of subjects){const subject=SUBJECTS[subjectName];if(!subject)continue;for(const topic of subject.topics){if(!covered.has(`${subjectName}::${topic.title}`)||!phaseAllows(subjectName,topic.title,active))continue;const p=progress.find(r=>r.subjectName===subjectName&&r.topicName===topic.title),weakHits=testMarks.filter(m=>m.subjectName===subjectName&&m.weakTopics.includes(topic.title)).length,reviewDue=Boolean(p?.nextRecallAt&&new Date(p.nextRecallAt).getTime()<=now),memoryHeavy=subjectName==="Biology";const mastery=(p?.knowledge??0)*.35+(p?.memory??0)*.35+(p?.performance??0)*.30;const score=mastery-Math.min(42,weakHits*12)-(reviewDue?24:0);queue.push({subjectName,topicName:topic.title,score,reviewDue,memoryHeavy,bucket:planningBucketFor(subjectName),classFocus:false})}}
 return queue.sort((a,b)=>a.score-b.score);
}

function currentOverride(classId:string,date:Date){return getRuntimeScheduleAdjustments().classWeekOverrides.find(x=>x.classId===classId&&x.weekStart===weekStartKey(date))}
function recentFocus(classId:string,date:Date){const target=new Date(`${weekStartKey(date)}T00:00:00`).getTime();return getRuntimeScheduleAdjustments().classWeekOverrides.filter(x=>x.classId===classId&&x.topicName).map(x=>({x,time:new Date(`${x.weekStart}T00:00:00`).getTime()})).filter(x=>x.time<=target&&target-x.time<=14*86400000).sort((a,b)=>b.time-a.time)[0]?.x}
function daysUntilClass(date:Date,c:ClassSchedule){const o=currentOverride(c.id,date);if(o?.status==="Missed")return Infinity;if(o?.status==="Rescheduled"&&o.rescheduledDate){const diff=Math.round((new Date(`${o.rescheduledDate}T00:00:00`).getTime()-new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime())/86400000);if(diff>=0)return diff}return(c.dayOfWeek-date.getDay()+7)%7}
function classPriority(queue:PlannerQueueItem[],date:Date,classes:ClassSchedule[]){return queue.map(item=>{let score=item.score,classFocus=false;for(const c of classes.filter(x=>x.subjectName===item.subjectName)){const focus=currentOverride(c.id,date)?.topicName?currentOverride(c.id,date):recentFocus(c.id,date);if(focus?.topicName===item.topicName){score-=34;classFocus=true}const until=daysUntilClass(date,c);if(until<=2)score-=8;if(c.classType==="Paper"&&until<=2)score-=12}return{...item,score,classFocus}}).sort((a,b)=>a.score-b.score)}

function appendClass(result:FixedBlock[],c:ClassSchedule,startTime:string,endTime:string,suffix=""){
 const start=parseTime(startTime),end=start+durationMinutes(startTime,endTime),travel=c.deliveryMode==="Physical"?Math.max(0,c.travelMinutes||90):0,review=Math.max(0,c.preReviewMinutes||30,c.classType==="Paper"?60:0),tag=suffix?`-${suffix}`:"";
 if(review)result.push({start:start-travel-review,end:start-travel,block:{id:`review-${c.id}${tag}`,type:"revision",title:c.classType==="Paper"?`Paper-class preparation · ${c.subjectName}`:`Pre-class review · ${c.subjectName}`,subjectName:c.subjectName,priority:"high"}});
 if(travel)result.push({start:start-travel,end:start,block:{id:`travel-out-${c.id}${tag}`,type:"travel",title:"Travel to class",subjectName:c.subjectName}});
 result.push({start,end,block:{id:`class-${c.id}${tag}`,type:"class",title:`${c.subjectName} · ${c.classType} class`,subtitle:c.deliveryMode,subjectName:c.subjectName}});
 if(travel)result.push({start:end,end:end+travel,block:{id:`travel-home-${c.id}${tag}`,type:"travel",title:"Travel home",subjectName:c.subjectName}})
}
function classBlocks(date:Date,classes:ClassSchedule[]){const out:FixedBlock[]=[],week=weekStartKey(date),day=localDateKey(date),overrides=getRuntimeScheduleAdjustments().classWeekOverrides;for(const c of classes){const o=overrides.find(x=>x.classId===c.id&&x.weekStart===week);if(o?.status==="Missed")continue;if(o?.status==="Rescheduled"){if(o.rescheduledDate===day&&o.startTime&&o.endTime)appendClass(out,c,o.startTime,o.endTime,`makeup-${o.id}`);continue}if(c.dayOfWeek===date.getDay())appendClass(out,c,c.startTime,c.endTime)}return out}
function protectedBlocks(date:Date):FixedBlock[]{const today=localDateKey(date);return getRuntimeScheduleAdjustments().protectedTimes.filter(x=>x.recurrence==="Weekly"?x.dayOfWeek===date.getDay():x.date===today).map(x=>({start:parseTime(x.startTime),end:parseTime(x.startTime)+durationMinutes(x.startTime,x.endTime),block:{id:`protected-${x.id}`,type:"free" as const,title:`Protected time · ${x.title}`,subtitle:"Unavailable time"}}))}

function targets(profile:StudentProfile,queue:PlannerQueueItem[]){const buckets=[...new Set(queue.map(x=>x.bucket))],prefs=getRuntimePlanningPreferences(),weekly=Math.max(7*60,Math.round((profile.selfStudyHours||3)*7*60));if(!buckets.length)return{} as Record<string,number>;const adjustments=prefs.weeklySubjectAdjustments,totalAdj=buckets.reduce((s,b)=>s+(adjustments[b]??0),0),base=Math.max(60,(weekly-totalAdj)/buckets.length);return Object.fromEntries(buckets.map(b=>[b,Math.max(60,base+(adjustments[b]??0))]))}
function choose(queue:PlannerQueueItem[],target:Record<string,number>,allocated:Record<string,number>,usage:Record<string,number>){const buckets=[...new Set(queue.map(x=>x.bucket))];if(!buckets.length)return undefined;const bucket=[...buckets].sort((a,b)=>((allocated[a]??0)/(target[a]||1))-((allocated[b]??0)/(target[b]||1)))[0];return queue.filter(x=>x.bucket===bucket).sort((a,b)=>(a.score+(usage[`${a.subjectName}::${a.topicName}`]??0)*10)-(b.score+(usage[`${b.subjectName}::${b.topicName}`]??0)*10))[0]}

export function generateDailyPlan(date:Date,profile:StudentProfile,classes:ClassSchedule[],progress:TopicProgress[],testMarks:TestMark[]=[],coverage:SubtopicCoverage[]=[],phase:PlannerPhaseOptions={}):PlanBlock[]{
 const active=resolvePhase(phase),prefs=getRuntimePlanningPreferences(),wake=parseTime(profile.wakeTime||"06:00");let sleep=parseTime(profile.sleepTime||"22:30");if(sleep<=wake)sleep+=1440;const examMode=active.phase==="Exam Month",mainMode=active.phase==="Main Exam Preparation",paperMode=active.phase==="Paper Practice";
 const fixed:FixedBlock[]=[{start:wake,end:wake+15,block:{id:"morning",type:"routine",title:"Wake up · morning routine"}},{start:clamp(12*60+30,wake+60,sleep-180),end:clamp(13*60+15,wake+105,sleep-135),block:{id:"lunch",type:"meal",title:"Lunch + reset"}},{start:clamp(19*60,wake+180,sleep-120),end:clamp(19*60+45,wake+225,sleep-75),block:{id:"dinner",type:"meal",title:"Dinner"}},{start:sleep-30,end:sleep,block:{id:"wind-down",type:"routine",title:"Wind down"}},...classBlocks(date,classes),...protectedBlocks(date)];
 const safe=mergeFixed(fixed.map(x=>({...x,start:Math.max(wake,x.start),end:Math.min(sleep,x.end)}))),classMinutes=safe.filter(x=>x.block.type==="class").reduce((s,x)=>s+x.end-x.start,0),desired=Math.min(12*60,Math.max(60,Math.round((profile.selfStudyHours||3)*60))),targetStudy=Math.max(0,(examMode?12*60:desired)-((examMode||prefs.countClassTimeTowardTarget)?classMinutes:0));
 const queue=classPriority(weaknessQueue(profile,progress,testMarks,coverage,active),date,classes),target=targets(profile,queue),allocated:Record<string,number>={},usage:Record<string,number>={};let studied=0,index=0,cursor=wake;const plan:PlanBlock[]=[];
 const fill=(start:number,end:number)=>{let p=start;while(p<end){const remaining=end-p,need=targetStudy-studied;if(need>0&&remaining>=45&&queue.length){const preferred=prefs.maxStudyBlockMinutes,length=Math.min(preferred,Math.max(45,Math.min(need,remaining>=preferred+15?preferred:remaining))),item=choose(queue,target,allocated,usage);if(!item)break;const key=`${item.subjectName}::${item.topicName}`,revision=item.reviewDue||item.classFocus||(mainMode&&index%3===1),paper=examMode||paperMode||(mainMode&&index%2===0);plan.push(block(`study-${localDateKey(date)}-${p}`,p,p+length,revision&&!paper?"revision":"study",paper?`Exam practice · ${item.topicName}`:item.topicName,{subtitle:paper?`${item.subjectName} · timed questions / paper practice`:revision?`${item.subjectName} · active recall${item.classFocus?" · review after class":""}`:`${item.subjectName} · focused study`,subjectName:item.subjectName,topicName:item.topicName,priority:item.score<50||item.reviewDue||item.classFocus?"high":"normal"}));studied+=length;allocated[item.bucket]=(allocated[item.bucket]??0)+length;usage[key]=(usage[key]??0)+1;index++;p+=length;if(end-p>=15){const b=Math.min(20,end-p);plan.push(block(`break-${localDateKey(date)}-${p}`,p,p+b,"break","Recovery break"));p+=b}continue}plan.push(block(`free-${localDateKey(date)}-${p}`,p,end,"free",queue.length?"Your own time":"Flexible study time",{subtitle:queue.length?"Target covered or not enough time for another useful block":"Mark lessons you have personally covered to let Study Arc schedule them"}));p=end}}
 for(const item of safe){if(item.start>cursor)fill(cursor,item.start);plan.push({...item.block,start:minutesToTime(item.start),end:minutesToTime(item.end)});cursor=Math.max(cursor,item.end)}if(cursor<sleep)fill(cursor,sleep);return plan.sort((a,b)=>parseTime(a.start)-parseTime(b.start))
}

export function generateBonusWork(profile:StudentProfile,progress:TopicProgress[],testMarks:TestMark[]=[],count=5,coverage:SubtopicCoverage[]=[],phase:PlannerPhaseOptions={}){return weaknessQueue(profile,progress,testMarks,coverage,phase).slice(0,Math.max(1,count)).map((item,index)=>({id:`bonus-${item.subjectName}-${item.topicName}`,subjectName:item.subjectName,topicName:item.topicName,title:item.reviewDue?`Recall · ${item.topicName}`:item.topicName,subtitle:item.reviewDue?`${item.subjectName} · memory review due`:`${item.subjectName} · priority practice`,studyType:(item.reviewDue||index%3===0?"Revision":"Study Session") as "Revision"|"Study Session"}))}
export function weeklySubjectMinutes(profile:StudentProfile,_classes:ClassSchedule[],plans:PlanBlock[][]){const result:Record<string,{selfStudy:number;classLearning:number;academic:number}>={};for(const subject of expandSubjectChoices(profile.subjectChoices))result[subject]={selfStudy:0,classLearning:0,academic:0};for(const b of plans.flat()){if(!b.subjectName)continue;const mins=durationMinutes(b.start,b.end);result[b.subjectName]??={selfStudy:0,classLearning:0,academic:0};if(b.type==="study"||b.type==="revision")result[b.subjectName].selfStudy+=mins;if(b.type==="class")result[b.subjectName].classLearning+=mins}for(const v of Object.values(result))v.academic=v.selfStudy+v.classLearning;return result}

export function recommendTaskNow(availableMinutes:number,profile:StudentProfile,progress:TopicProgress[],testMarks:TestMark[]=[],coverage:SubtopicCoverage[]=[],phase:PlannerPhaseOptions={}){const item=weaknessQueue(profile,progress,testMarks,coverage,phase)[0];if(!item)return null;const minutes=clamp(Math.floor(availableMinutes/15)*15,15,Math.min(availableMinutes,90));return{subjectName:item.subjectName,topicName:item.topicName,minutes,studyType:item.reviewDue?"Revision" as const:"Study Session" as const,reason:item.reviewDue?"Memory review is due":item.score<45?"This is currently one of your weakest covered topics":"This fits your available time and keeps subject balance moving"}}
export function recoverMissedBlock(block:PlanBlock,daysUntilDeadline:number,availableMinutes:number):MissedPlanDecision{const original=durationMinutes(block.start,block.end),high=block.priority==="high"||daysUntilDeadline<=3;if(!high&&daysUntilDeadline>10)return{action:"drop",reason:"Low priority and no near deadline; protect the remaining plan.",parts:[]};if(availableMinutes>=original)return{action:"reschedule",reason:"Enough free time remains to recover the full task.",parts:[original]};if(availableMinutes>=Math.max(60,original*.7))return{action:"reduce",reason:"Keep the highest-value part without pushing the whole timetable forward.",parts:[availableMinutes]};if(availableMinutes>=45&&original>=90)return{action:"split",reason:"Recover the task in smaller blocks across later free windows.",parts:[Math.min(60,availableMinutes),Math.max(30,original-Math.min(60,availableMinutes))]};return{action:high?"split":"drop",reason:high?"The task matters, so preserve a smaller recovery block.":"Not enough useful time remains for a low-priority recovery.",parts:high?[Math.max(30,availableMinutes)]:[]}}
