import {useEffect,useRef,useState} from 'react';
import {type Recall,clearLocalAudio,cloudAudioUri,deleteCloudRecall,legacyRecalls,listCloudRecalls,loadRecallCache,localAudioUri,removeLegacyRecall,mergeRecalls,saveLocalAudio,saveRecallCache,uploadRecall} from '../lib/audioRecallStorage';
export function useAudioRecalls(userId:string|undefined){
 const owner=userId??'guest';const ownerRef=useRef(owner);ownerRef.current=owner;
 const saveQueue=useRef(Promise.resolve());
 const [loadedOwner,setLoadedOwner]=useState<string|null>(null);
 const rowsRef=useRef<Recall[]>([]),lock=useRef(false),refreshLock=useRef<string|null>(null);
 const [recalls,setRecalls]=useState<Recall[]>([]),[legacy,setLegacy]=useState<Recall[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[syncing,setSyncing]=useState(false),[message,setMessage]=useState<string|null>(null);
 const persist=async(rows:Recall[])=>{if(ownerRef.current!==owner)return;rowsRef.current=rows;setRecalls(rows);const write=saveQueue.current.catch(()=>undefined).then(()=>saveRecallCache(owner,rows));saveQueue.current=write;await write};
 const refresh=async()=>{if(!userId||refreshLock.current===owner)return;refreshLock.current=owner;setSyncing(true);try{const remote=await listCloudRecalls(owner);if(ownerRef.current!==owner)return;await persist(mergeRecalls(rowsRef.current,remote.notes,remote.deletedIds));setMessage(null)}catch(e){if(ownerRef.current===owner)setMessage(e instanceof Error?e.message:'Could not sync recordings.')}finally{if(refreshLock.current===owner)refreshLock.current=null;if(ownerRef.current===owner)setSyncing(false)}};
 useEffect(()=>{let live=true;rowsRef.current=[];setRecalls([]);setLoading(true);setSyncing(false);setMessage(null);setLegacy([]);(async()=>{try{const rows=await loadRecallCache(owner);if(!live)return;rowsRef.current=rows;setRecalls(rows);const old=await legacyRecalls();if(live)setLegacy(old.filter(n=>!rows.some(r=>r.id===n.id)))}catch{if(live)setMessage('Could not read saved recordings.')}finally{if(live){setLoading(false);setLoadedOwner(owner)}}if(live)await refresh()})();return()=>{live=false}},[owner]);
 const syncNote=async(note:Recall)=>{if(!userId)throw new Error('Sign in to sync recordings across devices.');const synced=await uploadRecall(owner,note);if(ownerRef.current!==owner)return;await persist([synced,...rowsRef.current.filter(n=>n.id!==note.id)]);if(note.legacy)await removeLegacyRecall(note.id);if(ownerRef.current===owner){setLegacy(old=>old.filter(n=>n.id!==note.id));setMessage(null)}};
 const sync=async(note:Recall)=>{if(lock.current)return;lock.current=true;setBusy(note.id);try{await syncNote(note)}catch(e){setMessage(e instanceof Error?e.message:'Could not upload recording.')}finally{lock.current=false;setBusy(null)}};
 const add=async(note:Recall)=>{if(lock.current)throw new Error('Please wait for the current recording to finish saving.');lock.current=true;setBusy(note.id);try{let saved=note;try{saved=await saveLocalAudio(owner,note)}catch(e){setMessage('Recording kept for this session. Browser storage is unavailable; sync it before closing this page.')}await persist([saved,...rowsRef.current]);if(userId){try{await syncNote(saved)}catch(e){setMessage(e instanceof Error?e.message:'Saved on this device. Sync it again when online.')}}return saved}finally{lock.current=false;setBusy(null)}};
 const audio=async(note:Recall)=>{const local=await localAudioUri(owner,note).catch(()=>null);if(local)return local;if(!note.synced)throw new Error('The original audio is no longer available on this device.');const uri=await cloudAudioUri(owner,note);if(ownerRef.current===owner&&rowsRef.current.some(n=>n.id===note.id))await persist(rowsRef.current.map(n=>n.id===note.id?{...n,uri}:n));return uri};
 const remove=async(note:Recall)=>{if(lock.current)throw new Error('Please wait for the recording to finish syncing.');lock.current=true;setBusy(note.id);try{if(note.synced)await deleteCloudRecall(owner,note.id);await persist(rowsRef.current.filter(n=>n.id!==note.id));await clearLocalAudio(owner,note).catch(()=>undefined);if(note.legacy){const old=await legacyRecalls();await removeLegacyRecall(note.id);setLegacy(old.filter(n=>n.id!==note.id))}}finally{lock.current=false;setBusy(null)}};
 return {recalls:loadedOwner===owner?recalls:[],legacy:loadedOwner===owner?legacy:[],loading:loading||loadedOwner!==owner,busy,syncing,message,refresh,sync,add,audio,remove};
}
