import{Ionicons}from"@expo/vector-icons";
import React,{useMemo,useState}from"react";
import{Pressable,StyleSheet,Text,View}from"react-native";
import WeeklyTimetableModal from"../components/WeeklyTimetableModal";
import WeeklyWorkloadModal from"../components/WeeklyWorkloadModal";
import{useAcademic}from"../context/AcademicContext";
import{setRuntimeAssignments}from"../lib/timetableRuntime";
import PlanScreen from"./PlanScreen";

export default function PlanWithAssignments(){
 const{assignments}=useAcademic();const[workloadOpen,setWorkloadOpen]=useState(false),[tableOpen,setTableOpen]=useState(false);setRuntimeAssignments(assignments);const open=useMemo(()=>assignments.filter(a=>!a.completed),[assignments]),dueSoon=useMemo(()=>open.filter(a=>{if(!a.dueAt)return false;const diff=new Date(a.dueAt).getTime()-Date.now();return diff<=7*86400000}).length,[open]);
 return <View style={s.root}><View style={s.tools}><View style={s.inner}><View style={s.summary}><View style={s.icon}><Ionicons name="calendar-clear-outline" size={21} color="#D6BBF4"/></View><View style={{flex:1}}><Text style={s.eyebrow}>YOUR WEEK</Text><Text style={s.title}>Plan at a glance</Text><Text style={s.sub}>{open.length} open assignment{open.length===1?"":"s"} · classes, tasks, breaks and study share one adaptive week.</Text></View>{dueSoon?<View style={s.dueBadge}><Text style={s.dueValue}>{dueSoon}</Text><Text style={s.dueLabel}>DUE SOON</Text></View>:null}</View><View style={s.actions}><Pressable onPress={()=>setWorkloadOpen(true)} style={({pressed})=>[s.action,pressed&&s.pressed]}><View style={s.actionIcon}><Ionicons name="layers-outline" size={19} color="#D8BEF5"/></View><View style={{flex:1}}><Text style={s.actionText}>Weekly workload</Text><Text style={s.actionSub}>Assignments & repeating work</Text></View><Ionicons name="chevron-forward" size={18} color="#7C6C8B"/></Pressable><Pressable onPress={()=>setTableOpen(true)} style={({pressed})=>[s.action,pressed&&s.pressed]}><View style={s.actionIcon}><Ionicons name="grid-outline" size={19} color="#AFC8F4"/></View><View style={{flex:1}}><Text style={s.actionText}>Timetable view</Text><Text style={s.actionSub}>Optional 7-day table & PNG</Text></View><Ionicons name="chevron-forward" size={18} color="#7C6C8B"/></Pressable></View></View></View><View style={s.plan}><PlanScreen/></View><WeeklyWorkloadModal visible={workloadOpen} onClose={()=>setWorkloadOpen(false)}/><WeeklyTimetableModal visible={tableOpen} onClose={()=>setTableOpen(false)}/></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},tools:{backgroundColor:"#0C1219",borderBottomWidth:1,borderBottomColor:"#263442",padding:11},inner:{maxWidth:1000,width:"100%",alignSelf:"center"},summary:{flexDirection:"row",alignItems:"center",gap:10},icon:{width:45,height:45,borderRadius:14,backgroundColor:"#21182D",borderWidth:1,borderColor:"#3B2E49",alignItems:"center",justifyContent:"center"},eyebrow:{color:"#987DB3",fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:"#EEF1F4",fontSize:16,fontWeight:"900",marginTop:1},sub:{color:"#718092",fontSize:10.5,lineHeight:15,marginTop:3},dueBadge:{minWidth:60,height:48,borderRadius:13,backgroundColor:"#2B2116",borderWidth:1,borderColor:"#584124",alignItems:"center",justifyContent:"center"},dueValue:{color:"#F0BF78",fontSize:16,fontWeight:"900"},dueLabel:{color:"#9B7E54",fontSize:7,fontWeight:"900",marginTop:1},actions:{flexDirection:"row",gap:8,marginTop:10},action:{flex:1,minHeight:58,borderRadius:15,backgroundColor:"#171E28",borderWidth:1,borderColor:"#303C4B",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:8},actionIcon:{width:37,height:37,borderRadius:12,backgroundColor:"#21182D",alignItems:"center",justifyContent:"center"},actionText:{color:"#DDD3E8",fontSize:11.5,fontWeight:"900"},actionSub:{color:"#657285",fontSize:9,marginTop:2},pressed:{opacity:.76},plan:{flex:1}});
