import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React,{useMemo,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import Screen from"../components/Screen";
import{usePhase}from"../context/PhaseContext";
import{usePlanning}from"../context/PlanningContext";
import{useStudent}from"../context/StudentContext";
import{generateDailyPlan,type PlanBlock}from"../lib/planner";
import{durationMinutes,format12Hour,minutesLabel}from"../lib/time";
import{topicDisplayName}from"../data/subjects";

const iconFor:Record<PlanBlock["type"],keyof typeof Ionicons.glyphMap>={routine:"sparkles-outline",study:"book-outline",revision:"refresh-outline",break:"cafe-outline",class:"school-outline",travel:"car-outline",meal:"restaurant-outline",free:"leaf-outline"};
const addDay=(date:Date,delta:number)=>{const d=new Date(date);d.setDate(d.getDate()+delta);return d};
const sameDay=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();

export default function PlanScreen(){
 const router=useRouter();const{profile,classes,topicProgress,testMarks,subtopicCoverage}=useStudent();const{settings:phaseSettings}=usePhase();const{preferences}=usePlanning();const[selectedDate,setSelectedDate]=useState(new Date());
 const phaseOptions=useMemo(()=>({phase:phaseSettings.phase,examSubjects:phaseSettings.examSubjects,examTopics:phaseSettings.examTopics,doneSubjects:phaseSettings.doneSubjects}),[phaseSettings]);
 const plan=useMemo(()=>generateDailyPlan(selectedDate,profile,classes,topicProgress,testMarks,subtopicCoverage,phaseOptions),[classes,phaseOptions,preferences,profile,selectedDate,subtopicCoverage,testMarks,topicProgress]);
 const academicMinutes=plan.filter(b=>["study","revision","class"].includes(b.type)).reduce((sum,b)=>sum+durationMinutes(b.start,b.end),0);
 const studyMinutes=plan.filter(b=>["study","revision"].includes(b.type)).reduce((sum,b)=>sum+durationMinutes(b.start,b.end),0);
 const display=(b:PlanBlock)=>b.subjectName&&b.topicName?topicDisplayName(b.subjectName,b.topicName,profile.medium):b.title;
 return <Screen><LinearGradient colors={["#111021","#080D14","#080D14"]} style={StyleSheet.absoluteFill}/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.head}><View style={{flex:1}}><Text style={s.kicker}>DAILY TIMETABLE</Text><Text style={s.title}>{sameDay(selectedDate,new Date())?"Today":selectedDate.toLocaleDateString(undefined,{weekday:"long"})}</Text><Text style={s.sub}>{selectedDate.toLocaleDateString(undefined,{day:"numeric",month:"long",year:"numeric"})}</Text></View><Pressable onPress={()=>router.push("/planner-controls")} style={s.controls}><Ionicons name="options-outline" size={19} color="#DCC7F6"/></Pressable></View>
  <View style={s.dayNav}><Pressable onPress={()=>setSelectedDate(d=>addDay(d,-1))} style={s.nav}><Ionicons name="chevron-back" size={19} color="#B9C3CE"/></Pressable><Pressable onPress={()=>setSelectedDate(new Date())} style={s.today}><Text style={s.todayText}>TODAY</Text></Pressable><Pressable onPress={()=>setSelectedDate(d=>addDay(d,1))} style={s.nav}><Ionicons name="chevron-forward" size={19} color="#B9C3CE"/></Pressable></View>
  {preferences.catchUpMode?<View style={s.catchup}><Ionicons name="trail-sign-outline" size={18} color="#E5C5FF"/><View style={{flex:1}}><Text style={s.catchTitle}>Catch-up Mode is active</Text><Text style={s.catchSub}>Weak, overdue and recovery work receives stronger priority without increasing your available hours.</Text></View></View>:null}
  <View style={s.summary}><View><Text style={s.sumLabel}>ACADEMIC TIME</Text><Text style={s.sumValue}>{minutesLabel(academicMinutes)}</Text></View><View><Text style={s.sumLabel}>SELF-STUDY</Text><Text style={s.sumValue}>{minutesLabel(studyMinutes)}</Text></View><View><Text style={s.sumLabel}>PHASE</Text><Text style={s.sumValueSmall}>{phaseSettings.phase}</Text></View></View>
  <View style={s.timeline}>{plan.map((b,index)=><View key={b.id} style={[s.row,index!==plan.length-1&&s.border]}><View style={s.time}><Text style={s.start}>{format12Hour(b.start)}</Text><Text style={s.end}>{format12Hour(b.end)}</Text></View><View style={[s.icon,b.priority==="high"&&s.iconHigh]}><Ionicons name={iconFor[b.type]} size={17} color={b.type==="study"||b.type==="revision"?"#D2B4F5":"#8B98A8"}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{display(b)}</Text><Text style={s.rowSub}>{b.subtitle??b.type}</Text></View>{(b.type==="study"||b.type==="revision")?<Pressable onPress={()=>router.push({pathname:"/stopwatch",params:{subjectName:b.subjectName,topicName:b.topicName,studyType:b.type==="revision"?"Revision":"Study Session"}})} style={s.play}><Ionicons name="play" size={13} color="#160B20"/></Pressable>:null}</View>)}</View>
 </ScrollView></Screen>
}
const s=StyleSheet.create({content:{padding:20,paddingBottom:45,width:"100%",maxWidth:820,alignSelf:"center"},head:{flexDirection:"row",alignItems:"center",gap:11},kicker:{color:"#9E7BC8",fontSize:8,fontWeight:"900",letterSpacing:1.4},title:{color:"#F5F6F8",fontSize:28,fontWeight:"900",marginTop:4},sub:{color:"#748194",fontSize:10,marginTop:4},controls:{width:44,height:44,borderRadius:14,backgroundColor:"#21182D",borderWidth:1,borderColor:"#49365E",alignItems:"center",justifyContent:"center"},dayNav:{flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9,marginTop:16},nav:{width:42,height:42,borderRadius:13,backgroundColor:"#111923",borderWidth:1,borderColor:"#293646",alignItems:"center",justifyContent:"center"},today:{height:42,borderRadius:13,backgroundColor:"#1B1526",borderWidth:1,borderColor:"#4D3963",paddingHorizontal:18,alignItems:"center",justifyContent:"center"},todayText:{color:"#C9AFE8",fontSize:8.5,fontWeight:"900",letterSpacing:1},catchup:{minHeight:68,borderRadius:17,backgroundColor:"#20172A",borderWidth:1,borderColor:"#5C3F76",padding:12,flexDirection:"row",alignItems:"center",gap:10,marginTop:13},catchTitle:{color:"#E9D8FB",fontSize:11,fontWeight:"900"},catchSub:{color:"#887599",fontSize:8.8,lineHeight:13,marginTop:3},summary:{flexDirection:"row",gap:7,marginTop:13},sumLabel:{color:"#6E7C8E",fontSize:7,fontWeight:"900",letterSpacing:.9},sumValue:{color:"#F0F2F5",fontSize:16,fontWeight:"900",marginTop:5},sumValueSmall:{color:"#D7C3F2",fontSize:10,fontWeight:"900",marginTop:7},summaryItem:{flex:1},timeline:{marginTop:13,borderRadius:20,backgroundColor:"#0F161F",borderWidth:1,borderColor:"#273443",overflow:"hidden"},row:{minHeight:72,padding:11,flexDirection:"row",alignItems:"center",gap:9},border:{borderBottomWidth:1,borderBottomColor:"#222D39"},time:{width:75},start:{color:"#AAB5C2",fontSize:9,fontWeight:"900"},end:{color:"#5F6D7E",fontSize:8,marginTop:3},icon:{width:37,height:37,borderRadius:12,backgroundColor:"#17202B",alignItems:"center",justifyContent:"center"},iconHigh:{borderWidth:1,borderColor:"#60457E",backgroundColor:"#21182C"},rowTitle:{color:"#E7EAEE",fontSize:11,fontWeight:"900"},rowSub:{color:"#718092",fontSize:8.8,lineHeight:13,marginTop:3},play:{width:34,height:34,borderRadius:11,backgroundColor:"#B784FF",alignItems:"center",justifyContent:"center"}})
