import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React,{useEffect,useRef,useState}from"react";
import{BackHandler,FlatList,Modal,Platform,Pressable,StyleSheet,Text,View}from"react-native";
import Screen from "../components/Screen";
import{useSocial}from"../context/SocialContext";
import{useStudy,type PaperSection,type StudyType}from"../context/StudyContext";
import{clearActiveStudyTimer,elapsedFromPersistedTimer,readActiveStudyTimer,writeActiveStudyTimer,type PersistedStudyTimer}from"../lib/timerPersistence";

type Lap={id:number;number:number;duration:number;total:number};
const TYPES:StudyType[]=["Study Session","Revision","Tute Questions","Past Papers","Paper Review","Paper Correction","Paper Discussion","Class"];
const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v;
const fmt=(ms:number)=>{const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`};

export default function StopwatchMinimal(){
 const router=useRouter();const params=useLocalSearchParams<{subjectName?:string|string[];topicName?:string|string[];studyType?:string|string[];paperYear?:string|string[];paperSection?:string|string[];attemptNo?:string|string[];assignmentId?:string|string[];assignmentTitle?:string|string[]}>();
 const incomingType=one(params.studyType) as StudyType|undefined;const initialType=TYPES.includes(incomingType as StudyType)?incomingType as StudyType:"Study Session";
 const{addSession}=useStudy();const{setStudying}=useSocial();
 const[subjectName,setSubjectName]=useState<string|null>(one(params.subjectName)??null),[topicName,setTopicName]=useState<string|null>(one(params.topicName)??null),[studyType,setStudyType]=useState<StudyType>(initialType),[paperYear,setPaperYear]=useState<number|null>(one(params.paperYear)?Number(one(params.paperYear)):null),[paperSection,setPaperSection]=useState<PaperSection|null>((["MCQ","Essay","Full Paper"] as string[]).includes(one(params.paperSection)??"")?one(params.paperSection) as PaperSection:null),[attemptNo,setAttemptNo]=useState<number|null>(one(params.attemptNo)?Number(one(params.attemptNo)):null);
 const[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false),[laps,setLaps]=useState<Lap[]>([]),[lapStart,setLapStart]=useState(0),[simple,setSimple]=useState(true),[confirmOpen,setConfirmOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const startedAt=useRef(new Date()),runStarted=useRef<number|null>(null),accumulated=useRef(0),timer=useRef<ReturnType<typeof setInterval>|null>(null);
 const currentLap=Math.max(0,elapsed-lapStart);
 const nowElapsed=()=>runStarted.current==null?accumulated.current:accumulated.current+(Date.now()-runStarted.current);
 const persist=(isRunning=running,currentAccum=accumulated.current,currentStart=runStarted.current,nextLaps=laps,nextLapStart=lapStart)=>{const snap:PersistedStudyTimer={version:1,running:isRunning,accumulatedMilliseconds:currentAccum,runStartedAtEpoch:currentStart,sessionStartedAtIso:startedAt.current.toISOString(),lapStartedAtMilliseconds:nextLapStart,laps:nextLaps,subjectName,topicName,studyType,paperYear,paperSection,attemptNo,updatedAtEpoch:Date.now()};writeActiveStudyTimer(snap).catch(()=>undefined)};
 useEffect(()=>{let live=true;(async()=>{const saved=await readActiveStudyTimer();if(!live||!saved)return;startedAt.current=new Date(saved.sessionStartedAtIso);accumulated.current=saved.accumulatedMilliseconds;runStarted.current=saved.running?saved.runStartedAtEpoch:null;setElapsed(elapsedFromPersistedTimer(saved));setLapStart(saved.lapStartedAtMilliseconds);setLaps(saved.laps??[]);setRunning(saved.running);setSubjectName(saved.subjectName??null);setTopicName(saved.topicName??null);setStudyType(saved.studyType??"Study Session");setPaperYear(saved.paperYear??null);setPaperSection(saved.paperSection??null);setAttemptNo(saved.attemptNo??null);if(saved.running){timer.current=setInterval(()=>setElapsed(nowElapsed()),250);setStudying(true,saved.subjectName??undefined,saved.topicName??undefined).catch(()=>undefined)}})();return()=>{live=false;if(timer.current)clearInterval(timer.current)}},[]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setStudying(true,subjectName??undefined,topicName??undefined).catch(()=>undefined),60000);return()=>clearInterval(id)},[running,setStudying,subjectName,topicName]);
 const home=()=>router.replace("/(tabs)");
 useEffect(()=>{if(Platform.OS==="web")return;const sub=BackHandler.addEventListener("hardwareBackPress",()=>{home();return true});return()=>sub.remove()},[router]);
 const start=()=>{if(running)return;if(elapsed===0){startedAt.current=new Date();accumulated.current=0}else accumulated.current=elapsed;const epoch=Date.now();runStarted.current=epoch;setRunning(true);if(timer.current)clearInterval(timer.current);timer.current=setInterval(()=>setElapsed(nowElapsed()),250);persist(true,accumulated.current,epoch);setStudying(true,subjectName??undefined,topicName??undefined).catch(()=>undefined)};
 const pause=()=>{if(!running)return elapsed;const final=nowElapsed();accumulated.current=final;runStarted.current=null;setElapsed(final);if(timer.current){clearInterval(timer.current);timer.current=null}setRunning(false);persist(false,final,null);setStudying(false).catch(()=>undefined);return final};
 const flagLap=()=>{const total=running?nowElapsed():elapsed,part=Math.max(0,total-lapStart);if(part<=0)return;const lap={id:Date.now(),number:laps.length+1,duration:part,total};const next=[lap,...laps];setElapsed(total);setLaps(next);setLapStart(total);persist(running,running?accumulated.current:total,running?runStarted.current:null,next,total)};
 const resetCurrent=()=>{const total=running?nowElapsed():elapsed;if(total<=lapStart)return;setElapsed(total);setLapStart(total);persist(running,running?accumulated.current:total,running?runStarted.current:null,laps,total)};
 const save=async()=>{if(saving)return;setSaving(true);setError(null);try{const final=running?pause():elapsed,durationSeconds=Math.floor(final/1000);if(durationSeconds<=0){await clearActiveStudyTimer();home();return}const id=await addSession({subjectName:subjectName??"Quick Study",topicName:topicName??"General",studyType,startedAt:startedAt.current.toISOString(),durationSeconds,paperYear,paperSection,attemptNo,laps:laps.map(x=>({number:x.number,duration:x.duration,total:x.total}))});await clearActiveStudyTimer();await setStudying(false).catch(()=>undefined);router.replace({pathname:"/session-complete",params:{sessionId:id,duration:String(durationSeconds),subjectName:subjectName??"Quick Study",topicName:topicName??"General",studyType,assignmentId:one(params.assignmentId),assignmentTitle:one(params.assignmentTitle)}})}catch(e){setError(e instanceof Error?e.message:"Could not save this session.");setConfirmOpen(false)}finally{setSaving(false)}};
 const discard=async()=>{if(running)pause();await clearActiveStudyTimer();await setStudying(false).catch(()=>undefined);home()};
 return <Screen><View style={s.root}><View style={s.top}><Pressable onPress={home} style={s.back}><Ionicons name="arrow-back" size={20} color="#EFF2F5"/></Pressable><View style={s.toggle}><Pressable onPress={()=>setSimple(false)} style={[s.toggleButton,!simple&&s.toggleOn]}><Text style={[s.toggleText,!simple&&s.toggleTextOn]}>Normal</Text></Pressable><Pressable onPress={()=>setSimple(true)} style={[s.toggleButton,simple&&s.toggleOn]}><Text style={[s.toggleText,simple&&s.toggleTextOn]}>Simple</Text></Pressable></View></View>
 <View style={s.center}><Text style={s.clock}>{fmt(currentLap)}</Text>{!simple?<><Text style={s.activity}>{studyType}</Text><Text style={s.total}>TOTAL · {fmt(elapsed)}</Text></>:null}<View style={s.controls}>{running?<Pressable onPress={pause} style={s.main}><Ionicons name="pause" size={27} color="#160B20"/></Pressable>:<Pressable onPress={start} style={s.main}><Ionicons name="play" size={27} color="#160B20"/></Pressable>}<Pressable onPress={flagLap} disabled={currentLap<=0} style={[s.side,currentLap<=0&&s.dim]}><Ionicons name="flag-outline" size={22} color="#D9C2F4"/></Pressable><Pressable onPress={()=>setConfirmOpen(true)} style={s.stop}><Ionicons name="stop" size={21} color="#F2B3BC"/></Pressable></View>{!simple&&currentLap>0?<Pressable onPress={resetCurrent} style={s.reset}><Ionicons name="refresh-outline" size={15} color="#8E9AAC"/><Text style={s.resetText}>Reset current lap</Text></Pressable>:null}{error?<Text style={s.error}>{error}</Text>:null}{!simple&&laps.length?<FlatList data={laps} keyExtractor={x=>String(x.id)} style={s.laps} renderItem={({item})=><View style={s.lapRow}><Text style={s.lapNo}>FLAG {item.number}</Text><Text style={s.lapTime}>{fmt(item.duration)}</Text></View>}/>:null}</View>
 <Modal visible={confirmOpen} transparent animationType="fade" onRequestClose={()=>setConfirmOpen(false)}><View style={s.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setConfirmOpen(false)}/><View style={s.modal}><Text style={s.modalTitle}>Finish this session?</Text><Text style={s.modalText}>Save the full session, or discard it without adding study time.</Text><Pressable disabled={saving} onPress={save} style={s.save}><Text style={s.saveText}>{saving?"Saving…":"Save session"}</Text></Pressable><Pressable disabled={saving} onPress={discard} style={s.discard}><Text style={s.discardText}>Discard session</Text></Pressable><Pressable disabled={saving} onPress={()=>setConfirmOpen(false)} style={s.keep}><Text style={s.keepText}>Keep studying</Text></Pressable></View></View></Modal>
 </View></Screen>
}

const s=StyleSheet.create({root:{flex:1,backgroundColor:"#080D14"},top:{height:70,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:42,height:42,borderRadius:14,backgroundColor:"#121A24",alignItems:"center",justifyContent:"center"},toggle:{flexDirection:"row",backgroundColor:"#111923",borderRadius:13,padding:3,borderWidth:1,borderColor:"#293646"},toggleButton:{height:34,borderRadius:10,paddingHorizontal:12,alignItems:"center",justifyContent:"center"},toggleOn:{backgroundColor:"#34244A"},toggleText:{color:"#708092",fontSize:9,fontWeight:"900"},toggleTextOn:{color:"#E9DDF7"},center:{flex:1,alignItems:"center",justifyContent:"center",paddingHorizontal:22,paddingBottom:45},clock:{color:"#F4F6F8",fontSize:56,fontWeight:"300",fontVariant:["tabular-nums"],letterSpacing:2},activity:{color:"#A98BCD",fontSize:10,fontWeight:"900",letterSpacing:1.3,marginTop:14},total:{color:"#68778A",fontSize:9,fontWeight:"900",letterSpacing:1,marginTop:5},controls:{flexDirection:"row",alignItems:"center",gap:13,marginTop:34},main:{width:76,height:76,borderRadius:38,backgroundColor:"#B784FF",alignItems:"center",justifyContent:"center"},side:{width:58,height:58,borderRadius:29,backgroundColor:"#1C1625",borderWidth:1,borderColor:"#4A385E",alignItems:"center",justifyContent:"center"},stop:{width:58,height:58,borderRadius:29,backgroundColor:"#28171D",borderWidth:1,borderColor:"#5B303B",alignItems:"center",justifyContent:"center"},dim:{opacity:.35},reset:{flexDirection:"row",alignItems:"center",gap:6,marginTop:16},resetText:{color:"#7A8797",fontSize:9,fontWeight:"800"},error:{color:"#E7A4AF",fontSize:10,textAlign:"center",marginTop:14},laps:{width:"100%",maxWidth:360,maxHeight:180,marginTop:18},lapRow:{height:39,borderBottomWidth:1,borderBottomColor:"#1E2935",flexDirection:"row",alignItems:"center",justifyContent:"space-between"},lapNo:{color:"#667588",fontSize:8,fontWeight:"900"},lapTime:{color:"#B8C2CD",fontSize:11,fontWeight:"800",fontVariant:["tabular-nums"]},overlay:{flex:1,backgroundColor:"rgba(3,6,10,.8)",alignItems:"center",justifyContent:"center",padding:20},modal:{width:"100%",maxWidth:390,borderRadius:24,backgroundColor:"#101720",borderWidth:1,borderColor:"#344154",padding:20},modalTitle:{color:"#F2F4F7",fontSize:20,fontWeight:"900",textAlign:"center"},modalText:{color:"#788697",fontSize:10,lineHeight:16,textAlign:"center",marginTop:7,marginBottom:17},save:{height:49,borderRadius:15,backgroundColor:"#B784FF",alignItems:"center",justifyContent:"center"},saveText:{color:"#160B20",fontSize:11,fontWeight:"900"},discard:{height:46,borderRadius:14,backgroundColor:"#28171D",alignItems:"center",justifyContent:"center",marginTop:8},discardText:{color:"#EEAFB9",fontSize:10,fontWeight:"900"},keep:{height:42,alignItems:"center",justifyContent:"center",marginTop:4},keepText:{color:"#8B99AA",fontSize:9,fontWeight:"900"}})