import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React,{useEffect,useRef,useState}from"react";
import{BackHandler,Modal,Platform,Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import Screen from "../components/Screen";
import{useSocial}from"../context/SocialContext";
import{useStudy,type PaperSection,type StudyType}from"../context/StudyContext";
import{clearActiveStudyTimer,elapsedFromPersistedTimer,readActiveStudyTimer,writeActiveStudyTimer,type PersistedStudyTimer}from"../lib/timerPersistence";

type Lap={id:number;number:number;duration:number;total:number};
const TYPES:StudyType[]=["Study Session","Revision","Tute Questions","Past Papers","Paper Review","Paper Correction","Paper Discussion","Class"];
const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v;
const fmt=(ms:number)=>{const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`};

export default function StopwatchMinimal(){
 const router=useRouter();
 const params=useLocalSearchParams<{subjectName?:string|string[];topicName?:string|string[];studyType?:string|string[];paperYear?:string|string[];paperSection?:string|string[];attemptNo?:string|string[];assignmentId?:string|string[];assignmentTitle?:string|string[];targetMinutes?:string|string[];markAfter?:string|string[]}>();
 const incomingType=one(params.studyType) as StudyType|undefined;
 const initialType=TYPES.includes(incomingType as StudyType)?incomingType as StudyType:"Study Session";
 const{addSession}=useStudy();
 const{setStudying}=useSocial();
 const[subjectName,setSubjectName]=useState<string|null>(one(params.subjectName)??null);
 const[topicName,setTopicName]=useState<string|null>(one(params.topicName)??null);
 const[studyType,setStudyType]=useState<StudyType>(initialType);
 const[paperYear,setPaperYear]=useState<number|null>(one(params.paperYear)?Number(one(params.paperYear)):null);
 const[paperSection,setPaperSection]=useState<PaperSection|null>((["MCQ","Essay","Full Paper"] as string[]).includes(one(params.paperSection)??"")?one(params.paperSection) as PaperSection:null);
 const[attemptNo,setAttemptNo]=useState<number|null>(one(params.attemptNo)?Number(one(params.attemptNo)):null);
 const[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false),[laps,setLaps]=useState<Lap[]>([]),[lapStart,setLapStart]=useState(0);
 const[detailsOpen,setDetailsOpen]=useState(false),[finishOpen,setFinishOpen]=useState(false),[discardOpen,setDiscardOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const startedAt=useRef(new Date()),runStarted=useRef<number|null>(null),accumulated=useRef(0),timer=useRef<ReturnType<typeof setInterval>|null>(null);
 const currentBlock=Math.max(0,elapsed-lapStart);
 const nowElapsed=()=>runStarted.current==null?accumulated.current:accumulated.current+(Date.now()-runStarted.current);
 const persist=(isRunning=running,currentAccum=accumulated.current,currentStart=runStarted.current,nextLaps=laps,nextLapStart=lapStart)=>{const snap:PersistedStudyTimer={version:1,running:isRunning,accumulatedMilliseconds:currentAccum,runStartedAtEpoch:currentStart,sessionStartedAtIso:startedAt.current.toISOString(),lapStartedAtMilliseconds:nextLapStart,laps:nextLaps,subjectName,topicName,studyType,paperYear,paperSection,attemptNo,updatedAtEpoch:Date.now()};writeActiveStudyTimer(snap).catch(()=>undefined)};

 useEffect(()=>{let live=true;(async()=>{const saved=await readActiveStudyTimer();if(!live||!saved)return;startedAt.current=new Date(saved.sessionStartedAtIso);accumulated.current=saved.accumulatedMilliseconds;runStarted.current=saved.running?saved.runStartedAtEpoch:null;setElapsed(elapsedFromPersistedTimer(saved));setLapStart(saved.lapStartedAtMilliseconds);setLaps(saved.laps??[]);setRunning(saved.running);setSubjectName(saved.subjectName??null);setTopicName(saved.topicName??null);setStudyType(saved.studyType??"Study Session");setPaperYear(saved.paperYear??null);setPaperSection(saved.paperSection??null);setAttemptNo(saved.attemptNo??null);if(saved.running){timer.current=setInterval(()=>setElapsed(nowElapsed()),250);setStudying(true,saved.subjectName??undefined,saved.topicName??undefined).catch(()=>undefined)}})();return()=>{live=false;if(timer.current)clearInterval(timer.current)}},[]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setStudying(true,subjectName??undefined,topicName??undefined).catch(()=>undefined),60000);return()=>clearInterval(id)},[running,setStudying,subjectName,topicName]);

 const home=()=>router.replace("/(tabs)");
 const requestExit=()=>{if(elapsed>0||running){setFinishOpen(true);return}home()};
 useEffect(()=>{if(Platform.OS==="web")return;const sub=BackHandler.addEventListener("hardwareBackPress",()=>{requestExit();return true});return()=>sub.remove()},[elapsed,running]);

 const start=()=>{if(running)return;if(elapsed===0){startedAt.current=new Date();accumulated.current=0}else accumulated.current=elapsed;const epoch=Date.now();runStarted.current=epoch;setRunning(true);setError(null);if(timer.current)clearInterval(timer.current);timer.current=setInterval(()=>setElapsed(nowElapsed()),250);persist(true,accumulated.current,epoch);setStudying(true,subjectName??undefined,topicName??undefined).catch(()=>undefined)};
 const pause=()=>{if(!running)return elapsed;const final=nowElapsed();accumulated.current=final;runStarted.current=null;setElapsed(final);if(timer.current){clearInterval(timer.current);timer.current=null}setRunning(false);persist(false,final,null);setStudying(false).catch(()=>undefined);return final};
 const toggleRun=()=>running?pause():start();
 const markBlock=()=>{const total=running?nowElapsed():elapsed,part=Math.max(0,total-lapStart);if(part<=0)return;const lap={id:Date.now(),number:laps.length+1,duration:part,total};const next=[lap,...laps];setElapsed(total);setLaps(next);setLapStart(total);persist(running,running?accumulated.current:total,running?runStarted.current:null,next,total)};
 const freshBlock=()=>{const total=running?nowElapsed():elapsed;if(total<=lapStart)return;setElapsed(total);setLapStart(total);persist(running,running?accumulated.current:total,running?runStarted.current:null,laps,total)};
 const save=async()=>{if(saving)return;setSaving(true);setError(null);try{const final=running?pause():elapsed,durationSeconds=Math.floor(final/1000);if(durationSeconds<=0){await clearActiveStudyTimer();home();return}const id=await addSession({subjectName:subjectName??"Quick Study",topicName:topicName??"General",studyType,startedAt:startedAt.current.toISOString(),durationSeconds,paperYear,paperSection,attemptNo,laps:laps.map(x=>({number:x.number,duration:x.duration,total:x.total}))});await clearActiveStudyTimer();await setStudying(false).catch(()=>undefined);router.replace({pathname:"/session-complete",params:{sessionId:id,duration:String(durationSeconds),subjectName:subjectName??"Quick Study",topicName:topicName??"General",studyType,assignmentId:one(params.assignmentId),assignmentTitle:one(params.assignmentTitle),paperYear:paperYear?String(paperYear):undefined,paperSection:paperSection??undefined,targetMinutes:one(params.targetMinutes),markAfter:one(params.markAfter)}})}catch(e){setError(e instanceof Error?e.message:"Could not save this session.");setFinishOpen(false)}finally{setSaving(false)}};
 const discard=async()=>{if(running)pause();await clearActiveStudyTimer();await setStudying(false).catch(()=>undefined);setDiscardOpen(false);setFinishOpen(false);home()};
 const sessionName=one(params.assignmentTitle)??topicName??subjectName??"Quick Study";
 const contextLine=[subjectName,topicName&&topicName!=="General"?topicName:null].filter(Boolean).join(" · ");
 const totalNow=running?nowElapsed():elapsed;

 return <Screen><View style={s.root}>
  <View style={s.top}><Pressable onPress={requestExit} style={s.back} accessibilityLabel="Back"><Ionicons name="arrow-back" size={20} color="#EFF2F5"/></Pressable><View style={s.typeBadge}><Ionicons name="book-outline" size={14} color="#CBB3E8"/><Text style={s.typeBadgeText}>{studyType}</Text></View><Pressable onPress={()=>setDetailsOpen(v=>!v)} style={s.detailsToggle}><Ionicons name={detailsOpen?"chevron-up":"options-outline"} size={17} color="#C9B0E7"/><Text style={s.detailsToggleText}>{detailsOpen?"Less":"Details"}</Text></Pressable></View>

  <ScrollView contentContainerStyle={s.center} showsVerticalScrollIndicator={false}>
   <View style={[s.statusPill,running&&s.statusPillLive]}><View style={[s.statusDot,running&&s.statusDotLive]}/><Text style={[s.statusText,running&&s.statusTextLive]}>{running?"FOCUSING NOW":elapsed>0?"PAUSED":"READY"}</Text></View>
   <Text style={s.sessionTitle} numberOfLines={2}>{sessionName}</Text>
   {contextLine&&contextLine!==sessionName?<Text style={s.context} numberOfLines={1}>{contextLine}</Text>:null}

   <View style={[s.timerCard,running&&s.timerCardLive]}>
    <Text style={s.clock}>{fmt(totalNow)}</Text>
    <Text style={s.clockLabel}>{running?"SESSION TIME":"TOTAL SESSION TIME"}</Text>
    {laps.length>0?<View style={s.blockLine}><Ionicons name="flag-outline" size={15} color="#A990C6"/><Text style={s.blockLineText}>Current block {fmt(currentBlock)} · {laps.length} saved block{laps.length===1?"":"s"}</Text></View>:null}
   </View>

   <View style={s.mainActions}>
    <Pressable onPress={toggleRun} style={[s.primaryAction,running&&s.pauseAction]} accessibilityRole="button"><View style={s.primaryIcon}><Ionicons name={running?"pause":"play"} size={26} color="#160B20"/></View><View style={{flex:1}}><Text style={s.primaryLabel}>{running?"Pause":elapsed>0?"Resume":"Start studying"}</Text><Text style={s.primaryHint}>{running?"Timer stays saved while paused":elapsed>0?"Continue this same session":"Start tracking this study session"}</Text></View></Pressable>
    <Pressable disabled={elapsed<=0&&!running} onPress={()=>setFinishOpen(true)} style={[s.finishAction,elapsed<=0&&!running&&s.dim]}><Ionicons name="checkmark-circle-outline" size={21} color="#9ADAAF"/><Text style={s.finishLabel}>Finish & save</Text><Ionicons name="chevron-forward" size={18} color="#678073"/></Pressable>
   </View>

   {detailsOpen?<View style={s.detailsCard}>
    <View style={s.detailGrid}><View style={s.detailCell}><Text style={s.detailLabel}>TYPE</Text><Text style={s.detailValue}>{studyType}</Text></View><View style={s.detailCell}><Text style={s.detailLabel}>BLOCKS</Text><Text style={s.detailValue}>{laps.length}</Text></View><View style={s.detailCell}><Text style={s.detailLabel}>CURRENT BLOCK</Text><Text style={s.detailValue}>{fmt(currentBlock)}</Text></View></View>
    <Text style={s.advancedTitle}>ADVANCED TIMER TOOLS</Text><Text style={s.advancedHelp}>Use blocks only when you want lap-style timing. Most sessions do not need these controls.</Text>
    <View style={s.advancedRow}><Pressable onPress={markBlock} disabled={currentBlock<=0} style={[s.advancedButton,currentBlock<=0&&s.dim]}><Ionicons name="flag-outline" size={18} color="#D6BDED"/><Text style={s.advancedButtonText}>Save current block</Text></Pressable><Pressable onPress={freshBlock} disabled={currentBlock<=0} style={[s.advancedButton,currentBlock<=0&&s.dim]}><Ionicons name="refresh-outline" size={18} color="#D6BDED"/><Text style={s.advancedButtonText}>Restart block</Text></Pressable></View>
    {laps.length?<View style={s.blockList}><Text style={s.blockListTitle}>SAVED BLOCKS</Text>{laps.map(item=><View key={item.id} style={s.blockRow}><View style={s.blockBadge}><Text style={s.blockBadgeText}>{item.number}</Text></View><Text style={s.blockName}>Block {item.number}</Text><Text style={s.blockTime}>{fmt(item.duration)}</Text></View>)}</View>:null}
   </View>:null}

   {error?<View style={s.errorCard}><Ionicons name="alert-circle-outline" size={18} color="#E7A4AF"/><View style={{flex:1}}><Text style={s.errorTitle}>Could not save</Text><Text style={s.error}>{error}</Text></View></View>:null}
   <Text style={s.reassurance}>Your timer is saved automatically. You can pause, leave the app, and continue later.</Text>
  </ScrollView>

  <Modal visible={finishOpen} transparent animationType="fade" onRequestClose={()=>setFinishOpen(false)}><View style={s.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setFinishOpen(false)}/><View style={s.modal}>
   <View style={s.modalIcon}><Ionicons name="checkmark-done-outline" size={28} color="#AEE1BF"/></View><Text style={s.modalEyebrow}>SESSION COMPLETE</Text><Text style={s.modalTitle}>Save this study session?</Text><Text style={s.modalTime}>{fmt(totalNow)}</Text><Text style={s.modalText}>StudyArc will add this time to your progress and open the session review screen.</Text>
   <Pressable disabled={saving} onPress={save} style={[s.save,saving&&s.dim]}><Ionicons name="checkmark" size={18} color="#160B20"/><Text style={s.saveText}>{saving?"Saving…":"Save session"}</Text></Pressable>
   <Pressable disabled={saving} onPress={()=>setFinishOpen(false)} style={s.keep}><Ionicons name="play-outline" size={17} color="#C9B0E7"/><Text style={s.keepText}>Keep studying</Text></Pressable>
   <Pressable disabled={saving} onPress={()=>setDiscardOpen(true)} style={s.discardLink}><Text style={s.discardLinkText}>Discard session</Text></Pressable>
  </View></View></Modal>

  <Modal visible={discardOpen} transparent animationType="fade" onRequestClose={()=>setDiscardOpen(false)}><View style={s.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setDiscardOpen(false)}/><View style={s.modal}><View style={[s.modalIcon,s.dangerIcon]}><Ionicons name="trash-outline" size={26} color="#ECAAB5"/></View><Text style={s.modalTitle}>Discard this session?</Text><Text style={s.modalText}>This deletes the unsaved timer and does not add study time. This cannot be undone.</Text><Pressable onPress={discard} style={s.discard}><Text style={s.discardText}>Discard session</Text></Pressable><Pressable onPress={()=>setDiscardOpen(false)} style={s.keep}><Text style={s.keepText}>Cancel</Text></Pressable></View></View></Modal>
 </View></Screen>
}

const s=StyleSheet.create({
 root:{flex:1,backgroundColor:"#080D14"},top:{height:68,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:9,borderBottomWidth:1,borderBottomColor:"#17212B"},back:{width:42,height:42,borderRadius:14,backgroundColor:"#121A24",borderWidth:1,borderColor:"#24303C",alignItems:"center",justifyContent:"center"},typeBadge:{flex:1,minHeight:38,borderRadius:13,backgroundColor:"#111923",borderWidth:1,borderColor:"#263341",paddingHorizontal:11,flexDirection:"row",alignItems:"center",gap:7},typeBadgeText:{color:"#C5CDD7",fontSize:9,fontWeight:"900"},detailsToggle:{height:38,borderRadius:13,backgroundColor:"#1B1624",borderWidth:1,borderColor:"#3D304A",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:5},detailsToggleText:{color:"#C9B0E7",fontSize:8.5,fontWeight:"900"},
 center:{flexGrow:1,alignItems:"center",paddingHorizontal:18,paddingTop:26,paddingBottom:34,maxWidth:620,width:"100%",alignSelf:"center"},statusPill:{height:30,borderRadius:15,backgroundColor:"#171F29",borderWidth:1,borderColor:"#2B3745",paddingHorizontal:12,flexDirection:"row",alignItems:"center",gap:6},statusPillLive:{backgroundColor:"#13231A",borderColor:"#2E6040"},statusDot:{width:6,height:6,borderRadius:3,backgroundColor:"#718092"},statusDotLive:{backgroundColor:"#79D09A"},statusText:{color:"#7D8A9A",fontSize:7.5,fontWeight:"900",letterSpacing:1},statusTextLive:{color:"#8FD4A7"},sessionTitle:{maxWidth:540,color:"#F3F5F7",fontSize:20,fontWeight:"900",textAlign:"center",marginTop:16},context:{maxWidth:520,color:"#788698",fontSize:9.5,fontWeight:"800",marginTop:5,textAlign:"center"},
 timerCard:{width:"100%",borderRadius:28,backgroundColor:"#0E151E",borderWidth:1,borderColor:"#263341",paddingVertical:27,paddingHorizontal:16,alignItems:"center",marginTop:22},timerCardLive:{backgroundColor:"#101B17",borderColor:"#28533A"},clock:{color:"#F7F8FA",fontSize:62,fontWeight:"300",fontVariant:["tabular-nums"],letterSpacing:1.2},clockLabel:{color:"#6F7D8E",fontSize:8,fontWeight:"900",letterSpacing:1.2,marginTop:5},blockLine:{minHeight:34,borderRadius:12,backgroundColor:"#161C26",paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:6,marginTop:14},blockLineText:{color:"#8F819F",fontSize:8.5,fontWeight:"800"},
 mainActions:{width:"100%",marginTop:16,gap:9},primaryAction:{minHeight:74,borderRadius:22,backgroundColor:"#B784FF",padding:13,flexDirection:"row",alignItems:"center",gap:12},pauseAction:{backgroundColor:"#F0C779"},primaryIcon:{width:48,height:48,borderRadius:16,backgroundColor:"#FFFFFF40",alignItems:"center",justifyContent:"center"},primaryLabel:{color:"#160B20",fontSize:15,fontWeight:"900"},primaryHint:{color:"#3A244A",fontSize:8.5,fontWeight:"700",marginTop:3},finishAction:{height:54,borderRadius:17,backgroundColor:"#111B17",borderWidth:1,borderColor:"#2C573D",paddingHorizontal:14,flexDirection:"row",alignItems:"center",gap:8},finishLabel:{flex:1,color:"#AEE1BF",fontSize:10.5,fontWeight:"900"},dim:{opacity:.45},
 detailsCard:{width:"100%",borderRadius:20,backgroundColor:"#101720",borderWidth:1,borderColor:"#2B3745",padding:14,marginTop:14},detailGrid:{flexDirection:"row",gap:7},detailCell:{flex:1,minHeight:62,borderRadius:14,backgroundColor:"#0B1119",padding:10,justifyContent:"center"},detailLabel:{color:"#687587",fontSize:7,fontWeight:"900",letterSpacing:.8},detailValue:{color:"#E1E6EB",fontSize:10,fontWeight:"900",marginTop:5},advancedTitle:{color:"#8A769F",fontSize:7.5,fontWeight:"900",letterSpacing:1,marginTop:16},advancedHelp:{color:"#687587",fontSize:8.5,lineHeight:13,marginTop:4},advancedRow:{flexDirection:"row",gap:8,marginTop:10},advancedButton:{flex:1,minHeight:44,borderRadius:13,backgroundColor:"#1A1524",borderWidth:1,borderColor:"#433451",paddingHorizontal:9,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},advancedButtonText:{color:"#D3BCEB",fontSize:8.5,fontWeight:"900"},blockList:{marginTop:15},blockListTitle:{color:"#687587",fontSize:7.5,fontWeight:"900",letterSpacing:.9,marginBottom:5},blockRow:{minHeight:42,borderTopWidth:1,borderTopColor:"#202B37",flexDirection:"row",alignItems:"center",gap:8},blockBadge:{width:26,height:26,borderRadius:9,backgroundColor:"#2C2039",alignItems:"center",justifyContent:"center"},blockBadgeText:{color:"#D9C2F4",fontSize:8,fontWeight:"900"},blockName:{flex:1,color:"#C7CED7",fontSize:9,fontWeight:"800"},blockTime:{color:"#9E8AB4",fontSize:9,fontWeight:"900",fontVariant:["tabular-nums"]},
 errorCard:{width:"100%",borderRadius:16,backgroundColor:"#241318",borderWidth:1,borderColor:"#63333E",padding:12,flexDirection:"row",gap:9,marginTop:13},errorTitle:{color:"#F0BCC5",fontSize:9.5,fontWeight:"900"},error:{color:"#B8848E",fontSize:8.5,lineHeight:13,marginTop:2},reassurance:{color:"#5E6B7B",fontSize:8.5,textAlign:"center",lineHeight:13,marginTop:16,maxWidth:420},
 overlay:{flex:1,backgroundColor:"rgba(3,6,10,.8)",alignItems:"center",justifyContent:"center",padding:20},modal:{width:"100%",maxWidth:420,borderRadius:25,backgroundColor:"#101720",borderWidth:1,borderColor:"#3B4857",padding:19},modalIcon:{width:48,height:48,borderRadius:16,backgroundColor:"#173021",alignItems:"center",justifyContent:"center",marginBottom:13},dangerIcon:{backgroundColor:"#321920"},modalEyebrow:{color:"#7DB58E",fontSize:7.5,fontWeight:"900",letterSpacing:1.1},modalTitle:{color:"#F1F3F5",fontSize:19,fontWeight:"900",marginTop:4},modalTime:{color:"#E8ECF0",fontSize:34,fontWeight:"300",fontVariant:["tabular-nums"],marginTop:12},modalText:{color:"#7B8898",fontSize:9.5,lineHeight:15,marginTop:8},save:{height:51,borderRadius:15,backgroundColor:"#B784FF",marginTop:18,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},saveText:{color:"#160B20",fontSize:10.5,fontWeight:"900"},keep:{height:47,borderRadius:14,backgroundColor:"#171F29",borderWidth:1,borderColor:"#2C3947",marginTop:8,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},keepText:{color:"#C5B0DD",fontSize:9.5,fontWeight:"900"},discardLink:{height:40,alignItems:"center",justifyContent:"center",marginTop:3},discardLinkText:{color:"#9C727C",fontSize:8.5,fontWeight:"900"},discard:{height:49,borderRadius:14,backgroundColor:"#53252F",marginTop:18,alignItems:"center",justifyContent:"center"},discardText:{color:"#F4C7CE",fontSize:10,fontWeight:"900"}
});