import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React,{useEffect,useRef,useState}from"react";
import{BackHandler,FlatList,Modal,Platform,Pressable,StyleSheet,Text,View}from"react-native";
import Screen from "../components/Screen";
import{useSocial}from"../context/SocialContext";
import{useStudy,type PaperSection,type StudyType}from"../context/StudyContext";
import{clearActiveStudyTimer,elapsedFromPersistedTimer,readActiveStudyTimer,writeActiveStudyTimer,type PersistedStudyTimer}from"../lib/timerPersistence";

type Lap={id:number;number:number;duration:number;total:number};
const TYPES:StudyType[]=["Study Session","Revision","Tute Questions","Past Papers","Paper Review","Paper Correction","Paper Discussion","Class"];
const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v;
const fmt=(ms:number)=>{const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`};

export default function StopwatchMinimal(){
 const router=useRouter();
 const params=useLocalSearchParams<{subjectName?:string|string[];topicName?:string|string[];studyType?:string|string[];paperYear?:string|string[];paperSection?:string|string[];attemptNo?:string|string[];assignmentId?:string|string[];assignmentTitle?:string|string[]}>();
 const incomingType=one(params.studyType) as StudyType|undefined;
 const initialType=TYPES.includes(incomingType as StudyType)?incomingType as StudyType:"Study Session";
 const{addSession}=useStudy();const{setStudying}=useSocial();
 const[subjectName,setSubjectName]=useState<string|null>(one(params.subjectName)??null),[topicName,setTopicName]=useState<string|null>(one(params.topicName)??null),[studyType,setStudyType]=useState<StudyType>(initialType),[paperYear,setPaperYear]=useState<number|null>(one(params.paperYear)?Number(one(params.paperYear)):null),[paperSection,setPaperSection]=useState<PaperSection|null>((["MCQ","Essay","Full Paper"] as string[]).includes(one(params.paperSection)??"")?one(params.paperSection) as PaperSection:null),[attemptNo,setAttemptNo]=useState<number|null>(one(params.attemptNo)?Number(one(params.attemptNo)):null);
 const[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false),[laps,setLaps]=useState<Lap[]>([]),[lapStart,setLapStart]=useState(0),[simple,setSimple]=useState(true),[confirmOpen,setConfirmOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[discardConfirm,setDiscardConfirm]=useState(false);
 const startedAt=useRef(new Date()),runStarted=useRef<number|null>(null),accumulated=useRef(0),timer=useRef<ReturnType<typeof setInterval>|null>(null);
 const currentLap=Math.max(0,elapsed-lapStart);
 const nowElapsed=()=>runStarted.current==null?accumulated.current:accumulated.current+(Date.now()-runStarted.current);
 const persist=(isRunning=running,currentAccum=accumulated.current,currentStart=runStarted.current,nextLaps=laps,nextLapStart=lapStart)=>{const snap:PersistedStudyTimer={version:1,running:isRunning,accumulatedMilliseconds:currentAccum,runStartedAtEpoch:currentStart,sessionStartedAtIso:startedAt.current.toISOString(),lapStartedAtMilliseconds:nextLapStart,laps:nextLaps,subjectName,topicName,studyType,paperYear,paperSection,attemptNo,updatedAtEpoch:Date.now()};writeActiveStudyTimer(snap).catch(()=>undefined)};

 useEffect(()=>{let live=true;(async()=>{const saved=await readActiveStudyTimer();if(!live||!saved)return;startedAt.current=new Date(saved.sessionStartedAtIso);accumulated.current=saved.accumulatedMilliseconds;runStarted.current=saved.running?saved.runStartedAtEpoch:null;setElapsed(elapsedFromPersistedTimer(saved));setLapStart(saved.lapStartedAtMilliseconds);setLaps(saved.laps??[]);setRunning(saved.running);setSubjectName(saved.subjectName??null);setTopicName(saved.topicName??null);setStudyType(saved.studyType??"Study Session");setPaperYear(saved.paperYear??null);setPaperSection(saved.paperSection??null);setAttemptNo(saved.attemptNo??null);if(saved.running){timer.current=setInterval(()=>setElapsed(nowElapsed()),250);setStudying(true,saved.subjectName??undefined,saved.topicName??undefined).catch(()=>undefined)}})();return()=>{live=false;if(timer.current)clearInterval(timer.current)}},[]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setStudying(true,subjectName??undefined,topicName??undefined).catch(()=>undefined),60000);return()=>clearInterval(id)},[running,setStudying,subjectName,topicName]);

 const home=()=>router.replace("/(tabs)");
 const requestExit=()=>{if(elapsed>0||running){setConfirmOpen(true);return}home()};
 useEffect(()=>{if(Platform.OS==="web")return;const sub=BackHandler.addEventListener("hardwareBackPress",()=>{requestExit();return true});return()=>sub.remove()},[elapsed,running]);

 const start=()=>{if(running)return;if(elapsed===0){startedAt.current=new Date();accumulated.current=0}else accumulated.current=elapsed;const epoch=Date.now();runStarted.current=epoch;setRunning(true);setError(null);if(timer.current)clearInterval(timer.current);timer.current=setInterval(()=>setElapsed(nowElapsed()),250);persist(true,accumulated.current,epoch);setStudying(true,subjectName??undefined,topicName??undefined).catch(()=>undefined)};
 const pause=()=>{if(!running)return elapsed;const final=nowElapsed();accumulated.current=final;runStarted.current=null;setElapsed(final);if(timer.current){clearInterval(timer.current);timer.current=null}setRunning(false);persist(false,final,null);setStudying(false).catch(()=>undefined);return final};
 const toggleRun=()=>running?pause():start();
 const flagLap=()=>{const total=running?nowElapsed():elapsed,part=Math.max(0,total-lapStart);if(part<=0)return;const lap={id:Date.now(),number:laps.length+1,duration:part,total};const next=[lap,...laps];setElapsed(total);setLaps(next);setLapStart(total);persist(running,running?accumulated.current:total,running?runStarted.current:null,next,total)};
 const resetCurrent=()=>{const total=running?nowElapsed():elapsed;if(total<=lapStart)return;setElapsed(total);setLapStart(total);persist(running,running?accumulated.current:total,running?runStarted.current:null,laps,total)};
 const save=async()=>{if(saving)return;setSaving(true);setError(null);try{const final=running?pause():elapsed,durationSeconds=Math.floor(final/1000);if(durationSeconds<=0){await clearActiveStudyTimer();home();return}const id=await addSession({subjectName:subjectName??"Quick Study",topicName:topicName??"General",studyType,startedAt:startedAt.current.toISOString(),durationSeconds,paperYear,paperSection,attemptNo,laps:laps.map(x=>({number:x.number,duration:x.duration,total:x.total}))});await clearActiveStudyTimer();await setStudying(false).catch(()=>undefined);router.replace({pathname:"/session-complete",params:{sessionId:id,duration:String(durationSeconds),subjectName:subjectName??"Quick Study",topicName:topicName??"General",studyType,assignmentId:one(params.assignmentId),assignmentTitle:one(params.assignmentTitle)}})}catch(e){setError(e instanceof Error?e.message:"Could not save this session.");setConfirmOpen(false)}finally{setSaving(false)}};
 const discard=async()=>{if(running)pause();await clearActiveStudyTimer();await setStudying(false).catch(()=>undefined);setDiscardConfirm(false);setConfirmOpen(false);home()};
 const sessionName=one(params.assignmentTitle)??topicName??subjectName??"Quick Study";
 const contextLine=[subjectName,topicName&&topicName!=="General"?topicName:null].filter(Boolean).join(" · ");

 return <Screen><View style={s.root}>
  <View style={s.top}><Pressable onPress={requestExit} style={s.back}><Ionicons name="arrow-back" size={20} color="#EFF2F5"/></Pressable><View style={s.modeToggle}><Pressable onPress={()=>setSimple(true)} style={[s.modeButton,simple&&s.modeOn]}><Ionicons name="eye-off-outline" size={14} color={simple?"#E9DDF7":"#708092"}/><Text style={[s.modeText,simple&&s.modeTextOn]}>Focus</Text></Pressable><Pressable onPress={()=>setSimple(false)} style={[s.modeButton,!simple&&s.modeOn]}><Ionicons name="list-outline" size={14} color={!simple?"#E9DDF7":"#708092"}/><Text style={[s.modeText,!simple&&s.modeTextOn]}>Details</Text></Pressable></View></View>

  <View style={s.center}>
   <View style={[s.statusPill,running&&s.statusPillLive]}><View style={[s.statusDot,running&&s.statusDotLive]}/><Text style={[s.statusText,running&&s.statusTextLive]}>{running?"SESSION IN PROGRESS":elapsed>0?"PAUSED":"READY TO STUDY"}</Text></View>
   <Text style={s.sessionTitle} numberOfLines={2}>{sessionName}</Text>
   {contextLine&&contextLine!==sessionName?<Text style={s.context} numberOfLines={1}>{contextLine}</Text>:null}
   <Text style={s.clock}>{fmt(currentLap)}</Text>
   <Text style={s.clockLabel}>{laps.length?`CURRENT BLOCK · FLAG ${laps.length+1}`:"FOCUS TIME"}</Text>
   {!simple?<View style={s.detailsCard}><View style={s.detailCell}><Text style={s.detailLabel}>SESSION TYPE</Text><Text style={s.detailValue}>{studyType}</Text></View><View style={s.detailDivider}/><View style={s.detailCell}><Text style={s.detailLabel}>TOTAL TIME</Text><Text style={s.detailValue}>{fmt(elapsed)}</Text></View><View style={s.detailDivider}/><View style={s.detailCell}><Text style={s.detailLabel}>FLAGS</Text><Text style={s.detailValue}>{laps.length}</Text></View></View>:null}

   <View style={s.actionStack}>
    <Pressable onPress={toggleRun} style={[s.primaryAction,running&&s.pauseAction]} accessibilityRole="button"><Ionicons name={running?"pause":"play"} size={24} color="#160B20"/><View><Text style={s.primaryLabel}>{running?"Pause session":elapsed>0?"Resume session":"Start session"}</Text><Text style={s.primaryHint}>{running?"Your time stays saved while paused":elapsed>0?"Continue from where you stopped":"Begin tracking focused study time"}</Text></View></Pressable>
    <View style={s.secondaryRow}>
      {!simple?<Pressable onPress={flagLap} disabled={currentLap<=0} style={[s.secondaryAction,currentLap<=0&&s.dim]}><Ionicons name="flag-outline" size={19} color="#D9C2F4"/><Text style={s.secondaryLabel}>Mark block</Text></Pressable>:null}
      <Pressable onPress={()=>setConfirmOpen(true)} style={[s.secondaryAction,s.finishAction,{flex:simple?1:1}]}><Ionicons name="checkmark-circle-outline" size={20} color="#AEE1BF"/><Text style={[s.secondaryLabel,s.finishLabel]}>Finish & save</Text></Pressable>
    </View>
   </View>

   {!simple&&currentLap>0?<Pressable onPress={resetCurrent} style={s.reset}><Ionicons name="refresh-outline" size={14} color="#7D8998"/><Text style={s.resetText}>Start a fresh current block without deleting session time</Text></Pressable>:null}
   {error?<View style={s.errorCard}><Ionicons name="alert-circle-outline" size={17} color="#E7A4AF"/><Text style={s.error}>{error}</Text></View>:null}
   {!simple&&laps.length?<View style={s.lapWrap}><View style={s.lapHead}><Text style={s.lapHeadTitle}>FOCUS BLOCKS</Text><Text style={s.lapHeadMeta}>{laps.length} marked</Text></View><FlatList data={laps} keyExtractor={x=>String(x.id)} style={s.laps} renderItem={({item})=><View style={s.lapRow}><View style={s.lapBadge}><Text style={s.lapBadgeText}>{item.number}</Text></View><Text style={s.lapNo}>Block {item.number}</Text><Text style={s.lapTime}>{fmt(item.duration)}</Text></View>}/></View>:null}
  </View>

  <Modal visible={confirmOpen} transparent animationType="fade" onRequestClose={()=>setConfirmOpen(false)}><View style={s.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setConfirmOpen(false)}/><View style={s.modal}>
    {!discardConfirm?<><View style={s.modalIcon}><Ionicons name="checkmark-done-outline" size={27} color="#AEE1BF"/></View><Text style={s.modalEyebrow}>SESSION SUMMARY</Text><Text style={s.modalTitle}>Ready to finish?</Text><Text style={s.modalTime}>{fmt(running?nowElapsed():elapsed)}</Text><Text style={s.modalText}>Save this study time and continue to the completion screen, or return to the timer.</Text><Pressable disabled={saving} onPress={save} style={s.save}><Ionicons name="checkmark" size={18} color="#160B20"/><Text style={s.saveText}>{saving?"Saving session…":"Finish & save session"}</Text></Pressable><Pressable disabled={saving} onPress={()=>setConfirmOpen(false)} style={s.keep}><Text style={s.keepText}>Keep studying</Text></Pressable><Pressable disabled={saving} onPress={()=>setDiscardConfirm(true)} style={s.discardLink}><Text style={s.discardLinkText}>Discard session instead</Text></Pressable></>:<><View style={[s.modalIcon,s.dangerIcon]}><Ionicons name="trash-outline" size={25} color="#ECAAB5"/></View><Text style={s.modalTitle}>Discard this session?</Text><Text style={s.modalText}>This removes the timer and does not add any study time. This cannot be undone.</Text><Pressable disabled={saving} onPress={discard} style={s.discard}><Text style={s.discardText}>Yes, discard session</Text></Pressable><Pressable disabled={saving} onPress={()=>setDiscardConfirm(false)} style={s.keep}><Text style={s.keepText}>Go back</Text></Pressable></>}
  </View></View></Modal>
 </View></Screen>
}

const s=StyleSheet.create({
 root:{flex:1,backgroundColor:"#080D14"},top:{height:70,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:42,height:42,borderRadius:14,backgroundColor:"#121A24",borderWidth:1,borderColor:"#24303C",alignItems:"center",justifyContent:"center"},modeToggle:{flexDirection:"row",backgroundColor:"#111923",borderRadius:14,padding:3,borderWidth:1,borderColor:"#293646"},modeButton:{height:35,borderRadius:11,paddingHorizontal:10,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:5},modeOn:{backgroundColor:"#34244A"},modeText:{color:"#708092",fontSize:8.5,fontWeight:"900"},modeTextOn:{color:"#E9DDF7"},
 center:{flex:1,alignItems:"center",paddingHorizontal:20,paddingBottom:34,paddingTop:14},statusPill:{height:29,borderRadius:15,backgroundColor:"#171F29",borderWidth:1,borderColor:"#2B3745",paddingHorizontal:11,flexDirection:"row",alignItems:"center",gap:6},statusPillLive:{backgroundColor:"#13231A",borderColor:"#2E6040"},statusDot:{width:6,height:6,borderRadius:3,backgroundColor:"#718092"},statusDotLive:{backgroundColor:"#79D09A"},statusText:{color:"#7D8A9A",fontSize:7,fontWeight:"900",letterSpacing:.9},statusTextLive:{color:"#8FD4A7"},sessionTitle:{maxWidth:500,color:"#EFF2F5",fontSize:16,fontWeight:"900",textAlign:"center",marginTop:15},context:{maxWidth:500,color:"#788698",fontSize:8.5,fontWeight:"800",marginTop:4,textAlign:"center"},clock:{color:"#F7F8FA",fontSize:58,fontWeight:"300",fontVariant:["tabular-nums"],letterSpacing:1.4,marginTop:25},clockLabel:{color:"#6C798A",fontSize:7.5,fontWeight:"900",letterSpacing:1.2,marginTop:5},detailsCard:{width:"100%",maxWidth:520,minHeight:68,borderRadius:18,backgroundColor:"#0E151E",borderWidth:1,borderColor:"#25313E",flexDirection:"row",alignItems:"center",marginTop:20,paddingHorizontal:8},detailCell:{flex:1,alignItems:"center",justifyContent:"center",paddingHorizontal:5},detailLabel:{color:"#5F6D7F",fontSize:6.2,fontWeight:"900",letterSpacing:.8},detailValue:{color:"#C8D0D9",fontSize:9,fontWeight:"900",marginTop:4,textAlign:"center"},detailDivider:{width:1,height:34,backgroundColor:"#26313D"},
 actionStack:{width:"100%",maxWidth:520,marginTop:26},primaryAction:{minHeight:72,borderRadius:20,backgroundColor:"#B784FF",paddingHorizontal:17,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:12,shadowColor:"#B784FF",shadowOpacity:.18,shadowRadius:14,shadowOffset:{width:0,height:6},elevation:8},pauseAction:{backgroundColor:"#C9A0FF"},primaryLabel:{color:"#160B20",fontSize:13,fontWeight:"900"},primaryHint:{color:"#40294F",fontSize:7.5,fontWeight:"800",marginTop:3},secondaryRow:{flexDirection:"row",gap:8,marginTop:9},secondaryAction:{flex:1,minHeight:49,borderRadius:15,backgroundColor:"#1A1523",borderWidth:1,borderColor:"#40324E",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},finishAction:{backgroundColor:"#13231A",borderColor:"#2E6040"},secondaryLabel:{color:"#D5C0EE",fontSize:9,fontWeight:"900"},finishLabel:{color:"#AEE1BF"},dim:{opacity:.35},reset:{flexDirection:"row",alignItems:"center",gap:6,marginTop:14,paddingVertical:6},resetText:{color:"#697688",fontSize:7.5,fontWeight:"800"},errorCard:{maxWidth:520,width:"100%",borderRadius:13,backgroundColor:"#29181D",borderWidth:1,borderColor:"#5A313B",padding:10,flexDirection:"row",alignItems:"center",gap:8,marginTop:12},error:{flex:1,color:"#E7A4AF",fontSize:8.5,lineHeight:13},
 lapWrap:{width:"100%",maxWidth:520,borderRadius:17,backgroundColor:"#0E151E",borderWidth:1,borderColor:"#25313E",padding:10,marginTop:15},lapHead:{flexDirection:"row",justifyContent:"space-between",paddingHorizontal:3,paddingBottom:5},lapHeadTitle:{color:"#687789",fontSize:6.8,fontWeight:"900",letterSpacing:1},lapHeadMeta:{color:"#675779",fontSize:6.8,fontWeight:"900"},laps:{width:"100%",maxHeight:150},lapRow:{height:40,borderTopWidth:1,borderTopColor:"#1E2935",flexDirection:"row",alignItems:"center"},lapBadge:{width:24,height:24,borderRadius:8,backgroundColor:"#21182D",alignItems:"center",justifyContent:"center"},lapBadgeText:{color:"#CBB0EA",fontSize:7,fontWeight:"900"},lapNo:{flex:1,color:"#778597",fontSize:8,fontWeight:"900",marginLeft:8},lapTime:{color:"#BEC7D0",fontSize:10,fontWeight:"900",fontVariant:["tabular-nums"]},
 overlay:{flex:1,backgroundColor:"rgba(3,6,10,.82)",alignItems:"center",justifyContent:"center",padding:20},modal:{width:"100%",maxWidth:400,borderRadius:25,backgroundColor:"#101720",borderWidth:1,borderColor:"#344154",padding:20,alignItems:"center"},modalIcon:{width:54,height:54,borderRadius:18,backgroundColor:"#16271C",borderWidth:1,borderColor:"#315C40",alignItems:"center",justifyContent:"center",marginBottom:12},dangerIcon:{backgroundColor:"#29181D",borderColor:"#5A313B"},modalEyebrow:{color:"#758396",fontSize:7,fontWeight:"900",letterSpacing:1.1},modalTitle:{color:"#F2F4F7",fontSize:20,fontWeight:"900",textAlign:"center",marginTop:4},modalTime:{color:"#CDB6E6",fontSize:28,fontWeight:"400",fontVariant:["tabular-nums"],marginTop:8},modalText:{color:"#788697",fontSize:9.5,lineHeight:15,textAlign:"center",marginTop:8,marginBottom:17,maxWidth:330},save:{width:"100%",height:50,borderRadius:15,backgroundColor:"#B784FF",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},saveText:{color:"#160B20",fontSize:10.5,fontWeight:"900"},keep:{width:"100%",height:43,alignItems:"center",justifyContent:"center",marginTop:5},keepText:{color:"#AAB5C1",fontSize:9,fontWeight:"900"},discardLink:{paddingVertical:7,paddingHorizontal:12},discardLinkText:{color:"#7E6871",fontSize:7.8,fontWeight:"800"},discard:{width:"100%",height:48,borderRadius:14,backgroundColor:"#351B22",borderWidth:1,borderColor:"#683642",alignItems:"center",justifyContent:"center"},discardText:{color:"#ECAAB5",fontSize:9.5,fontWeight:"900"}
});