create table if not exists public.whatsapp_release_subscribers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  phone_e164 text not null unique check (phone_e164 ~ '^\\+[1-9][0-9]{7,14}$'),
  enabled boolean not null default true,
  consent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_release_deliveries (
  id bigint generated by default as identity primary key,
  subscriber_id uuid references public.whatsapp_release_subscribers(id) on delete set null,
  app_version text not null,
  release_url text not null,
  status text not null check (status in ('sent','failed')),
  provider_response text,
  created_at timestamptz not null default now()
);

alter table public.whatsapp_release_subscribers enable row level security;
alter table public.whatsapp_release_deliveries enable row level security;

create policy "Users can view own WhatsApp subscription"
on public.whatsapp_release_subscribers for select
to authenticated using (auth.uid() = user_id);

create policy "Users can manage own WhatsApp subscription"
on public.whatsapp_release_subscribers for all
to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
