{
  "expo": {
    "name": "Study Arc",
    "slug": "study-arc",
    "version": "1.0.0",
    "orientation": "default",
    "scheme": "studyarc",
    "userInterfaceStyle": "dark",

    "icon": "./assets/images/icon.png",

    "plugins": [
      "expo-router",
      "expo-notifications",
      [
        "expo-splash-screen",
        {
          "backgroundColor": "#080D14",
          "image": "./assets/images/splash-icon.png",
          "imageWidth": 1
        }
      ],
      [
        "expo-image-picker",
        {
          "photosPermission": "Study Arc uses your photo library only when you choose a profile picture.",
          "microphonePermission": false
        }
      ]
    ],

    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.studyarc.app",
      "buildNumber": "1"
    },

    "android": {
      "package": "com.studyarc.app",
      "versionCode": 1,
      "predictiveBackGestureEnabled": false,
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/icon.png",
        "backgroundColor": "#080D14"
      }
    },

    "web": {
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },

    "experiments": {
      "typedRoutes": false
    }
  }
}
